### ISSUE TITLE
EntityPlayer

### ISSUE THREAD

**Issue by iKays** [CyberdyneCC/Thermos#114]
It is possible to add net/minecraft/server/v1_7_R4/EntityPlayer in the library :3
Cause some of the plugin im using it keep saying "java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/EntityPlayer"

**Comment by iKaneki-Ken** [comment]
No it's not.libraries are basically engines, a player can't be an engine.

**Comment by Robotia** [comment]
Might be able to make a wrapper for particle effect library

**Comment by iKays** [comment]
Its not a particle effect Dx, Its for a chat control plugin i purchased on spigot lol.

**Comment by Robotia** [comment]
It is in general due to plugins thinking that the server doesn't remap imports and trying up get Class(). Needs to be fixed for craft Bukkit in general

**Comment by iKays** [comment]
Do you think this will be fixable or impossible :3

**Comment by Robotia** [comment]
It is possible but will require time. Also, you should never pay for a plugin if there's something free out there that works just as well.

**Comment by iKays** [comment]
Take your time, I was just wondering :3 THank you for quick answer

**Comment by Robotia** [comment]
Will not be done in the near future, sorry.
