### ISSUE TITLE
[BUG] Item map doesn't work properly

### ISSUE THREAD

**Issue by skmedix** [CyberdyneCC/Thermos#119]
**What is wrong:**
Rendered image disappears from the map.

_Video:_ https://skmedix.pl/share/2016-02-17-0152-42.mp4
_Logs:_ https://gist.github.com/skmedix/259223f990e10669bd09

**List of plugins:**
http://dev.bukkit.org/bukkit-plugins/pixelator/ _(Best to reproduce)_
http://dev.bukkit.org/bukkit-plugins/imageonmap/
http://dev.bukkit.org/bukkit-plugins/imagemaps/
http://dev.bukkit.org/bukkit-plugins/imgmap/

**How to reproduce:**
Just use commands:

```
/pixel create http://dev.bukkit.org/media/images/51/344/pixelator2.png
/pixel give 0
```

And look at the results.

**Affects Versions:**
All versions since Cauldron.
Bug occurs in all versions of the engine. (Cauldron, KCauldron, Thermos)

**Comment by Robotia** [comment]
Possibly fixed by 17d71edfe280765f663f27ee68f3861852eb0d41

**Comment by Time6628** [comment]
Assuming this is fixed.

**Comment by skmedix** [comment]
Would be awesome, but nah. This bug still exist.

**Comment by Eufranio** [comment]
I can use maps rendered by FramePicture in my server, is it your problem? The video seems to be offline...

**Comment by skmedix** [comment]
Video is offline, because there was a few IP's, that I don't want's to public. I gave @Robotia a special link for this file. Also that's right, frames are working fine, but problem is with item maps. I'll try to find out a fix for them in next few days, but I need more free time. Im not completely sure, if that's not a bug with Forge on client side, because server is sending map to client, but after a while, map is overridden with vanilla generated view.
