### ISSUE TITLE
[Bug] Armor issue with Kami installed (All thermos)

### ISSUE THREAD

**Issue by TerdyTheTerd** [CyberdyneCC/Thermos#128]
I will link to another issue made over at KCauldron since I'm too lazy to rewrite everything, this issue has been present ever since november 2015, and in every version of Kcauldron since then as well as Thermos versions. That issue should follow contributing guidelines much better than this one.

https://gitlab.prok.pw/KCauldron/KCauldron/issues/347

Basically there is something within the Kami module from Thaumic Tinkerer that messes up high tier (most high tier armors use energy) to where they all act like diamond armor. Kami used to be a seperate addon for TT, but was later merged and can be disabled in the config (this obviously disables the entirety of the kami mod). I believe it stems from this [class](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/blob/1.7-final/src/main/java/thaumic/tinkerer/common/core/handler/kami/KamiArmorHandler.java) not sure on that one, I do know it is most likely from kami, as mentioned in that issue disabling kami removes the issue. I did just test this on thermos build 27 to double check, and it is still present.

**Comment by Robotia** [comment]
I had a similar armor related issue in December, where, strangely, iron armor wearers took no damage from other players. Will try to see what's up

**Comment by Robotia** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/commit/d4a181d43109c191045d6dcaa8cbd3bac883c83e

**Comment by Robotia** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/commit/896e45556a16ac30320acc245a57afcfa232a20e

**Comment by Robotia** [comment]
https://gitlab.prok.pw/KCauldron/KCauldron/commit/923b9e81a07fd51c8b8ee10512ac822ad1f79892

**Comment by Robotia** [comment]
@TerdyTheTerd Is this fixed? I think it is related to the TFC damage bug, which should also be fixed now.

**Comment by Robotia** [comment]
Fixed.
