### ISSUE TITLE
[Todo Long Term] Code Optimization

### ISSUE THREAD

**Issue by Robotia** [CyberdyneCC/Thermos#182]
Make sure Thermos code aligns with [these](http://www.appperfect.com/support/java-coding-rules/optimization.html) rules.

**Comment by Bogdan-G** [comment]
:O there are a lot of refactoring the code you need.

**Comment by Robotia** [comment]
Yup...

**Comment by Yive** [comment]
This is why the revamp should just be worked on instead of the current state of Thermos.

**Comment by iKaneki-Ken** [comment]
I agree with Yive. I know it's easy to say for me as I'm not providing any help with code, but it'd be better to scrap everything that has been done to Cauldron VIA KCauldron and start from Cauldron B212.

**Comment by Robotia** [comment]
Unlikely

**Comment by Bogdan-G** [comment]
^ meh :)
