### ISSUE TITLE
[Proposal] Stop Vanilla Blocks from Unnecessary Chunk Loading

### ISSUE THREAD

**Issue by Robotia** [CyberdyneCC/Thermos#21]
I have found that vanilla blocks like BlockGrass.java and BlockStaticLiquid.java load chunks when getting/setting blocks. 

I propose that chunkExists() be implemented in several of these to prevent the server from being silly and updating blocks by loading chunks....

**Comment by Robotia** [comment]
Put off indefinitely until Event Linking and PaperSpigot grabs are done.

**Comment by Cracks777** [comment]
@Robotia is there a way that i can pm you?

**Comment by Robotia** [comment]
@Cracks777 Have Discord? I'll be on the TCPR Discord in a moment.

**Comment by Cracks777** [comment]
lol i have teamspeak?

**Comment by Robotia** [comment]
@Cracks777 Join this: https://discord.gg/0VmBoNh2sE2t5yKh

**Comment by Robotia** [comment]
Unlikely.
