### ISSUE TITLE
Event-linking to-do list (please add on)

### ISSUE THREAD

**Issue by Robotia** [CyberdyneCC/Thermos#22]
The following need to be linked from Forge to Bukkit (so Forge Items code isn't called if Bukkit stops the event early):
+ PlayerInteractEvent
+ PlayerEvent.HarvestCheck
+ PlayerEvent.BreakSpeed
+ PlayerUseItemEvent.Start
+ PlayerUseItemEvent.Tick
+ PlayerUseItemEvent.Finish

**Comment by iKaneki-Ken** [comment]
I don't know the specific event, but I used to be able to block Mining Lasers from working in claims, now they completely bypass all protections because Bukkit doesn't see the item being used.

**Comment by Robotia** [comment]
@iKaneki-Ken Probably has to do with "Laser Beam" entities, I'll see what I can do with that.

**Comment by Robotia** [comment]
Hmm...thinking EntityJoinWorldEvent, EntityInteractEvent, and EntityEvent will need linking then.

**Comment by linkinkov** [comment]
@iKaneki-Ken just use IC2 with events https://github.com/gamerforEA/IC2-FakePlayers

**Comment by Robotia** [comment]
@linkinkov I have seen this before but it does not work with IC2Classic, only the official builds. It is also not a permanent solution for other mods which sadly do not have FakePlayers implemented.
:disappointed_relieved:

**Comment by linkinkov** [comment]
@Robotia if needed i have events for IC2Classic. Anyway you cant implement all forge events to bukkit or have a lot problem with plugins.

**Comment by Robotia** [comment]
@linkinov Would love it if you could share that. Also, it was never my plan to make every forge event align with every Bukkit event. The idea of this linking is to prevent forge from ever notifying a mod of an event if Bukkit prevents it beforehand.

**Comment by Robotia** [comment]
@linkinkov I found the regular IC2 fake players, but not the classic, could you share them please?

**Comment by linkinkov** [comment]
@Robotia only im PM can for personal use

**Comment by Robotia** [comment]
@linkinkov Have discord? ))

**Comment by linkinkov** [comment]
@Robotia sometimes with team :)

**Comment by Robotia** [comment]
@linkinkov I have email you, please check

**Comment by linkinkov** [comment]
@Robotia reply :3

Oh my mistake, i think that "discord" not the chat service :D

**Comment by Robotia** [comment]
PlayerInteractEvent has been linked to Forge's interact event. If Bukkit's event fails, forge never knows there was an interaction. This has introduced a new problem though: Bukkit's PlayerInteract double-runs.

**Comment by linkinkov** [comment]
And a lot of dupes :)

**Comment by Robotia** [comment]
@linkinkov Dupes?

**Comment by linkinkov** [comment]
Yes, for example: https://www.youtube.com/watch?v=2-rxxQniua0

**Comment by Robotia** [comment]
@linkinkov That does not deal with double-run of event. Does not mean double-click.

**Comment by Robotia** [comment]
Unlikely.
