### ISSUE TITLE
[ToDo] RegionFile chunk existence thread

### ISSUE THREAD

**Issue by Robotia** [CyberdyneCC/Thermos#222]
Similar to how chunks can load asynchronously, there should be an asynchronous thread to handle requests for the existence of chunks with a region file. The seek time when players fly across the server makes chunk-loading take forever.

Alternatively, chunk existence data could be saved in a existingchunks.dat so a RandomAccess reader would not need to be used.

**Comment by TerdyTheTerd** [comment]
Anything to make chunks load faster or smoother would be nice, one of the big issues on my server is that players lag the server when they start flying around with their draconium armor at full speed.

**Comment by Robotia** [comment]
Basic implementation of RAM disk chunks has failed; MappedMemoryBuffers cannot be expanded when written to.

**Comment by Robotia** [comment]
This failed, not sure how to go forward with it. If someone wants to look at it and make *code changes*, I'd be happy to help out.
