### ISSUE TITLE
[ToDo] Scrape out tile entity tick limiting and impose "20TPS" always feature

### ISSUE THREAD

**Issue by Robotia** [CyberdyneCC/Thermos#223]
@Isolonice reminded me that I had mentioned limiting tile entity processing so that the server maintains a healthy 20 TPS.
> and what about your idea of limit tick to 50.00 then put the rest on the next tick ?

Unprocessed tiles would be pushed to the next tick and processed first.

However, this could also be problematic because the list could build up indefinitely with servers running below 10 TPS normally. To that end, certain TileEntity classes would be algorithmically preferred to tick. Those that have very small tick times will be allowed to tick every tick, those that perform more poorly will tick less often. Also, specific tiles, regardless of their type would be ticked less if they tend to lag.

This feature could be disabled for certain tiles through the `tileentities.yml`.

**Comment by DraksterAU** [comment]
Very smart... 
Can you please allow to be turned on/off for all tile entities with a boolean config check also?
Just in case someone has a large number of mods that don't work too well with it.

**Comment by Robotia** [comment]
Why would you want to disable all tile entities? 0.o
That would remove an entire part of the game

**Comment by DraksterAU** [comment]
@Robotia I mean Disable this feature for all tile entities.

Your saying it will be on for all by default and we have to disable it for each, one by one.
Just making sure you do a disable for all as an option :P

**Comment by Robotia** [comment]
Ah yes there will definitely be a global disable option.

**Comment by Robotia** [comment]
Conversation with kristi further fleshed out this idea.
```calculate a running mean of tile entity ticktimes
in calculating the mean tick time of all tiles of a type, we can calculate the standard deviation
there is a rule in statistics called the empirical rule which says that basically..
68% of tiles will be with in 1 standard deviation
95% within 2
99.7% within 3```

**Comment by linkinkov** [comment]
https://github.com/wildex999/TickDynamic impliment this to thermos would be great.
But now its not working.

**Comment by Robotia** [comment]
I thought @nallar made tick dynamic 0.o

**Comment by nallar** [comment]
Unfortunately, I haven't trademarked "Tick" in the name of a mod.

**Comment by linkinkov** [comment]
More info about TD: http://mods.stjerncraft.com/tickdynamic/

**Comment by Robotia** [comment]
Oh...and @nallar still loving that face :3

**Comment by Robotia** [comment]
@linkinkov it is not good idea to take that and implement because I do not want to get in trouble with them. Since we have control of actual server code here we can do much better with it.

**Comment by linkinkov** [comment]
I mean use some features/ideas :)
Because:
- Little to no Block lag
- Interact with TileEntities(Chests, Machines etc.) without delays
- Chunk loading and teleporting without long pauses
- No player lag when moving around
- No disconnects due to long ticks
- Generally lower ping and a more responsive server

It sounds great

**Comment by Robotia** [comment]
That is the general idea yes.

**Comment by vadimyer** [comment]
When would this feature be available? And at least "dynamic view" feature.

**Comment by Robotia** [comment]
Since I am a one man team, you will likely have to wait a long time for this, I cannot make any promises as to when it will be done.

**Comment by iKaneki-Ken** [comment]
Wondering if it'd be better to build off BloodMC's tile entity limiting system instead of scrapping it altogether.

**Comment by Robotia** [comment]
Unlikely.
