### ISSUE TITLE
*Suggestion* Poweruser/Nallar Optimizations?

### ISSUE THREAD

**Issue by Zilacon** [CyberdyneCC/Thermos#230]
Hello, first of all id like to thank you for your hard work on thermos! A lot of things were bugged on KCauldron and Prototik never seemed to care about 90% of the issues reported.

Anyways my friend Poweruser is a performance freak like myself and hes completely recoded bukkit in his server version called MineTick and Migot located here:
https://github.com/Poweruser/MinetickMod/tree/v1.7.10
https://github.com/Poweruser/Minetick
https://github.com/Poweruser/Migot

He setup asynchronous world saving, multiple threads per world, bandwidth compression, and many more optimizations that work wonders for my HUB.

But one thing that i suggested to him and he implemented that was a MASSIVE performance improvement and even made him very happy with the results as well was a FOV Chunk Loader. Basically the chunks will only load on the server based on the players FOV and will load outwards of the player like a cone. Instead of randomly loading chunks all over the place. When the player's FOV exits the chunks after X amount of seconds the chunk will unload.

I am just asking if you could look into his work and implement his improvements into thermos. I asked him about making a Forge version of minetick and he said he wouldn't do it but he would fully support anyone who wanted to use his improvements to make a forge version.

Also another thing that would be great to add would be features from TickThreading or nTweaks by Nallar. I believe you have had previous dealings with nallar in the past which makes this easier to explain.

In TickThreading it has a "Deadlock Detector" and in the case of the server deadlocking it notifies players and tries to recover, if it cannot then it shutsdown the server. Allowing a restart script to reboot the server.

It also has a world unloader for unused worlds and it unloads tile entities, entities, etc in them as well. Both TickThreading and nTweaks have this.

He also has a custom AI and Mob spawning system implemented as well. But i believe Poweruser's AI implementation is better than nallars, but I am not a programmer so you will have to be the judge of this.

Thanks!

**Comment by Robotia** [comment]
Don't know how possible this is. I have limited time to fix issues as it is and I am a one man team :confounded:

**Comment by Zilacon** [comment]
Maybe Poweruser and Nallar would be willing to help?

**Comment by Robotia** [comment]
@nallar has a life unlike me (I think), not sure about Poweruser

**Comment by TerdyTheTerd** [comment]
If only java devs with experience in minecraft modding were cheap (and available) to hire :/

**Comment by Zilacon** [comment]
@TerdyTheTerd I know right? Im looking for devs for my network and the latest one wanted $75/hr!

**Comment by Robotia** [comment]
Unlikely.
