### ISSUE TITLE
Do you have some will to update Thermos to 1.9?

### ISSUE THREAD

**Issue by vpontin** [CyberdyneCC/Thermos#264]
I'm sorry if the question violates the rules... but i need to ask this (since i dont find any issue similar, open or closed).

The title is self-descriptive: Do you have some will to update Thermos to 1.9, using the newest [Forge](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.9.html) and [Spigot](https://www.spigotmc.org/threads/minecraft-1-9-release.127186/) builds?

Thanks in advance!

**Comment by iKaneki-Ken** [comment]
No point, Sponge is already released for that.

**Comment by Robotia** [comment]
People still want to use Bukkit plugins in 1.9 
I don't know if this can be done in a timely manner.
:confused:

**Comment by vpontin** [comment]
I dont know. I never liked Sponge, for some reason.
And yep, spigot are becoming derpy due to paid plugins in the forums, but i still feel better using it (maybe because of [TrainCarts](https://github.com/bergerhealer/TrainCarts) (something still isnt compatible with Thermos 1.7.10, and according to its creator it could never be, see https://github.com/bergerhealer/BKCommonLib/issues/8)

**Comment by Zilacon** [comment]
I would much rather use Thermos than that monstrosity called Sponge.

**Comment by DraksterAU** [comment]
@vpontin Why would you use TrainCarts on Thermos when you can try out things like SteveCarts or Railcraft? :)

**Comment by vpontin** [comment]
@DraksterAU these mods conflicts with several other mods in my modpack. And personally i think TrainCarts is FAR MORE better, simply and feels more "Minecraft" than that crap mods.

**Comment by DraksterAU** [comment]
Name one mod that conflicts with railcraft...

**Comment by DraksterAU** [comment]
@robotia there are projects underway to create a link between the Bukkit and sponge apis.... Might not need to do one yourself?

**Comment by Robotia** [comment]
That is true, but from what I've seen I'm not sure that it is completely possible to make them compatible :confused: 
We will see when most of the issues for 1.7.10 are fixed.

**Comment by vpontin** [comment]
Well, i want to use TrainCarts. Period.

And the subject here is about a possible update to 1.9. Please dont derail the issue. ;)

**Comment by DraksterAU** [comment]
Lol. Each to their own. Just try out railcraft sometime ;)

**Comment by vpontin** [comment]
I tried. Too costly spawns vanilla villagers when using MCA, and don't have half of the automated station functions of TrainCarts.

**Comment by DraksterAU** [comment]
Explain the villager thIng? I've never seen it do that for me.

What functions are missing ? Quite possible your not implementing the railcraft way of doing something.... You can do some pretty complex stuff haha

**Comment by Robotia** [comment]
If you want to have a discussion, please use Discord. As @vpontin said, don't "derail" the issue...! (horrible pun)

**Comment by vpontin** [comment]
Yep @Robotia, but well, what are the major pains "merging" spigot and forge now in 1.9? Some new implementation of one or both of systems can conflict each other, or other things...?

**Comment by Robotia** [comment]
Spigot code is formatted completely differently than Minecraft Forge code and there are many changes spigot makes which would not be safe for forge without additional coding. This is mainly why there are so many problems with achieving compatibility.

**Comment by vpontin** [comment]
Just saw this today.

Very sad. I use a clean Forge server in 1.8.9 and miss a lot administration (permissions, locking) and multiworld plugins Bukkit/Spigot provides.

Sticking to 1.7 IMO is a bad thing, since virtually all mods for that version dont have any support et all (Forge is the prime example, vide [here](https://github.com/MinecraftForge/MinecraftForge/issues/2735)), and any still bugs in both Forge and mods will not go to be fixed.

**Comment by spannerman79** [comment]
There is already something else planned for that - SpongeForge.

**Comment by vpontin** [comment]
Sponge is horrible, have for now low pluigin support and overpopulated with selfish devs.

Spigot, on the other hand, still have a lot of popularity and a active dev base and several systems stable.

The best alternative IMO would be if devs port your plugins direcly to Forge (and [this little thing](https://github.com/MinecraftForge/MinecraftForge/issues/2899) would be of much help), eliminating the need of a 3rd api for that.

How this will not be implemented in sight and most bukkit plugin devs simply migrated to Spigot, a 1.8+ joint of both still would rock.

**Comment by DraksterAU** [comment]
@vpontin There are literally hundreds if not thousands of hours of coding to enable 1.8 support for Thermos.
There are two developers.

Do the math. Unless you can pay their wages for a year it will not happen ... Especially when sponge exists and 1.8 is already superseded by mojang.

**Comment by spannerman79** [comment]
Err you do know the so called selfish deva were the actual cauldron devs as well as forge dev'a plus others?  I don't think bloodmc, md_5 and others would like it if you said they we selfish.......

**Comment by vpontin** [comment]
They could not be selfish, but a lot used the bukkit trouble to auto-promote.

**Comment by DraksterAU** [comment]
Bukkit code is is largely illegal to use unfortunately and was written a very long time ago.... So was due for an overhaul.

Sponge is the new Bukkit and supported by Forge developers, Bukkit developers and even the author of Cauldron (BloodMC)... So I would hardly say they are unjustified in promoting it.

Don't forget thermos/cauldron code is covered by the DCMA on Bukkit... Thermos technically shouldn't exist.

**Comment by vpontin** [comment]
Yep, that's the truth.

Years and years being the best option for server to went down the drain because someone was forget to be hired by Mojang.

**Comment by DraksterAU** [comment]
It's actually not better than sponge from a logical point of view - Cauldron always had issues. Serious ones.... And never had 100% mod and plugin support.

All sponge plugins that work with the sponge version you have installed and all mods that work with the forge version you have installed will work side by side without issue.....

Think of this as a hard time...  But things will definitely get better once sponge has a decent plugin base.
