### ISSUE TITLE
Super optimized for modded servers core

### ISSUE THREAD

**Issue by BlayzerQ** [CyberdyneCC/Thermos#266]
This is super-optimized for modded servers core, but without bukkit-api (No Suppor Plugins)
May be check functions and add to Thermos.
https://gitlab.ultramine.ru/ultramine/ultramine_core/network/master

**Comment by JewishDog** [comment]
Это разные ядра. Thermos'у придется многое переписывать. Проще попросить автора Ultramine добавить поддержку bukkit-api.

**Comment by BlayzerQ** [comment]
Я лишь предложил реализовать некоторые функционал этого ядра. Автор его забросил.
Но ядро очень хорошо себя показывало, по сравнению с другими ядрами - лагов не было вообще.

**Comment by JewishDog** [comment]
Ну может быть авторы спишутся

**Comment by Bogdan-G** [comment]
о и тут тоже предложение, ну давайте посмотрим как дело пойдет тут.

**Comment by JewishDog** [comment]
@Bogdan-G Можешь дать ссылочку на твоё ядро? Хочу глянуть

**Comment by Bogdan-G** [comment]
@JewishDog https://github.com/Bogdan-G/FFoKC и по сути все форки что я редачу у меня в профиле на гитхабе посмотреть можно в списке репозитариев.

**Comment by Robotia** [comment]
Unlikely.
