### ISSUE TITLE
[BUG] Opis broken with latest commits.

### ISSUE THREAD

**Issue by iKaneki-Ken** [CyberdyneCC/Thermos#284]
**Server Log:** http://pastebin.com/Ksu521bB

**FML Log(s):** http://pastebin.com/Ksu521bB (Both Server log and FML log show the same data)

**Explanation of issue:** Updated to the latest commits and made a custom build.

**How to recreate this issue:** Launch a server

**Modpack Name:** Infinity, Direwolf20.

**Mods Installed:** http://www.feed-the-beast.com/projects/ftb-presents-direwolf20/files/2272690

**Plugins Installed:** N/A as I've tried without plugins and got the same result.

**Warmroast Report:** *(Optional)*

**Thermos Version:** Custom build with the latest commits at the time of this post.

**Forge Version:** 1614

**Comment by Robotia** [comment]
Does it work fine on 54?

**Comment by Hoborific** [comment]
No.

**Comment by linkinkov** [comment]
Hm i think that opis cant work with cofh tweaks

**Comment by Robotia** [comment]
Is there any 5X build or 4X build it works with so I can better pinpoint the issue?

**Comment by Hoborific** [comment]
using 1614 build 53 works.

**Comment by Robotia** [comment]
Thanks!

**Comment by Robotia** [comment]
Opis will not be supported.
