### ISSUE TITLE
[iChunHats] mod commands from rcon doesn't work

### ISSUE THREAD

**Issue by gafunbird007** [CyberdyneCC/Thermos#296]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
www.mc-baby.in.th/log.txt
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
----
**Explanation of issue:**
this error occurs it console by sending command from rcon to console (commands is by hats mod) 
**How to recreate this issue:**
/hats send <player> <name of hats> from rcon to console 
#It work  fine in game and by direct to console
**Modpack Name:** *(Only if public)*
iChunHat
**Mods Installed:**
iChun hat
**Plugins Installed:**
-
**Warmroast Report:** *(Optional)*

**Thermos Version:**
54
**Forge Version:**
1614

**Comment by Robotia** [comment]
Fixed by @Time6628

**Comment by Proplex** [comment]
Has this bug regressed? I'm getting the same error on build 57 and 58. A look at the commit shows the patch was removed in later builds sometime later.

**Comment by Time6628** [comment]
No, it was never implemented.

**Comment by Proplex** [comment]
What's your idea on how to implement a proper fix? Changing the sender from the RemoteConsoleCommandSender instance to the ConsoleCommandSender instance from Bukkit.getServer().getConsoleSender() fixes sending RCON command, but the RCON client never receives the output of the command (understandably so).

RCON is pretty important to me as a lot of my server stats relies on parsing console commands via RCON.
