### ISSUE TITLE
[BUG] PlayerDeathEvent.setKeepInventory

### ISSUE THREAD

**Issue by ChenGang0415** [CyberdyneCC/Thermos#298]
PlayerDeathEvent.setKeepInventory(true)
i am set KeepInventory true 
but it's still clear all item on respawn and don't drop on ground
please fix it

Thermos Version:
55
Forge Version:
1614

**Comment by Robotia** [comment]
Possible to give GIF/Video?

And nice profile picture!

**Comment by iKaneki-Ken** [comment]
Have tested this myself, could not reproduce.

**Comment by ChenGang0415** [comment]
![1](https://cloud.githubusercontent.com/assets/6367112/14648828/ced811a4-0696-11e6-9d99-977078198c38.gif)

This is my code:

    @EventHandler(priority = EventPriority.HIGHEST)
    public void onKeepInventory(PlayerDeathEvent e){
        e.setKeepInventory(true);
        System.out.println("e.getDrops().size() = " + e.getDrops().size());
        System.out.println("e.getKeepInventory() = " + e.getKeepInventory());
        e.getEntity().getInventory().getHeldItemSlot();
    }

**Comment by Bogdan-G** [comment]
no mods and no plugins installed in server?

**Comment by ChenGang0415** [comment]
I don't have mods and plugins.

**Comment by Time6628** [comment]
Well for starters, that code is defiantly wrong.
You would have to get all the items in the player inventory, then add those items to the player's inventory after they respawn.

**Comment by ChenGang0415** [comment]
I use spigot for this method ,it can keep inventory. 
I only remove drop item.
@Time6628  
You said the way is used before 1.7.10
At that time, PlayerDeathEvent dont have 'keepInventory' Method

**Comment by Time6628** [comment]
Can we see all of your code?

**Comment by Robotia** [comment]
@Time6628 I think it is on our end actually, under the EntityPlayer the keep inventory is checked and the items should be kept but they're not..which is why I'm confused about this.

**Comment by Time6628** [comment]
I will work on this when I can :cat:

**Comment by ChenGang0415** [comment]
good job! thx
