### ISSUE TITLE
Ignore entitytracking and entityactivation on boss mobs.

### ISSUE THREAD

**Issue by Zilacon** [CyberdyneCC/Thermos#301]
As the title states the biggest flaw with spigots entity tracking/activation is it breaks fighting the wither and dragon or any boss that flies around a reasonable distance away from you. Ghasts, Bats, Or even thrown entities such as snowballs and arrows are also effected by this.

Can there be a fix for this?

**Comment by Robotia** [comment]
There isn't really a way to detect what is a boss mob and what isn't, unless you are just referring to vanilla mobs If you don't want the entity activation range to take effect, you'll have to set it to a large number. It is all configurable in the spigot file.

**Comment by Zilacon** [comment]
Setting it to 128 still freezes the dragon in place 64 blocks away. If anything could you add an option to disable the entity tracker and activator? So when its disabled just run vanilla behavior?

**Comment by iKaneki-Ken** [comment]
@Robotia Wouldn't there be a way to make the ignore-entity-tracking and entity-activation on mobs that make use of the boss HP bar?

**Comment by iKaneki-Ken** [comment]
Or better yet, do what mod devs do and make it ignore specific class paths.

**Comment by Robotia** [comment]
Hmm.  Might be able to do something like the tile entity yml file

**Comment by iKaneki-Ken** [comment]
If that is possible, it may fix the issue with Minecarts.

**Comment by Time6628** [comment]
@Zilacon Could you try this build of thermos? https://github.com/WeAreShrubs/Thermos/releases/tag/WRS-Test1
I've added two config options that allow you to change the Wither and Dragon tracking/activation ranges.

**Comment by Zilacon** [comment]
@Time6628 Sounds good, ill check it out when i come home later. Thanks!

**Comment by Zilacon** [comment]
@Time6628 @Robotia Can confirm, problem is fixed with Time's build. Could this be added into the official thermos build?

Thanks time for working on this!

**Comment by Time6628** [comment]
@Zilacon I believe @Robotia is creating a entites.yml which is similar to tileentities.yml, but you can modify the activation and tracking ranges instead the the tile ticks :cat:

**Comment by Robotia** [comment]
^ @Time6628 is correct, but right now it's kinda in RIP state, @iKaneki-Ken has been having issues with it I believe.

**Comment by iKaneki-Ken** [comment]
@Robotia Wait, there's a Entity.yml? If there is in the latest commits, it hasn't generated.

**Comment by Robotia** [comment]
@iKaneki-Ken It should've been made, argh I probably missed something.

**Comment by Zilacon** [comment]
Will this be added to thermos? I dont see it in the recent build.

**Comment by Time6628** [comment]
It is in the recent builds, entities.yml :cat:

**Comment by Zilacon** [comment]
I dont understand how this is similar to setting the spigot.yml. Could you explain please?

**Comment by Robotia** [comment]
Fixed in 56 with `entities.yml`.
