### ISSUE TITLE
[BUG] Ticking Item Entity

### ISSUE THREAD

**Issue by iKaneki-Ken** [CyberdyneCC/Thermos#303]
**Server Log:** Not applicable

**FML Log(s):** Not applicable

**Explanation of issue:** Server can randomly if someone drops an item on the ground.

**How to recreate this issue:** Drop items on the ground, it may or may not crash the server.

**Modpack Name:** Not applicable, happens randomly regardless of the modpack.

**Mods Installed:** Not applicable as it happened without any mods installed.

**Plugins Installed:** Not applicable as it happened without any plugins installed

**Warmroast Report:** *(Optional)*

**Thermos Version:** Unofficial, 5 commits off the lastest commits.

**Forge Version:** 1614

**Crash Report:** http://pastebin.com/jmZL3P3E

**Comment by Bogdan-G** [comment]
strange that no one has responded to this must be added to the list of the loaded entity check.
example: https://github.com/Bogdan-G/FFoKC/blob/master/patches/net/minecraft/world/World.java.patch#L882

**Comment by Robotia** [comment]
We talked on Discord a bit, there are problems that must be solved before 56 is released, and this is one of them :(

**Comment by Robotia** [comment]
Fixed in 56.
