### ISSUE TITLE
Sever deadlock on player join

### ISSUE THREAD

**Issue by wormzjl** [CyberdyneCC/Thermos#304]
The full log can be found here
https://gist.githubusercontent.com/wormzjl/c04038f2554c006e771b327734eb5c68/raw/a53fefb75dc9aba1b0ff500a8268a0f0a744fd38/gistfile1.txt

Seems that pressured pipe is the source of problem, but we haven't got such issues before while using kcauldron 152

**Comment by Time6628** [comment]
What is your timeout-time in spigot.yml?

**Comment by wormzjl** [comment]
90 as default

**Comment by Time6628** [comment]
Set it to 900 or more.

**Comment by Robotia** [comment]
Caused by mod behavior. The timeout simply *shows the issue source*, it does not cause it.
