### ISSUE TITLE
Server player list on hover broken

### ISSUE THREAD

**Issue by ChrisLane** [CyberdyneCC/Thermos#310]
**Explanation of issue:**
In the Minecraft client, hovering over a server's player count (e.g. 20/80) should list players on the server. Hovering over the player count does not do anything with MCPC-Plus, KCauldron or Thermos.

This occurs with a vanilla Thermos server.

**Thermos Version:**
Thermos Build 53

**Forge Version:**
1.7.10-1448

**Server Files**
server.properties: http://paste2.org/vO40tWVV

**Comment by Time6628** [comment]
Can you post your server.properties?

**Comment by Bogdan-G** [comment]
`(e.g. 20/80)` - random ~10 players view

**Comment by ChrisLane** [comment]
server.properties file: http://paste2.org/vO40tWVV

**Comment by Robotia** [comment]
Does your spigot.yml contain these lines?
`settings:
  late-bind: false
  sample-count: 12
  timeout-time: 90
  restart-on-crash: false
  restart-script: ./server.sh
  netty-threads: 3
  fullMatchRate: 10
  bungeecord: false
  player-shuffle: 0
  user-cache-size: 102400
`

**Comment by ChrisLane** [comment]
All but "user-cache-size: 102400".

**Comment by ChrisLane** [comment]
Seems to be fixed in build 58.
