### ISSUE TITLE
 SkinsRestorer

### ISSUE THREAD

**Issue by evernife** [CyberdyneCC/Thermos#311]
Is there a way to fix SkinsRestorer to work on Thermos?

https://www.spigotmc.org/resources/skinsrestorer.2124/

(Just to point here too :D )

http://gogs.tcpr.ca/TCPR/Fixes/issues/1

**Comment by Robotia** [comment]
What is wrong with it? You erased the default template and did not specify :confused:

**Comment by Time6628** [comment]
If you setup BungeeCord correctly you should have no need for SkinsRestorer.

**Comment by evernife** [comment]
Sorry for the non-detail.

The plugin just dont work.

I talked to the plugin author and he said that the problem is with cauldron/thermos, and he will only suport spigot/bukkit problems... so....

i am here asking you to fix this compatible problem, if you could of course :D 

I will try the bungeecord as the friend says too :D

**Comment by evernife** [comment]
Ok, bungeecord sems not to be what i am looking for, too much complicated, and i dont have multiple servers, just a single one '-'

Nor even minigames

**Comment by DarkBlade177** [comment]
Ops, same problem here, just wandering if this plugin can be fixed, my players keep askying me why my server dont have skins '-'

**Comment by ArcasCZ** [comment]
Did anyone tested SkinsRestorer @ 10.4.4? On my KCauldron server it works.

**Comment by ArcasCZ** [comment]
SkinsRestorer v. 10.4.4 is working - https://ctrlv.cz/shots/2016/04/21/0e2B.png

**Comment by evernife** [comment]
: (

**Comment by Robotia** [comment]
Because it was noted to be working, the issue was closed

**Comment by evernife** [comment]
Hmm, just to say, 

> SkinsRestorer v. 10.4.4

  Is too laged, it cant be used at all...

When i have about 20 players online, TPS drops to 13-15 ..

But Ty : C

**Comment by Robotia** [comment]
If you give a WarmRoast profile of your server during the lag I will try to fix it.

**Comment by evernife** [comment]
This warm host ? **[Link](https://bukkit.org/threads/warmroast-a-jvm-cpu-sampling-tool-to-figure-out-why-a-mc-server-lags.153336/)**

How to use is in a MultiMC server ? 

:/

**Comment by Time6628** [comment]
https://github.com/Robotia/WarmRoastSetup
