### ISSUE TITLE
World edit minor issues potential to fix from thermos?

### ISSUE THREAD

**Issue by djoveryde** [CyberdyneCC/Thermos#312]
As it seems world edit hasn't really had any new releases in a while I am going to note a couple of issues that I don't know wether they can be fixed through thermos.

1: Seems something in world edit doesn't like the version of thermos/cauldron and refuses to save sign data when saving schematics or moving buildings.

2: As we know world edit can pretty much crash the server if your loading in large schematics. Is it possible wether thermos could "build" that schematic. I saw something similar with the civilisation mod where it builds the schematic over time adding layer by layer chunk by chunk to prevent any taxation on the server.

3: On occasions if I do a //regen or anything with world edit it will sometimes roll back a previous regen wether it be from days ago or 4 regens ago. Tried /save-all and server restart which never seemed to physically lock the regen/edit in permanently.

**Comment by Robotia** [comment]
1. Have you tested this on PaperSpigot 1.7.10 as well?
2. This must be done by WorldEdit...not Thermos. The code of WE must be edited so that it saves asynchronously.
3. I have that issue too, but I'm not sure if it's due to the fact that I'm using AsyncWorldEdit or that it's on Thermos. Are you using AsyncWorldEdit, and have you tried this on PaperSpigot 1.7.10?

**Comment by djoveryde** [comment]
Haven't used ASyncWorldEdit and not tried on paperspigot 1.7.10 however when the server starts up it throws the following message. This has been the same since cauldron I believe.

19.04 16:30:17 [Server] INFO Enabling WorldEdit v6.1;no_git_id
19.04 16:30:17 [Server] INFO WEPIF: Using the Bukkit Permissions API.
19.04 16:30:17 [Server] INFO **********************************************
19.04 16:30:17 [Server] INFO ** This WorldEdit version does not fully support your version of Bukkit.
19.04 16:30:17 [Server] INFO **
19.04 16:30:17 [Server] INFO ** When working with blocks or undoing, chests will be empty, signs
19.04 16:30:17 [Server] INFO ** will be blank, and so on. There will be no support for entity
19.04 16:30:17 [Server] INFO ** and biome-related functions.
19.04 16:30:17 [Server] INFO **
19.04 16:30:17 [Server] INFO ** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
19.04 16:30:17 [Server] INFO **********************************************

**Comment by Bogdan-G** [comment]
@djoveryde what's the difference what he says? the main thing that worked!

**Comment by Time6628** [comment]
Install worldedit forge and worldedit bukkit. WorldEdit forge does all block editing and keeps all data of the blocks including chests,signs, even Thermal Expansion machines. Bukkit worldedit takes over all the commands and permissions. :cat:
