### ISSUE TITLE
Modded Block Protection on Factions

### ISSUE THREAD

**Issue by CzEMC** [CyberdyneCC/Thermos#318]
No protection on factions items.

I have tried using mostly every version supported by Thermos' spigot version, and I have no luck with adding blocks like the iron chest, (From the mod, IronChest. [BlockID: 691:0, IronChest:BlockIronChest])

SERVER_BASE/mstore/factions_mconf/instance.json:

  "materialsContainer": [
    "DISPENSER",
    "CHEST",
    "FURNACE",
    "BURNING_FURNACE",
    "JUKEBOX",
    "BREWING_STAND",
    "ENCHANTMENT_TABLE",
    "ANVIL",
    "BEACON",
    "TRAPPED_CHEST",
    "HOPPER",
    "DROPPER",
    "BlockIronChest" ##I have also changed this to: "691", "691:0", "IronChest:BlockIronChest", and "IronChest")
  ],

Is there anyway to add a Modded Block to the protection? or is that not possible?

 Thanks

- CzE

Using Thermos Build 56

**Comment by Robotia** [comment]
Fixed versions are available here: http://gogs.tcpr.ca/TCPR/Fixes

**Comment by Time6628** [comment]
Try IRONCHEST_BLOCKIRONCHEST

**Comment by CzEMC** [comment]
> Fixed versions are available here: http://gogs.tcpr.ca/TCPR/Fixes - Robotia
I am using those versions. (MCore+Factions 2.8.5 from that page)

> Try IRONCHEST_BLOCKIRONCHEST - Time6628
Thanks, that fixed the problem. I'm guessing that its MOD_BLOCK (I can know full block names from Waila)

**Comment by CzEMC** [comment]
Oh, forgot about this:

The fixed versions seem to block every interaction with the terrain. Is there anyway that the OpenBlocks grave can be whitelisted from the protection? (Like anyone can break openblocks graves?)

**Comment by Eufranio** [comment]
Try right click with an shovel in the grave.

**Comment by Robotia** [comment]
I am sorry but it is no longer being supported. That fixed version was supposed to universalize protection, but I am not sure how to allow graves and I no longer have access to the code I wrote for it.
