### ISSUE TITLE
Some players get "Internet server error"

### ISSUE THREAD

**Issue by DigitalSniperz** [CyberdyneCC/Thermos#321]
**Server Log:** http://pastebin.com/pTfmkKbR

**FML Log(s):** http://pastebin.com/pTfmkKbR

**Explanation of issue:** some players are getting kicked on join "internal server error"

**How to recreate this issue:** Not sure

**Modpack Name:** CrundeeCraft (ATLauncher)

**Mods Installed:** https://www.atlauncher.com/pack/CrundeeCraft

**Plugins Installed:** AsyncWorldEditInjector, CoreProtect, MongoAPI, WorldEdit, Essentials, ClearLag, ChatControl, Buycraft, WorldBorder, SkQuery, Votifier, VoteParty, WorldGuard, ProtocolLib, AsyncWorldEdit, ExecuteEverywhere, EssentialsChat, GlobalMarket, PermissionsEx, DigiBot, Lottery, Vault, EssentialsSpawn, DigiFix, ItemRestrict, DigiCrundee, GriefPreventionPlus, Jobs, CrateReloaded, DigiPerks

**Thermos Version:** Thermos 1.7.10-1614.46

**Forge Version:** 1614.46

**Comment by Time6628** [comment]
DivineRPG issue, not thermos.

**Comment by Robotia** [comment]
`    at mca.core.forge.EventHooksFML.playerLoggedInEventHandler(EventHooksFML.java:85) ~[EventHooksFML.class:?]`
Whatever MCA core is 0.o

**Comment by bookerthegeek** [comment]
Minecraft comes alive

I think.

**Comment by Robotia** [comment]
Not caused by Thermos as @Time6628 noted.
