### ISSUE TITLE
Client Crashes upon login 

### ISSUE THREAD

**Issue by CobaltSparkz** [CyberdyneCC/Thermos#328]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

http://pastebin.com/ec1KBDaB

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

http://pastebin.com/ec1KBDaB

**Explanation of issue:**

Player logs in on various packs across the network, instantly disconnected and crashes client

**How to recreate this issue:**

Logging into server

**Modpack Name:** *(Only if public)*

Revenge of the C-Team, Resonant Rise 3: Mainline, Revolution2, CrundeeCraft

**Mods Installed:**

Default Pack mods.

**Plugins Installed:**

http://pastebin.com/Q7MivUFV

**Warmroast Report:** *(Optional)*

**Thermos Version:**

Various, 1448-56 Crundee, 1614-56 for others

**Forge Version:**

1448 for Crundee, 1614 for Others

Please note, this issue only occurred after updating the network from KCauldron to Thermos

**Comment by DraksterAU** [comment]
What is providing the world and/or teleporting the player on login?
That error is typically experienced when transporting a player using forge methods to a bukkit provided world.

Eg. I used to have a problem when a player logged in in my 2nd world, but if they logged in in my first then travelled to the second it was fine.

**Comment by CobaltSparkz** [comment]
Currently, this can occur even when playerdata has been deleted. Players have logged out of different worlds, only to crash when logging back in again - Such as Mainline, the player logged out of the overworld, logged back in and crashed. I delete their playerdata, which means they would spawn in a flatworld I made specifically to house the spawn for the server, and they still crashed.

I use MultiVerse and have also tested MultiWorld, to the same effect. There are no such worlds that co-incide with the Dimension numbers stated =(

**Comment by CobaltSparkz** [comment]
I have just had the issue myself on my CrundeeCraft pack - The error is caused by DImension3 - There is a DIM3 folder, however, inside it, it only contains a SecretRooms-ownership.dat file. If I go to the level.dat on my Spawn flat world, the Dimension number there is also 3.

**Comment by DraksterAU** [comment]
This is by no means a fix, but you could try build 46.
It's what my server runs and has no issues with any world providers and uses a combo of forge and Bukkit world generators.

There were some changes in a later builds that may have broken things in some circumstances.
 They even attempted a fix for travelling to Bukkit worlds with forge modded items / mechanics that throws this exact error.

**Comment by CobaltSparkz** [comment]
Thanks for the input Drak :)
