### ISSUE TITLE
Error with ModularPowersuits-0.11.0.284

### ISSUE THREAD

**Issue by Evinsta** [CyberdyneCC/Thermos#329]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/dFNg61HW

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:**
When  connected to server and you have a piece of the modular power suit it cashes the client (**this doesn't happen in single player**)

**How to recreate this issue:**
grab any piece of the armor and hold the item in your hand ( it will kick you out of the game with the message:
Connection Lost
Internal server error

**Modpack Name:** *(Only if public)*
ATR Evolved (on technic launcher)

**Mods Installed:**
1.7.10_AM2-1.4.0.009.jar
ae2stuff-0.5.0.57-mc1.7.10.jar
AgriCraft-1.7.10-1.5.0.jar
AM2PlantFix-1.0.jar
ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar
AnimationAPI-1.7.10-1.2.4.jar
AOBD-2.8.4.jar
appliedenergistics2-rv2-stable-10.jar
bdlib-1.9.4.109-mc1.7.10.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
BigReactors-0.4.3A.jar
BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar
BloodMagic-1.7.10-1.3.3-17.jar
Botania r1.8-249.jar
Chisel2-2.5.1.44.jar
ChiselTones-1.7.10-1.0-3.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.2-325.jar
ComputerCraft1.75.jar
Decocraft-2.2.1_1.7.10.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
EnderCore-1.7.10-0.2.0.31_beta.jar
EnderIO-1.7.10-2.3.0.424_beta.jar
EnderStorage-1.7.10-1.4.7.38-universal.jar
ExtraCells-1.7.10-2.3.9b188.jar
ExtraTiC-1.7.10-1.4.5.jar
extrautilities-1.2.12.jar
FastLeafDecay-1.7.10-1.3.jar
Forbidden Magic-1.7.10-0.573.jar
ic2
IguanaTinkerTweaks-1.7.10-2.1.5.jar
ImmersiveEngineering-0.7.3.jar
immersiveintegration-0.6.8.jar
industrialcraft-2-2.2.820-experimental.jar
InventoryTweaks-1.59-dev-156.jar
magicalcrops-4.0.0_PUBLIC_BETA_3.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-8.1.9.265.jar
MekanismGenerators-1.7.10-8.1.9.265.jar
MekanismTools-1.7.10-8.1.9.265.jar
ModularPowersuits-0.11.0.284.jar
MrCrayfishFurnitureModv3.4.8(1.7.10).jar
neiaddons-1.12.14.40-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.0.jar
NetherOres-[1.7.10]2.3.1-22.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
Numina-0.4.0.131.jar
OpenBlocks-1.7.10-1.5.1.jar
OpenModsLib-1.7.10-0.9.1.jar
OpenModularTurrets-1.7.10-2.1.9-211.jar
OreDictionaryConverter-1.6.1.jar
orespawn-1.7.10-20.3.zip
Pam's HarvestCraft 1.7.10Lb.jar
roguelike-1.7.10-1.4.4.jar
secretroomsmod-1.7.10-4.7.1.413.jar
SimplyJetpacks-MC1.7.10-1.5.3.jar
SolarExpansion-Basic-1.6a.jar
StevesAddons-1.7.10-0.10.16.jar
StevesFactoryManagerA93.jar
StorageDrawers-1.7.10-1.9.4.jar
switchescontinued-0.0.1.jar
TConstruct-1.7.10-1.8.8.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumicenergistics-0.8.10.10.jar
ThaumicTinkerer-2.5-1.7.10-493.jar
TMechworks-1.7.10-0.2.14.100.jar
VeinMiner-1.7.10_0.30.2.unknown.jar
Waila-1.5.10_1.7.10.jar
Wawla-1.3.3-1.7.10.jar
Ztones-1.7.10-2.2.1.jar

**Plugins Installed:**
28.04 09:14:24 [Server] INFO Plugins (18): WorldEdit, Essentials, EssentialsProtect, GroupManager, EssentialsChat, EssentialsAntiBuild, BanItem, ClearLag, ScheduledAnnouncer2, WorldBorder, HolographicDisplays, Vault, Votifier, EssentialsSpawn, GriefPrevention, WorldGuard, EnjinMinecraftPlugin, RandomTP

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-1.7.10-1614-56-server.jar

**Forge Version:**
1614

**Comment by Robotia** [comment]
Explanation for the issue: @Evinsta installed a client-side mod on the server by accident.
