### ISSUE TITLE
No crashreports when the game crash 

### ISSUE THREAD

**Issue by vrackfall** [CyberdyneCC/Thermos#330]
Hi,
I was missing a mod on my THermos server (lastest version), and no crashreports was displayed when the game crash.
So it's was just to inform you about this bug.
Please fix it.
Thanks

**Comment by Robotia** [comment]
This is not a bug, look in `latest.log` and you will see what caused the server to not start up.

A crash is defined as: a failure in the Minecraft server during runtime. The server has tried to tick at least once.
This is a start up error. A start up error occurs when the server has not had a chance to tick and is found in logs/latest.log.

**Comment by vrackfall** [comment]
Sorry for I didn't say it,
The thing is when the game is crashing on the 53 build, there is a crashreport (it said what is the imssing mod) but no in the build 56.
