### ISSUE TITLE
Bukkit plugins cannot check for Material is Forge block

### ISSUE THREAD

**Issue by DraksterAU** [CyberdyneCC/Thermos#332]
Hi There,

I'm trying to create a compatibility addon for Factions that focus around detection of modded blocks and performing extra validation on them.

I'd really like to only be targeting this validation at modded blocks.

I've just checked, and there seems to be no way to call the private isForgeBlock field in Material.java.patch

is it possible this could be exposed in a future build, so a plugin designed for Thermos can check if a block is actually a forge block?

Regards,
DraksterAU

**Comment by Time6628** [comment]
https://github.com/CyberdyneCC/Thermos/blob/master/patches/org/bukkit/Material.java.patch#L63

**Comment by DraksterAU** [comment]
That covers all Vanilla blocks too, @Time6628

**Comment by Time6628** [comment]
Yes, but that returns if the block id is more than the vanilla ids go or if it is a forge block.

**Comment by DraksterAU** [comment]
That's a LT symbol haha :P

**Comment by Time6628** [comment]
Still works though...

**Comment by DraksterAU** [comment]
I don't think you understand this request.

**Comment by Time6628** [comment]
Just check if isBlock() returns false...

**Comment by DraksterAU** [comment]
IsBlock is false when the item is not a vanilla block or a forge block.

It is true when the block is vanilla or forge.

No way to check for just forge.

**Comment by Time6628** [comment]
My bad, I will fix :cat:

**Comment by Time6628** [comment]
Completed https://github.com/CyberdyneCC/Thermos/commit/57e1478df635e4dc5c85548be90c71d94fbba490.

**Comment by DraksterAU** [comment]
Thanks @time6628 .... Much appreciated :)

Sorry for the Confusion!
