### ISSUE TITLE
Error Regarding ChatControl

### ISSUE THREAD

**Issue by BungeeTheCookie** [CyberdyneCC/Thermos#337]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/vG35z4F8
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:** I installed ChatControl and Protocol Lib (Cauldron) on my server, and when I join it spams this error in the console. I know this is due to a feature called "Deseralize JSON" in the config, but this error doesn't occur on kCauldron and was wondering if there was a fix for this.

**How to recreate this issue:** Download ProtocolLib (Cauldron) and ChatControl on a Thermos install.

**Modpack Name:** *(Only if public)*

**Mods Installed:** none

**Plugins Installed:** Essentials, ChatControl, ProtocolLib 

**Warmroast Report:** *(Optional)*

**Thermos Version:** 55

**Forge Version:** 1614

**Comment by Time6628** [comment]
Try 56.

**Comment by BungeeTheCookie** [comment]
Isn't that a bleeding build though?

**Comment by BungeeTheCookie** [comment]
Fixed!
