### ISSUE TITLE
Firing an IC2 Mining Laser cannot be tracked in Bukkit

### ISSUE THREAD

**Issue by DraksterAU** [CyberdyneCC/Thermos#338]
This is a long standing bug that has this item banned on most servers.

The reason this occurs is because the mining laser projectile does not throw a 'ProjectileHitEvent' or ProjectileLaunchEvent in bukkit.

Is there an issue with the mapping of the Forge equivalent?

If there is a way that I am unaware of, please let me know.

My goal here: To stop the item from bypassing faction permissions by calculating the shooters rights to build at the point of impact.

EDIT: This is really weird, IC2 Mining Lasers throw their own events for everything.
I'm not sure you can help here?

**Comment by Robotia** [comment]
@DraksterAU I am aware of this, I talked with the developer but he refused to add events that align with Forge (weirdly enough). The only real way to solve the problem would be to either convert the code to match Forge events or make an add-on mod. :confused:  Sorry.

**Comment by spannerman79** [comment]
Damn it ninja'ed by @Robotia :stuck_out_tongue: 

I was about to state that the forge dev for IC2 needs to enforce either a fakeplayer on blockplace/blockbreak or reflect the UUID of the user who owns the TE - in this case the Mining Laser.

And for the record this isn't an issue with Cauldron/kCauldron/Thermos - this happens even while using ForgeEssentials on a vanilla forge server - so go figure. And yes I know as I run a vanilla forge server with ForgeEssentials for kids with learning issues.  I removed IC2 as the dev/s shows their unwillingness to not just add in normal forge events but they blame everything and everyone else.

**Comment by DraksterAU** [comment]
@Robotia  No worries at all.

**Forge events or make an add-on mod**

If I do that, will Thermos pass the events to bukkit?

**Comment by DraksterAU** [comment]
Working on Quarry & Digiminer support.
Plan is to make it so a miner placed in faction can mine that factions land and wilderness only.
A Miner placed in wilderness can mine in wildernesss only.

**Comment by spannerman79** [comment]
> Digiminer support

If your talking about the Digital Miner from Mekanism there already is a fake player for that. `[Mekanism]` - I can't remember the UUID but check your logs as it adds a log event stating the UUID.

**Comment by DraksterAU** [comment]
@spannerman79 I know....thanks lol.
 I'm working on it :P

Having an issue with the fakeplayer reporting the location of the broken block for its location, not the miner/quarry..... any ideas? @Robotia @spannerman79

**Comment by spannerman79** [comment]
While using Prism it logs and reports the activity of the fakeplayer and with GPP it correctly blocks or allows the blockbreak/blockplace forge event.  I know that's not much help as you want factions support but it will give you a location to start at/peak at code wise.

/personalrant

I've always disliked factions.  they use a third party api which serves no real purpose that in my view just makes them lazy. Not to mention their configs.... 

/endpersonalrant

**Comment by DraksterAU** [comment]
@spannerman79 I admit, they're not the most pleasant people (aka. Assholes?) (they've been offered t he 1 line of code required to support cauldron officially and declined it citing it was bad coding).

But they also use a plugin that actually has some "sense" of realism to it. Not a golden shovel tool.

**Comment by spannerman79** [comment]
You can use whatever item you like in the configs. golden shovel is default. same with the stick or the newbie option of setting a claim by placing down a chest.

**Comment by DraksterAU** [comment]
@spannerman79 Does GP support alliances? War? etc?
Not having a go at it, I'm just trying to theme my server to a bit of RP and "Factions" suites (So would nations/empires whatever you call it).... but It would need to involve relations.
http://stargatemc.com - my little project haha :)

**Comment by spannerman79** [comment]
No - its more towards PvE not PvP.

As for PvP there isn't much choice - Factions is the only real plugin that can offer a war type setting..

You *could* do PvP with GPP but it will require the use of other plugins and mods and quite a bit of setting up using CustomNPC's to set the player faction type/group. Screwed if you do screwed if you don't LOL

**Comment by DraksterAU** [comment]
@spannerman79 Towny and other similar plugins also do it.

Yep, really are.

I learned some Java and have developed several little plugins to handle the 'fuck you' that I've been given when asking from help... QQ haha

**Comment by Razorskills** [comment]
Here is a mod I used to use for the mining laser. But lots has changed with it. maybe op would be willing to let you update it. http://forum.industrial-craft.net/index.php?page=Thread&threadID=10527

**Comment by iKaneki-Ken** [comment]
I've already fixed and patched this myself.

**Comment by DraksterAU** [comment]
Do share?

**Comment by iKaneki-Ken** [comment]
http://dev.bukkit.org/bukkit-plugins/otherdrops/files/59-2-8b-596/ - Download that.

`- trigger: Right_Click
          tool: Mekanism_FlameThrower
          consumetool: 1
          command: ['/!$ cofh killall Mekanism.Flame','/!$ give %p Mekanism_FlameThrower:100 1']
          message: '&a[&3!&a] &3Sorry, &fFlamethrowers &3can''t be used in the main world due to griefing issues.'
          world: ap_world
          delay: 3`

**Comment by DraksterAU** [comment]
Eh, that's not the mining laser.

**Comment by Time6628** [comment]
Normal GriefPrevention does have a Seige feature which is more geared towards pvp, however this is removed in GPP.

**Comment by DraksterAU** [comment]
This is not relavent to the mining laser at all?

**Comment by Time6628** [comment]
Was adding to the chat earlier about GP supporting PvP :P http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/pvp-protection-and-optional-siege-pvp-mode/

**Comment by Robotia** [comment]
Are you using IC2Classic or IC2 Experimental?

**Comment by DraksterAU** [comment]
IC2 Experimental - Classic died years ago no?

**Comment by Robotia** [comment]
Nope, https://github.com/TinyModularThings/IC2Classic

**Comment by DraksterAU** [comment]
To your knowledge is it compatible with the experimental Api?
99% of mods use experimental for integration and might break

**Comment by Robotia** [comment]
Well I know the author tries to keep it integrated but I wouldn't suggest just switching to it, a lot of the items are different.

**Comment by DraksterAU** [comment]
haha fair enough :)

**Comment by iKaneki-Ken** [comment]
`Eh, that's not the mining laser.
It also only prevents use of the item, I am trying to allow use of the item & not have it grief.

PS: Check out ItemRestrict. Such a cool tool for what you're doing. Simple too.`

![faceplam. . .](http://memesvault.com/wp-content/uploads/Facepalm-Meme-04.png)
