### ISSUE TITLE
Fakeplayer locations being reported incorrectly

### ISSUE THREAD

**Issue by DraksterAU** [CyberdyneCC/Thermos#339]
Hi Guys,

I've noticed that any time a fakeplayer registers itself for a block break, place or damage event, it is located at the block that is being modified.

This occurs for both BuildCraft quarries & Mekanism Digital Miners.

Any chance we can have it be the location of the device instead? That way we can do some validation on it for Grief protection (The relation between the two locations)

The Location of the block is (obviously) stored in the block, so theres no point in having it there twice.

PS: I've posted on both the BC and Mek githubs for this, incase it just happens to be something they did.

Regards,
DraksterAU

**Comment by Robotia** [comment]
This is on purpose. The fake player is intended to have a location of 0,0,0 in some magical place.

This is a guideline set forth by Forge, I don't think this can be changed realistically

**Comment by DraksterAU** [comment]
It would be up to the mods to report differernt fakeplayers for different miners I guess then.
Bah :(

**Comment by DraksterAU** [comment]
@Robotia Closest thing to a workaround I could find:

1. Create a custom flag for turning miners on/off in a players land, allow them to modify it for their faction.
2. Allow miners to break blocks in unclaimed land regardless (Factions only allows you to allow them to build anywhere, including other peoples factions... stupid).

This allows people to place them on the edge of claimed land to keep them safe and to have the miner 'do its business' in the wilderness.
