### ISSUE TITLE
Bukkit CreatureSpawnEvent does not fire at all

### ISSUE THREAD

**Issue by DraksterAU** [CyberdyneCC/Thermos#342]
Hi All,

I'm currently trying to debug why its impossible to prevent mobs spawning in any area (specifically via the factions plugin).

It looks like CreatureSpawnEvent in Bukkit does not fire on Thermos, which on a vanilla spigot/bukkit server would fire allowing plugins to block spawns of entities in certain areas.

This is the bukkit equivalent of the LivingSpawnEvent in forge, but only covers non-players.

Can You please look into this?

if there is a way around this, let me know.

The sample code I am using is:

> @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = false)
>     public void creatureSpawn(CreatureSpawnEvent event) {
>         PerimeterPlugin.throwMessage("info", "Entity Spawn: " + event.getEntity().getType().toString() + " at: " + event.getLocation());
>     }

**Comment by Time6628** [comment]
It does throw...
```SKELETON
SKELETON
SKELETON
MAGMA_CUBE
MAGMA_CUBE
MAGMA_CUBE
MAGMA_CUBE
MAGMA_CUBE
MAGMA_CUBE
BAT
BAT
BAT
BAT
GALACTICRAFTCORE_ALIENVILLAGER
GALACTICRAFTCORE_ALIENVILLAGER
GALACTICRAFTCORE_ALIENVILLAGER
GALACTICRAFTCORE_ALIENVILLAGER
```
Code:
```
    @EventHandler
    public void onSpawn(CreatureSpawnEvent e) {
        TestPlugin.log.log(Level.INFO, e.getEntity().getType().toString());
    }
```

**Comment by DraksterAU** [comment]
@Time6628 I'm testing without the priority / cancelled detection now.. Its the only difference between the two haha

If that works, then back to the drawing board :(

**Comment by Time6628** [comment]
Btw, Factions already has flags to prevent mobs from spawning in faction territories. 
https://www.massivecraft.com/factions#flags

**Comment by DraksterAU** [comment]
@Time6628 They do not work..

**Comment by DraksterAU** [comment]
@Time6628 How is that firing? 

I'm seeing nothing with the below... even though the same plugin fires dozens of other events for me.

    @EventHandler
    public void creatureSpawn(CreatureSpawnEvent event) {
        PerimeterPlugin.throwMessage("info", "Entity Spawn: " + event.getEntity().getType().toString() + " at: " + event.getLocation());
    }

**Comment by DraksterAU** [comment]
@Time6628 I am a god damn idiot. I commented out my throwMessage function. Sorry man.

**Comment by DraksterAU** [comment]
@Time6628 

Figured it out now after my idiot mistake.

Mobs no longer spawn if flag is disabled (I just re-checked their spawn event at HIGHEST instead of factions NORMAL priority)

I also put custom checks in for slimes to prevent them spawning in claimed land.

https://www.spigotmc.org/resources/perimeter.22469/updates
