### ISSUE TITLE
[Bug] Item Duplication with Inventory Tweaks.

### ISSUE THREAD

**Issue by CzEMC** [CyberdyneCC/Thermos#345]
**Explanation of issue:** You can duplicate Items from protected inventories (Like a GUI Shop) by sorting the said inventory and causing Inventory Tweaks to give the item to the player. This is brought to thermos because other mods don't add GUI's that 

**How to recreate this issue:** Simply contentiously sort the protected GUI, Item that you receive is random, however, is one from the protected inventory.

**Modpack Name:** *(Only if public)* Land of Potentia (On the Technic Launcher)

**Mods Affected:** Inventory Tweaks

**Plugins Affected:** ShopGUIPlus

**Thermos Version:** Latest Bleeding, 56.

**Possible Solution:** Custom build of Inventory Tweaks that checks if the inventory has the cancel item move event and then sort the inventory (Players inventory and Chest Inventory)

**Comment by spannerman79** [comment]
Remove Inventory Tweaks from server

**Comment by CzEMC** [comment]
That was a solution our staff team had, but Inventory Tweaks is one of our most loved plugins.

**Comment by Time6628** [comment]
InventoryTweaks is a client side mod. Having it on the server is not needed.

**Comment by spannerman79** [comment]
It is not required server side.  Inventory Tweaks is a mod that can be run stand alone on client. It will still operate and work correctly without the issues of item dupes.

**Comment by CzEMC** [comment]
Thanks for the reply, the problem is solved.
