### ISSUE TITLE
Question - where is the Hash-backed ArrayList commit?

### ISSUE THREAD

**Issue by Slind14** [CyberdyneCC/Thermos#346]
Hey,
seeing the changelog of 56 bleeding I have some performance concerns from trying something similar in the past. But looking through to the commits I can't seem to find it. The "Transition to Hash-backed ArrayList data structure for all tile entity collection, should see a significant performance improvement".

https://github.com/CyberdyneCC/Thermos/compare/56...master

Mind pointing me at the commit?

**Comment by Robotia** [comment]
You are looking at the wrong set of commits. The 56...master is what changes occurred after 56 was released.

If you are looking for the changes made in 56 they are here: https://github.com/CyberdyneCC/Thermos/compare/55...56

**Comment by Slind14** [comment]
ohh, sorry, thanks.
We have a similar approach in production for +1 year now. Benchmarking showed that this has benefits with a list size of 8k on. Therefor we have it configurable and only turn it on, on the busy servers. As your patch is nearly identical I assume you will experience the same and it might be worth making it configurable, too.

On a side note: You will probably need to be careful, as the way you are removing entries corrupts the order of the list entries, that might cause major issues depending on the use of the list.

**Comment by Robotia** [comment]
Hi Slind, we would appreciate it if you would share optimization changes you make to Thermos with everyone here with a pull request. Since this is an open source project, its continuation depends on developers donating their time to improve it.

Thanks,

Robotia

**Comment by Slind14** [comment]
Sorry, we are using cauldron and this is implemented via. runtime patching.
