### ISSUE TITLE
"fake" players cannot mine blocks (i.e Quarry and Digital Miner)

### ISSUE THREAD

**Issue by VenomFrog** [CyberdyneCC/Thermos#354]
**Server Log:** *(https://www.dropbox.com/s/3pwzfq6at5mlatd/latest.log?dl=0)*

**FML Log(s):** *(https://www.dropbox.com/s/osri6htzfl183ax/fml-server-latest.log?dl=0)*

**Explanation of issue: Any fake player, cannot mine blocks. However, normal players on default groups can do so just fine.**

**How to recreate this issue: Build a BC Quarry or Digital Miner, and it will successfully count the blocks/build the frame, but it will not pick up blocks. Many other forums point to (k)Cauldron so im a bit lost and confused.**

**Modpack: VenomKraft**

**Mods Installed: https://gyazo.com/c4706179743939835541c6fd055e4526 (server has client mods removed)**

**Plugins Installed: https://gyazo.com/514525e2f11af36fe359c1cb213d3c8a Permissionsex shouldnt be an issue, I've used it in the past just fine with these mods.**

**Thermos Version: Thermos-1.7.10-1614-56-server.jar**

**Forge Version: Thermos-1.7.10-1614-56-server.jar**

**Comment by spannerman79** [comment]
This is not a thermos issue but an issue on your end.
The fake player needs to have the correct permission - obviously - just like any other normal player.

**Comment by VenomFrog** [comment]
Confirmed. After looking for hours, i found the issue in AcceptRules which disabled building before accepting the rules. Apologies for filling the issues with an unrelated issue, I hope it helps someone in the future
