### ISSUE TITLE
Mod interfering with Plugin world generation

### ISSUE THREAD

**Issue by Tencao** [CyberdyneCC/Thermos#357]
I've tested multiple world generators, including uSkyBlock, VoidWorld, and CleanroomGenerator, all with the intended purpose of creating an empty world, however it seems Thermos overrides this regardless, and generates the world as normal. Is there anychance someone can look into this issue and try to fix it?

**Comment by Time6628** [comment]
No logs, no help.

**Comment by spannerman79** [comment]
It is not Thermos that overrides - its the forge component that overrides.

On a clean thermos server without mods using any other world gen plugin it works as intended. If you are using any forge based world gen - which you never tested or stated @Tencao - it will override anything that bukkit component tries to restrict.

If you want to limit or control world gen you need to look at forge based alternatives.

**Comment by Tencao** [comment]
I cant provide logs when there's no log output @Time6628 
@spannerman79 Outside of mods like buildcraft, I'm not using any mod based world gen. Plugin based world gen use to work perfectly fine back when I was using KCauldron, it was only recently when I tried it again on Thermos that I ran into this issue. I'm looking into if this only affects the overworld, as well as any mods that could be interfering.

**Comment by Tencao** [comment]
Ok, so after doing some more testing, it seems like this is mostly an issue with the overworld, the nether seems to accept custom generators fine. I've deleted any mod that altered world gen outside ore spawning, and even removed mods like fastcraft, the issue is still present.

**Comment by iKaneki-Ken** [comment]
@Tencao Take a look at the Cauldron.yml. You'll be pleasantly surprised. Bukkit also has a toggleable Debug option as well. So yes, there is ways to get logs on what the software is trying to do, or errors that may pop up.

**Comment by Tencao** [comment]
@iKaneki-Ken Thank you for that, I'll enable log output and paste anything that seems relevant to the issue.

**Comment by Tencao** [comment]
Ok, after using the logs and alot of testing and swapping, I've isolated the mod causing the issue to be TooMuchTime, but to my knowledge, all TooMuchTime does is alter game time, it has nothing to do with world generation. Is it possible altering the game time could be breaking the world gen?

**Comment by Time6628** [comment]
TooMuchTime overrides the way the overworld is generated. Not a Thermos issue. https://github.com/dmillerw/TooMuchTime/blob/master/src/main/java/dmillerw/time/world/WorldProviderOverworld.java#L13
