### ISSUE TITLE
ID problem with Thermos (?) and ZZZZZ Custom Configs mod

### ISSUE THREAD

**Issue by Kruxy** [CyberdyneCC/Thermos#360]
**Mods Installed:**
CodeChicken Core
EtFuturum
Gany's Surface
MalisisCore
MalisisDoors
Not Enough Items
OptiFine (client only)
ZZZZZ Custom Configs

**Thermos Version:**
1.7.10-1614

**Forge Version:**
1.7.10-10.13.4.1614

Hi ! To begin, I'm French, so maybe don't I have a really good English. Please don't blame me for that ! :c

On a modded server running on Thermos, I have a mod called ZZZZZ Custom Configs, the most important features of which is that we can create recipes and remove repices. Y'understand? c:

<RemoveRecipes>
<output1>minecraft:chest 1 0</output1>
<output2>minecraft:painting 1 0</output2>
<output3>ganyssurface:portabledualworktable 1 0</output3>
<output4>ganyssurface:icypickaxe 1 0</output4>
<output5>ganyssurface:painting 1 0</output5>
</RemoveRecipes>

On that configuration of the recipe remover ... configuration, the vanilla chest and the vanilla painting correctly lost their recipes, but the modded items like avec Gany's Surface's portable dual work table, icy pickaxe and painting don't!! Y'understand? c:

So I just replaced all the ids by their numeral ids which are 4122, 4123 and 4125 :
<output3>4122 1 0</output3>
<output4>4123 1 0</output4>
<output5>4125 1 0</output5>
... but it doesn't function better. ;-;

I don't really know if Thermos be there for something on this problem...

Does anyone know the solution ? Please ? :c

**Comment by Time6628** [comment]
Have you tried MineTweaker?

**Comment by Kruxy** [comment]
I didn't know that mod! ô_o I will test it! :P

**Comment by Kruxy** [comment]
Finally, ZZZZZ Custom Configs had functioned! I just wrote that :
	<output3>4122 1 0</output3>
	<output4>ganyssurface:portabledualworktable 1 0</output4>
	<output5>ganyssurface:portableDualWorkTable 1 0</output5>
	<output6>ganyssurface:portable_dual_work_table 1 0</output6>
	<output7>GANYSSURFACE_PORTABLEDUALWORKTABLE 1 0</output7>
	<output8>GANYSSURFACE_PORTABLE_DUAL_WORK_TABLE 1 0</output8>
	<output9>ganyssurface:GANYSSURFACE_PORTABLEDUALWORKTABLE 1 0</output9>
	<output10>ganyssurface:GANYSSURFACE_PORTABLE_DUAL_WORK_TABLE 1 0</output10>
	<output11>ganyssurface:4122 1 0</output11>
	<output12>minecraft:4122 1 0</output12>
So I have to find the correct one and delete the others, now. x)

But thank you for MineTweaker, it could be useful for me.
'nice day!
