### ISSUE TITLE
Thaumcraft 4 Pech Forager + Thermos

### ISSUE THREAD

**Issue by xSable** [CyberdyneCC/Thermos#361]
-Server Log + FML Log:
https://gist.github.com/xSable/2e0b5733a2cc1794a2b56731982ffc3d

-Explanation:
The issue seems to occur with Pech Foragers specifically. I've had multiple crashes on my server as soon as a player loads in, and they are all related to Pech Forager entities. This has never happened with KCauldron, with all the same mods. I recently switched to Thermos to solve the Ars Magica 2 issues KCauldron had (worked beautifully), but I never expect perfection, so it was only a matter of time before something went wrong.

-Recreating the Issue:
I'm not exactly sure how to recreate the issue, so instead I have uploaded a crash report. This is one of many. All of which had Pech Forager problems, and with multiple players. It appears to just happen with some of them that spawn. I spawned in a couple myself, and there was no issue. Again, this issue has never occured with KCauldron, and all the same mods.

https://gist.github.com/xSable/704c8cbdebc437f0e5d4d8e33e4003e8

-Modpack Name:
Wizard Academy

-Mods Installed:
Ars Magica 2
AbyssalCraft
AnimationAPI
Automagy
Backpack
Baubles
BiblioCraft
Blood Magic
Botania
bspkrsCore
Chisel 2
CodeChickenCore
CodeChickenLib
CoroUtil
Crafting Tweaks
CustomNPCs
DummyCore
EvilCraft
ExtraTiC
Forbidden Magic
Gadomancy
Guide API
Infernal Mobs
Inventory Tweaks
Iron Chest
Jabba
Lucky Blocks
Magical Crops
Mantle
Metallurgy + Core
MrCrayfish Furniture Mod
NoMoreRecipeConflict
NotEnoughItems
Pam's Harvestcraft
RTG - Realistic Terrain Generation
Sanguimancy
Sanguine Utilities
Soul Shards Reborn
Tainted Magic
TC Node Tracker
Tinkers' Construct
Thaumcraft 4
Thaumcraft NEI Plugin
Thaumic Bases
Thaumic Horizons
Thaumic Tinkerer
TravellersGear
Twilight Forest
UpdateCheckerMod
Waila
Waila Harvestability
Wawla
Witchery
Witching Gadgets

-Plugins:
AsyncWorldEdit
BanItem
Clearlag
CoreProtect
Essentials
GlobalMarket
KeepDeathDrop
KitAdder
Multiverse-Core
OnTime
OpenInv
PermissionsEx
Plugman
ProtocolLib
RandomTP
ServerSigns
SimpleBroadcast
SimpleClans
SimpleTicketManager
VanishNoPacket
Vault
VoidWorld
Voxelsniper
WorldBorder
WorldEdit
WorldGuard
X-Blocker (Custom Plugin for blocking item use in WG Region)

-Thermos Version:
Thermos-1.7.10-1614-56

-Forge Version:
1.7.10 - 10.13.4.1614

Any help is greatly appreciated.

EDIT-1: Also would like to note, using /killall monsters in the world with the issue as soon as the player logged in, removed the Pech Foragers, and the players were able to join properly.

Also, have since disabled Pech spawning in Thaumcraft.cfg, and haven't had the issue.

**Comment by Time6628** [comment]
How about with build 55?

**Comment by xSable** [comment]
Not sure, I have a test server that is separate, I'll throw B55 on there and start spawning a bunch of Pechs to give it a go.

Will update.

**Comment by Time6628** [comment]
This is fixed in the newer commits, not official release atm though.
