### ISSUE TITLE
Lib's Disguises error

### ISSUE THREAD

**Issue by NDruce** [CyberdyneCC/Thermos#363]
**Server Log:** http://pastebin.com/J3ycuBGa

**FML Log(s):** none

**Explanation of issue:** Lib's Disguises plugin prints errors in console on startup. Plugin for 1.7.10 with Forge support: https://www.dropbox.com/s/wvo12rjlanxxa7v/LibsDisguises.jar?dl=1

**How to recreate this issue:** Idk, see log

**Modpack Name:** none

**Mods Installed:** none

**Plugins Installed:** Lib's Disguises, ProtocolLib, PermissionsEx. Also tried to install Minecraft Comes Alive (Real Villager Towns), but it also don't work (I think because it error in Lib's Disguises)

**Warmroast Report:** none

**Thermos Version:** 55-56

**Forge Version:** 1614

**Comment by Robotia** [comment]
LibDisguises is accessing fields it shouldn't be accessing through reflection. These fields have been renamed by Forge and when it tries to access them expecting the Bukkit format, it fails. I am sorry but we are unable to support this plugin. Several authors have been able to create effects plugins that support Thermos, but I do not believe LibDisguises has done this.

**Comment by NDruce** [comment]
I need it for one special NPC plugin and my custom plugins

**Comment by iKaneki-Ken** [comment]
Whether you need it or not is irrelevant, Robotia has made it very clear that it's unable to be supported due to the fact of how it was coded. Either fix the plugin yourself to be compatible with Forge's methods, or move onto something else.

**Comment by NDruce** [comment]
I already decompiled Forge version of LibsDisguises. This plugin works but sending errors in console:
http://pastebin.com/UNuDEH0P

> java.lang.NoSuchMethodException: net.minecraft.util.AxisAlignedBB.<init>(double, double, double, double, double, double)

What the new name of AxisAlignedBB method?

**Comment by NDruce** [comment]
I will reborn this plugin. Just help me with some Forge methods I posted here

**Comment by NDruce** [comment]
https://github.com/NDruce/LibsDisguisesThermos/blob/master/me/libraryaddict/disguise/utilities/ReflectionManager.java
