### ISSUE TITLE
Mods missing?

### ISSUE THREAD

**Issue by AssassinsKeeper** [CyberdyneCC/Thermos#367]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/AssassinsKeeper/b369bd3fe5fee753bfff26c9f467c430

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/AssassinsKeeper/32718f62abbfb47c3c6f91f703afa697

**Explanation of issue:**
On connection, I get an issue where "kimagine" is missing. I've seen this issue when I've googled it, but the links point to the Thermos forums which are ironically down. Apparently the solution was held on the forums...

**How to recreate this issue:**
Install Thermal Expansion? Not sure though, that's just one of the mod additions I had made.

**Modpack Name:** *(Only if public)*
Not public, sorry :(

**Mods Installed:**

- Applied Energistics
- Archimedes Ships
- Big Reactors
- Buildcraft
- Carpenter's Blocks
- Chisel
- Code Chicken Lib
- Coding Lib
- CoFHCore
- ComputerCraft
- Custom NPCs
- Decocraft
- Ender Core
- Ender IO
- EJML Core
- Extra utilities
- Fastcraft
- Flaxbeard's Steam Power
- Forge Multipart
- Forge Relocation
- Forge Relocation FMP
- MrTJPCore
- Hats
- iChunUtil
- Immersive Engineering
- IC2
- Iron Chest
- Malisis Core
- Malisis Doors
- Mantle
- Mekanism
- Mekanism Generators
- Mekanism Tools
- Morpheus
- MrCrayfish Furniture Mod
- Natura
- Open Blocks
- Open Mods Lib
- Pam's Harvestcraft
- Portal Gun
- Project E
- All project Red mods
- Simply Jetpacks
- TConstruct
- Thermal Expansion
- Thermal Foundation
- Twilight Forest
- Voltz Engine
- Waila
- Wawla

**Plugins Installed:**
- PermissionsEx
- PlugMan
- WorldEdit
- Essentials
- Voxel Sniper
- Essentials Spawn
- Essentials Chat
- Essentials Anti Build
- Essentials Protect

**Warmroast Report:** *(Optional)*

**Thermos Version:**
1.7.10-1614.56

**Forge Version:**
10.13.4.1566

**Comment by Tencao** [comment]
I doubt this is a thermal expansion issue, as my modpack also uses this mod with the server running thermos, and clients can join fine. The best thing to do, is do a directory search on both the servers mod directory and the client and see if you can find it. Sometimes, some mods can hide in the 1.7.10 folder under mods.

**Comment by spannerman79** [comment]
> On connection, I get an issue where "kimagine" is missing. I've seen this issue when I've googled it, but the links point to the Thermos forums which are ironically down. Apparently the solution was held on the forums...

The "soloution" was that it wasn't a server issue. That mod is a server side component that was originally added into KCauldron for which Thermos is forked from.

Its exactly the same as any server sided mod - like [Morpheus](http://minecraft.curseforge.com/projects/morpheus), [JourneyMap Server](http://minecraft.curseforge.com/projects/journeymap-server) and other mods that are pure server side only mods.

What isn't shown is the actual client log to show what is missing mod wise.

**Comment by AssassinsKeeper** [comment]
So, it's started working for some reason, although when I try to connect, the client runs this message in the log:
`[10:58:17] [Netty Client IO #1/INFO] [FML]: Attempting connection with missing mods [CodeChickenCore, NotEnoughItems, FastCraft, ArmorStatusHUD, StatusEffectHUD, TiCTooltips, bspkrsCore] at SERVER
`
Which is understandable, those are client-only mods (correct me if I'm wrong).

**Comment by Time6628** [comment]
Those are simply the client side mods the server doesn't have.
