### ISSUE TITLE
[Suggestion] never-ever-tick for tileentities.yml

### ISSUE THREAD

**Issue by joserobjr** [CyberdyneCC/Thermos#368]
I have players using a specific block abusively on my server so I'm trying to make it become merely decorative, without impact to the server tick rate and disabling the block functionality. I it would be fine if I could set it to never tick just like we can set an entity to never tick on entities.yml.

**Comment by iKaneki-Ken** [comment]
I completely agree with this. Wondering if it be possible to specific which worlds this logic specifically applies to as well.

**Comment by Robotia** [comment]
Hi,
The block can't function if it doesn't tick. This would be the same as disabling the block. :confused:

**Comment by Bogdan-G** [comment]
hmm disable block update? but because ye are will communicate with the block?

**Comment by Robotia** [comment]
This is not really necessary, considering that you could just set the tick-interval to a large number of ticks.
You could set it to: 2147483647
