### ISSUE TITLE
Need Help, Please Understand

### ISSUE THREAD

**Issue by kylanrock8** [CyberdyneCC/Thermos#374]
As embarrassing as this is, I cannot get Thermos to work. I couldn't find anywhere else to get help on this, so I had to disregard the normal format. I understand if people are angry about this. I followed all the steps at http://cyberdynecc.github.io/Thermos/install At the end it just says "You're good to go!", but that doesn't really help me. When I try to run it, this is what shows: http://pastebin.com/CmKiHz73
A couple of minutes later, it says A problem occurred running the Server launcher.
I'm not sure what I'm doing wrong, and it is probably something extremely simple. This is my first time ever using Thermos, please forgive me.

Sorry if I have bad english. This is not my first language.

**Comment by Robotia** [comment]
Hi @kylanrock8 ,
Please share the file: "logs/latest.log"
Also, what language?

**Comment by EXilE-EXistance** [comment]
Try it with just the max and min ram arguments and, post a screenshot of
your server folders?

**Comment by kylanrock8** [comment]
[latest.zip](https://github.com/CyberdyneCC/Thermos/files/288131/latest.zip)
There is log. My partner speaks english mainly and I am doing this for him so English would still be best.

**Comment by Robotia** [comment]
The error is because you have Mobiuscore installed, remove it and the server should work fine.
Still, what language?

**Comment by kylanrock8** [comment]
Spanish if this is still an issue. I think I see problem now. Thanks for now.
