### ISSUE TITLE
[URGENT] MultiInv Issue [Or Just Multiple World Inventories in General)

### ISSUE THREAD

**Issue by BungeeTheCookie** [CyberdyneCC/Thermos#375]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))* No errors

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:** I tried using MultiInv, and my own custom version of PerWorldInventory on a Thermos server. Switching between creative and survival worked, but when I tried to teleport between worlds, my inventory remained the same, when it is supposed to be different. However, In Spigot, this does not happen, and my inventories are separate.

**How to recreate this issue:** Test MultiInv on a Spigot server, install Multiverse, and do /mvtp between worlds. As you can see, the inventories are separated. When you do the same thing on Thermos, inventories are the same.

I am suspecting WorldTeleportEvent is not being called.

**Modpack Name:** *(Only if public)*

**Mods Installed:**

**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:**

**Forge Version:**

**Comment by NDruce** [comment]
#349 already created issue
