### ISSUE TITLE
Factions

### ISSUE THREAD

**Issue by edgarasf123** [CyberdyneCC/Thermos#377]
**Explanation of issue:**
I'm looking for a property claim plugin that is compatible with forge mods. And according to this repository's Readme, Factions is what I should be looking for. But it doesn't suggest which versions of Factions is compatible, nor the site where [Fixed](http://gogs.tcpr.ca/TCPR/Fixes) links to contains any Factions plugin.
![http://i.imgur.com/loDnP7A.png](http://i.imgur.com/loDnP7A.png)

I  tried using various versions of Factions and MassiveCore and none of them works for me, I'm getting errors when trying to claim land. ```ERROR: Your "CommandSender Link" has been severed.```

**Modpack Name:** *(Only if public)*
FTB Infinity Evolved 2.5.0

**Mods Installed:**
http://ftbwiki.org/Feed_The_Beast_Infinity_Evolved#Mod_List

**Warmroast Report:** *(Optional)*

**Thermos Version:**
B57

**Forge Version:**
Don't know, I downloaded following file for server ```Thermos-1.7.10-1614-server.jar```

**Comment by spannerman79** [comment]
Logs?

**Comment by spannerman79** [comment]
#353

**Comment by Time6628** [comment]
I personally recommend https://github.com/KaiKikuchi/GriefPreventionPlus it's much less buggy than factions and it protects against a lot of modded things.

**Comment by edgarasf123** [comment]
I couldn't find compiled version of GriefPreventionPlus. The download site shows 404.

**Comment by spannerman79** [comment]
https://github.com/KaiKikuchi/GriefPreventionPlus/releases
