### ISSUE TITLE
Fast leaf decay

### ISSUE THREAD

**Issue by ArcasCZ** [CyberdyneCC/Thermos#378]
What about implementing Fast Leaf Decay (as KCauldron)? It's really usefull, 'cause you have not to use another mod for this.

**Comment by spannerman79** [comment]
This would conflict with [Random Things](http://minecraft.curseforge.com/projects/random-things)

**Comment by ArcasCZ** [comment]
@spannerman79 What does this mod do?

**Comment by Robotia** [comment]
I no longer have access to the KCauldron github. If anyone has a mirror of the git repo from the last time it was up, please contact me on Discord. Thanks!

**Comment by bookerthegeek** [comment]
I'll look @Robotia

As for the OP... there are plenty of plugins and mods that do this. 

The amount of work required to support each mod added  leaves would be enough work on its own. People still can't get great wood leaves to decay quickly correctly. As much as I'd like it, I'll say no.

**Comment by ArcasCZ** [comment]
@bookerthegeek Not at all. Prototik's Fast Leaf Decay worked for all leaves.

**Comment by spannerman79** [comment]
> @spannerman79 What does this mod do?

Aside for adding random things in (use google to find out) one thing it already adds is fast leaf decay for which is incompatable with the newest build of KCauldron.  I don't use the newest build i build my own.

**Comment by ArcasCZ** [comment]
@spannerman79 That is not problem - in KCauldron you can disable fast leaf decay, so it has not to interact.

**Comment by ArcasCZ** [comment]
Yes, you can have another mod. But it can be implemented in server, so why not?

**Comment by bookerthegeek** [comment]
Cause you can do one thing really good or a lot of things sorta okish.

**Comment by Time6628** [comment]
There's many mods and plugins that do this already. It can be done in a server, but why should it?

**Comment by Yanniclord** [comment]
@spannerman79 Any possibility of you sharing that build you made for yourself with us? My server crashes with Random Things and its fast leaf decay, and would love to have that fixed.

**Comment by spannerman79** [comment]
No. LGPL requires source code to be provided with any bins distrubuted. I am not willing to do that.

My build is for my own private use only.

**Comment by Yanniclord** [comment]
Ok and sharing it with only me? Since its not public then, LGPL doesn't seem to apply.

**Comment by spannerman79** [comment]
https://www.qt.io/qt-licensing-terms/

Read "Developing with LGPL"

**Comment by Yanniclord** [comment]
Actually, never mind. I fixed it.

**Comment by Time6628** [comment]
Going to close this as it's not going to be implemented.
