### ISSUE TITLE
/tps show wrong tps

### ISSUE THREAD

**Issue by BlayzerQ** [CyberdyneCC/Thermos#379]
On last version Thermos command "/tps" show wrong tps.
/tps show ~10 tps:
https://pp.vk.me/c636121/v636121881/d99a/PdQYLGv6PhM.jpg
real tps ~19:
https://pp.vk.me/c636121/v636121881/d9a2/0az42pAADJU.jpg
Its TickProfiler (mod) output. And Timmings show ~19 tps.
https://timings.spigotmc.org/?url=16923669

**Comment by JewishDog** [comment]
use /thermos tps

**Comment by Robotia** [comment]
This tps looks correct...from the spigot log, plugins seem to be causing a lot of lag. This would probably not be counted by tick profiler.

**Comment by BlayzerQ** [comment]
/thermos tps show ~20 tps:
https://pp.vk.me/c636121/v636121881/d9b3/RdTo4tBBIhI.jpg

**Comment by Robotia** [comment]
And still /tps incorrect?

**Comment by BlayzerQ** [comment]
Yes. But after restarting the server, /tps show correct. This is strange.

**Comment by Robotia** [comment]
Strange, might've just been a random error.

**Comment by Time6628** [comment]
The Bukkit /tps command is wrong most of the time, in my experience.

**Comment by Time6628** [comment]
I recommend /forge tps or /cofh tps (if you have CoFHCore).
