### ISSUE TITLE
/fly and /home bug

### ISSUE THREAD

**Issue by BlayzerQ** [CyberdyneCC/Thermos#380]
If activate fly mode (i use Essentials), fly 20 blocks and and higher of ground (Only Ender world) and use /home (i use MyHome) for teleport to home point, player dies (He fell from a height).

**Comment by BlayzerQ** [comment]
Hmmm, after restart this does not work. Its very strange.

**Comment by Robotia** [comment]
There must be something wrong with your server instance.
