### ISSUE TITLE
Can't start a Thermos server with TheFerretBusiness Modpack

### ISSUE THREAD

**Issue by A-xis** [CyberdyneCC/Thermos#387]
**Server Log:** server is not starting

**FML Log(s):** https://gist.github.com/A-xis/f92496b029acb64ac8d20bebbd327da2

**Explanation of issue:** When trying to launch thermos with this modpack, server fail with `A problem occurred running the Server launcher.`

**How to recreate this issue:** download TheFerretBusiness 0.1.3 and Thermos 57 w forge 1614 and try to start it.

**Modpack Name:** TheFerretBusiness v 0.1.3 (Server version of course) available on FTB launcher (http://forum.feed-the-beast.com/threads/1-7-10-the-ferret-business-wip-hqm-425-quests-v-0-1-3.64930/)

**Mods Installed:** https://docs.google.com/document/d/1Qob-8kJ4fK5Yunv8PiNr6p5OwXbgjJMmxaubz7DOuPE/edit
ae2stuff-0.5.0.56-mc1.7.10
AgriCraft-1.7.10-1.4.0-beta-2-1.7.10
AOBD-2.8.4
appliedenergistics2-rv2-stable-10
Aroma1997Core-1.7.10-1.0.2.16
AromaBackup-1.7.10-0.1.0.0
AsieLib-1.7.10-0.4.5
AuraCascade-557
Avaritia-1.0
backpack-2.0.1-1.7.x
bdlib-1.9.4.109-mc1.7.10
BeeSpecific-1.7.10-1.0.0
BiblioCraft[v1.11.4][MC1.7.10]
BigReactors-0.4.3A
Binnie Patcher 1.6
binnie-mods-2.0-pre14
BloodMagic-1.7.10-1.3.3-17
Botania r1.8-249
BrandonsCore-1.0.0.11
buildcraft-7.1.16
buildcraft-compat-7.1.3
Carpenter's Blocks v3.3.7 - MC 1.7.10
CartFixes-1.7.10-0.1.0
catwalks-2.0.3
Chisel-2.9.5.11
CodeChickenCore-1.7.10-1.0.7.47-universal
CoFHCore-[1.7.10]3.1.2-325
compactmachines-1.7.10-1.21
compactstorage-1.7.10-release-2.1.0-lts.21-universal
ComputerCraft1.75
ComputerCraftEdu1.74
Computronics-1.7.10-1.6.0
cookingbook-mc1.7.10-1.0.134
CustomMainMenu-MC1.7.10-1.9.2
Decocraft-2.2.1_1.7.10
denseores-1.6.2
dimensional-anchor-59.0.3
DoggyStyle-1.1.3.99
Draconic-Evolution-1.7.10-1.0.2
Enchiridion 2-1.7.10-2.0.2a(FerretBusinessCustom)
EnderCore-1.7.10-0.2.0.32_beta
EnderIO-1.7.10-2.3.0.424_beta
EnderStorage-1.7.10-1.4.7.37-universal
EnhancedPortals_1.7.10-universal-3.0.12
Exotic Birds 1.7.10 - 1.0.3b
ExtraCells-1.7.10-2.3.9b188
ExtraTiC-1.7.10-1.4.5
extrautilities-1.2.12
fastcraft-1.21
Ferret Shinies-1.2.98
FlatSigns-1.7.10-universal-2.0.0.17
Fluxed-Crystals2-1.0.7
Forbidden Magic-1.7.10-0.573
forestry_1.7.10-4.2.11.59
FoxLib-1.7.10-0.7.0
gendustry-1.6.4.133-mc1.7.10
GrimoireOfGaia3-1.7.10-1.2.7
HQM-FerretBusiness-Custom (4.4.4)
iChunUtil-4.2.2
IguanaTinkerTweaks-1.7.10-2.1.6
ImmersiveEngineering-0.7.4
immibis-core-59.1.2
INpureCore-[1.7.10]1.0.0B9-62
InventoryTweaks-1.59-dev-152
ironchest-1.7.10-6.0.62.742-universal
Jabba-1.2.1a_1.7.10
journeymap-1.7.10-5.1.4-unlimited
magicbees-1.7.10-2.4.3
malisiscore-1.7.10-0.14.3
malisisdoors-1.7.10-1.13.2
Mantle-1.7.10-0.3.2b
MatterOverdrive-1.7.10-0.4.1
mcjtylib-1.8.1
Mekanism-1.7.10-8.1.9.265
MekanismGenerators-1.7.10-8.1.9.265
MekanismTools-1.7.10-8.1.9.265
MineFactoryReloaded-[1.7.10]2.8.2B1-178
MineMenu-1.7.10-1.2.0.B44-universal
MineTweaker3-1.7.10-3.0.10B
MobProperties-1.7.10-0.4.2
ModTweaker2-0.9.5
Morph-Beta-0.9.2
natura-1.7.10-2.2.1a2
neiaddons-1.12.15.41-mc1.7.10
NEIIntegration-MC1.7.10-1.1.2
NetherOres-[1.7.10]2.3.1-22
NotEnoughItems-1.7.10-1.0.5.118-universal
NotEnoughResources-1.7.10-0.1.0-122
OpenBlocks-1.7.10-1.5.1
OpenComputers-MC1.7.10-1.5.22.46-universal
OpenEye-0.6-1.7.10
OpenModsLib-1.7.10-0.9.1
OpenModularTurrets-1.7.10-2.1.9-211
OpenPeripheralCore-1.7.10-1.3
Opis-1.3.1-MAPLESS_1.7.10
Pam's HarvestCraft 1.7.10Lb
ProjectRed-1.7.10-4.7.0pre12.95-Base
ProjectRed-1.7.10-4.7.0pre12.95-Fabrication
ProjectRed-1.7.10-4.7.0pre12.95-Integration
ProjectRed-1.7.10-4.7.0pre12.95-Lighting
ProjectRed-1.7.10-4.7.0pre12.95-Mechanical
ProjectRed-1.7.10-4.7.0pre12.95-World
RandomThings-2.2.4
ResourceLoader-1.0
rftools-4.23
roguelike-1.7.10-1.4.4
RTG-1.7.10-0.7.0
SimplyJetpacks-MC1.7.10-1.5.3
SolarExpansion-Basic-1.6a
StacksOnStacks-1.7.10-2.4.2
StevesAddons-1.7.10-0.10.16
StevesCarts2.0.0.b18
StevesFactoryManagerA93
StevesWorkshop-0.5.1
StorageDrawers-1.7.10-1.9.7
Tails-1.7.10-1.4.1a
tcinventoryscan-mc1.7.10-1.0.8
tcnodetracker-1.7.10-1.1.2
TConstruct-1.7.10-1.8.7
Thaumcraft-1.7.10-4.2.3.5
thaumcraftneiplugin-1.7.10-1.7
thaumicenergistics-0.8.10.10
ThaumicExploration-1.7.10-1.1-53
thaumicSanity-1.0-1.7.10-9
ThaumicTinkerer-2.5-1.7.10-470
ThermalDynamics-[1.7.10]1.2.0B2-169
ThermalExpansion-[1.7.10]4.1.2-240
ThermalFoundation-[1.7.10]1.2.3-112
TiCTooltips-mc1.7.10-1.2.5
TMechworks-1.7.10-0.2.14.100
Toolbox-1.7.10-1.2.3
TravellersGear-1.7.10-1.16.5
twilightforest-1.7.10-2.3.7
VeinMiner-1.7.10_0.31.4.unknown
Waila-1.5.10_1.7.10
WailaHarvestability-mc1.7.10-1.1.6
WAILAPlugins-MC1.7.10-0.2.0-23
warpbook-1.7.10_2.0.37
witchery-1.7.10-0.24.1
Yampst-The Ferret Business-0.1.3
Ztones-1.7.10-2.2.1
[1.7.10]ArmorStatusHUD-client-1.27
[1.7.10]StartingInventory-universal-1.7.10.r03
[1.7.10]StatusEffectHUD-client-1.26

**Plugins Installed:** none

**Warmroast Report:** *(Optional)*

**Thermos Version:** 57

**Forge Version:** 1614

**Comment by Time6628** [comment]
You have mobiusCore installed.

**Comment by spannerman79** [comment]
https://gist.github.com/A-xis/f92496b029acb64ac8d20bebbd327da2#file-logs-fml-server-latest-log-L70

https://github.com/CyberdyneCC/Thermos#known-caveats-use-provided-fixes-at-your-own-risk

**Comment by A-xis** [comment]
Well... sometimes, you just feel stupid...

Thanks guys.
