### ISSUE TITLE
server crash with LC.. decorator crash

### ISSUE THREAD

**Issue by Cronosus** [CyberdyneCC/Thermos#389]
**Server Log:**
http://pastebin.com/MxSDfUch
http://cronos.wz.cz/mc/gc/2016-06-04-5.log
**FML Log(s):**
http://cronos.wz.cz/mc/gc/fml-server-2.log
**Explanation of issue:**
server crashing when crafting decorator
i dont know, if is problem in mod or server, but happens only on server, not in SP.
**How to recreate this issue:**
When i try to craft decorator from lanteacraft on serverside, server crashing
**Modpack Name:** *(Only if public)*
not yet public, galaxycraft.cz
**Mods Installed:**
in logs, but happens when you have just lanteacraft on server
**Plugins Installed:**
in logs, but happens without plugins too
**Thermos Version:**
Thermos-1.7.10-1614-server
**Forge Version:**
1614?

can you help?
thanks in advance

**Comment by EXilE-EXistance** [comment]
you need to post your thermos build number, latest stable is build 55

**Comment by Cronosus** [comment]
build 57

**Comment by Robotia** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11097096/15800646/bf77b974-2a4c-11e6-8b80-3c28abdb7e92.png)
This mod is using methods only available clientside. Not a problem on our end.
You might have installed the version intended for singleplayer, the developer might've made a mistake, or this mod was only designed with singleplayer in mind.

**Comment by Cronosus** [comment]
ok, this is what i need to know
thanks :)
