### ISSUE TITLE
Zivicio Armor, fall damage - lost all items.

### ISSUE THREAD

**Issue by BlayzerQ** [CyberdyneCC/Thermos#390]
If you die after falling from a height in the ziivicio armor of a Magical Cropts - lost all items.
Errors in the log no. On KCauldron no such problem was only after the transition to Thermos appeared.
Thermos version: Thermos:1.7.10-1614.56
Log: https://www.dropbox.com/s/jl78b73zau7jay1/fml-server-latest.log?dl=0

**Comment by Time6628** [comment]
Build 56 is unstable, try 57 or 55.
