### ISSUE TITLE
ExNihilo barrels not filling up with rain

### ISSUE THREAD

**Issue by Tencao** [CyberdyneCC/Thermos#395]
**Server Log:** *No log output*

**FML Log(s):** *No log output*

**Explanation of issue:** - Normally when the server rains, the barrels from this mod is suppose to fill up, however on thermos, it doesn't seem to recognize it's raining. This works perfectly fine on single player, so I can only assume this is an issue with Thermos

**How to recreate this issue:** - Place empty barrel from mod and set weather to rain

**Modpack Name:** N/A

**Mods Installed:** http://pastebin.com/CAnveSjW

**Plugins Installed:** Plugins (40): CleanroomGenerator , CoreProtect, MinecraftMarket, dynmap, Announcement, WorldEdit, Playtime, ServerMaintenance, Questioner, Essentials, RemoteToolkitPlugin, RestartTime, BukkitCompat, AdvancedBan, SimpleWarnings, WorldBorder, SaveIt, Multiverse-Core, WorldGuard, SlowChat, BanVote, MessageConsistency, EssentialsGeoIP, PermissionsEx, AntiCapsLock, Multiverse-Portals, Vault, EssentialsSpawn, BungeeTabListPlus, ItemRestrict, afkTerminator, NoItem, Herochat, Autorank, uSkyBlock, LWC, TecEE, ReportRTS, AncientGates, Multiverse-NetherPortals

**Warmroast Report:** *(Optional)*

**Thermos Version:** Build 55

**Forge Version:** 1614

**Comment by Time6628** [comment]
How are you setting it to rain? And do you have a block over the barrel? And what about something still in the barrel?

**Comment by Tencao** [comment]
I'm using the same rain command I did in single player. No block is covering the top, and the barrel was freshly spawned with nothing inside

**Comment by Tencao** [comment]
I would like to add onto this by saying I've removed every plugin and the issue is still present, so this is not a plugin issue.

**Comment by Tencao** [comment]
Ok, I have finally found the issue, and solution, so I'm putting it here but I would prefer to see a perm fix. In the tileentities, the tick-no-players option must be set to true. Even if a player is right next to it, it will not fill up otherwise. The reason I'm asking for more of a perm fix despite finding a solution is because by default, thermos sets everything to false, making it not work out of the box.

**Comment by spannerman79** [comment]
> The reason I'm asking for more of a perm fix despite finding a solution is because by default, thermos sets everything to false, making it not work out of the box

This was put in place well before the Thermos team created this fork.  In fact it was the original cauldron dev team that introduced `skip-tileentity-ticks: true` within `tileentities.yml`1

**This** is why myself and others have stated before and continue to state that running a cauldron based server isn't just point and click.  This issue should never have been raised nor opened.

**Comment by Tencao** [comment]
I know that cauldron based servers, even forks will contain issues, however if a block like this is proven to not work with this option, which that option does sometimes break, then by default you should try and set their default option to true to at least give some better compatibility, or at least some kind of public fix list for problems such as this. 

Even if the problem didn't start with thermos, I would like to see thermos resolve alot of these problems and become much better as a result.

**Comment by spannerman79** [comment]
Changing this will create other incompatabilities with other mods.  The default options are there for a reason - yes not *all* work with default but the vast majority do.

Here is an example.  I go to purchase a car, should a manufacturer specifically design a car suited just for me or should i find the best configuration and design of a certian make and model that would suit me best? I already know this answer as I already been down this exact path myself.

This is why configuration options exist - to give choice.  Hence why its up to the server owner to make a choice based on what they want - not what everyone else should have.

**Comment by Tencao** [comment]
Like I said, even if you cant change defaults to a per mod block basis, create some kind of public wiki that contains a list of mod issues and how to solve them, so if something like this comes up, we can add it to that list for others to see.

**Comment by spannerman79** [comment]
> Like I said, even if you cant change defaults to a per mod block basis

Actually *you* can - look within `tileentities.yml`. There was a wiki of sorts back in the day but even those devs had issues to keep it up to date due to the vast number of times that a mod dev changes something without giving any sort of feedback to the cauldron dev team. So one of the original cauldron dev team added and inserted `Setting: debug.enable-te-place-warning` so a server owner can approach the dev/s responsible for that specific mod

If you actually checked `tileentities.yml` you would have seen it populate TE's and their options.  Take the vanilla chest snip being;
```
    net-minecraft-tileentity-TileEntityChest:
      tick-no-players: false
      tick-interval: 1
````
If i wanted vannilla chests to tick without players being around I would change `tick-no-players` to `true`.  Like i said before configuation options exist to give choice.  Trying to create a wiki for those choices is trying to count the number of uniqure snowflakes that can exist.

**Comment by Time6628** [comment]
Does this happen without uSkyBlock and world guard?

**Comment by Tencao** [comment]
Yes, as stated above, I've removed all mods excluding this and two others I was unable to remove (Cofh, and Nether Ores), and removed all plugins. The issue was down to the block not set to tick when no players was around, even though players was around the block during it.

**Comment by Time6628** [comment]
Alright since you seemed to have fixed the issue I'll close this issue.
