### ISSUE TITLE
Possible Ancient Warfare issue

### ISSUE THREAD

**Issue by aetherpirate** [CyberdyneCC/Thermos#396]
http://pastebin.com/ejS8fEUH

No crashlog generated

Working on Ancient Warfare (2.4.115) windmill, crashes within moments

go to windmill, attempt construction by placing windmill blades

Too Much Tech, Too Few Ores (Technic Launcher)

http://pastebin.com/BKVFw0n1    -- mod list

worldguard, essentials, essentials spawn, greifprotection

**Warmroast Report:** *(Optional)*

Thermos 1614-56

Forge 1614

**Comment by spannerman79** [comment]
Remove DragonAPI

**Comment by aetherpirate** [comment]
For testing? Or as a permanent solution? I also have RotaryCraft, ReactorCraft, and ElectriciCraft which need DragonAPI

**Comment by spannerman79** [comment]
Permanent. None of those work with Thermos. As to why - search this and other issue trackers.

**Comment by aetherpirate** [comment]
Just read a few threads. That's a shame, I really like his mods. Maybe someday DragonAPI and Thermos can work together.

**Comment by spannerman79** [comment]
As do I but in life not everything goes as what we want.

**Comment by Time6628** [comment]
That version of DragonAPI should work with Thermos and all other Cauldron versions.

**Comment by Time6628** [comment]
Actually, in the newer versions of DragonAPI he added Cauldron/Thermos support.

**Comment by aetherpirate** [comment]
That is good news. 

I removed all Reika's mods and I am still having the a similar issue. No crash on server, but client times out while working on windmill.

Latest log attached. 
[latest.txt](https://github.com/CyberdyneCC/Thermos/files/305714/latest.txt)

**Comment by Time6628** [comment]
Your server is stalling.

**Comment by aetherpirate** [comment]
Any idea why? Its a new map with just me connected. Not much built yet. I'll try running warmroast while playing and see what comes of it.

**Comment by Time6628** [comment]
What is your timeout time in spigot.yml?

**Comment by aetherpirate** [comment]
timeout-time: 90

**Comment by Time6628** [comment]
Set that to 900 or more.

**Comment by aetherpirate** [comment]
Done. Re-launching and testing.

**Comment by bookerthegeek** [comment]
@spannerman79 they do work with thermos. Specifically because I am running them together. 

Please be more carefully of spreading disinformation.

**Comment by aetherpirate** [comment]
Same result. As soon as I place another windmill block down, I timeout about 5 seconds later. 

If I do not attempt to build it, I can play normally. 

The windmill is a multiblock, I am trying to make the max size. It only forms when complete.

**Comment by Time6628** [comment]
Looking at your warm roast, ancient warfare is calling a method over and over causing the server to stall.
