### ISSUE TITLE
Thermos Build 55, Multiverse Core 2.4 & uSkyblocks issue

### ISSUE THREAD

**Issue by djoveryde** [CyberdyneCC/Thermos#403]
Ok so further to #313 , I am perhaps getting the error causing the issues. This is on a Skyblocks world that uses multiverse to run.
This seems to be a major issue spanning across any plugin that uses its own world.
This is the error I get during load up.

I really hope this error finally gets to the bottom of all the issues that thermos has had with multi world plugins.

http://pastebin.com/zEFZ8XC5

**Comment by Time6628** [comment]
You are using incompatible versions of USB and MV.

**Comment by djoveryde** [comment]
Ok that fixed that issue, only issue now is after making an island if I do /is restart it will spawn me in the air like I'm in a corrupt chunk. No console error. Not sure if there's any relation to thermos on that. Also mobs fail to spawn as well.

**Comment by Time6628** [comment]
I recommend GPPSkyBlock. https://github.com/KaiKikuchi/GriefPreventionPlus-SkyBlock 
The developers of uSkyBlock no longer offer Cauldron/KCauldron/Thermos support.

**Comment by djoveryde** [comment]
ok thankyou.
