### ISSUE TITLE
crash on warez try to join

### ISSUE THREAD

**Issue by Cronosus** [CyberdyneCC/Thermos#405]
Hello
can please someone help me with this?:
-when someone with warez try to join my server (online-mode) and is kicked, server crashing
crash: http://cronos.wz.cz/mc/err/crash-2016-06-15_21.39.15-server.txt
log: http://cronos.wz.cz/mc/err/2016-06-15-3.log

thanks in advance

**Comment by Robotia** [comment]
It seems as though Lantea Craft is at fault.

**Comment by Robotia** [comment]
There has been no response from OP for nearly a month, assuming the issue has been resolved.
