### ISSUE TITLE
Error: Your "CommandSender Link" Has been severed --> Faction 

### ISSUE THREAD

**Issue by FredericFernandes** [CyberdyneCC/Thermos#408]
Hey , I hope you are well !

I tell you when I wish therefore claim with the / f o claim I have an error on the games but nothing on the console.

Faction and massivecraft isversion: 2.7.4.

--> http://hpics.li/eab2fdf

**Thermos Version:*Thermos-1.7.10-1614-56-server*

**Forge Version:*forge-1.7.10-10.13.4.1566-1.7.10-universal*

**Comment by BungeeTheCookie** [comment]
https://github.com/MarkehMe/MassiveCoreForgeFixes

**Comment by FredericFernandes** [comment]
http://pastebin.com/ZtAAeupk

**Comment by BungeeTheCookie** [comment]
Try updating your massivecore to 2.8.5.

**Comment by Time6628** [comment]
Labeled external due to it being a problem with Factions, not Thermos.

**Comment by DraksterAU** [comment]
Close this ticket.

Use Perimeter & MCFF to fix Factions issues on all versions beween 2.8.0 and 2.8.9.
2.8.10+ isn't supported.

For Modded block protection (mostly perfect) : https://www.spigotmc.org/resources/perimeter.22469/
Fixing Critical issues like the one mentioned in this ticket: https://github.com/markehme/massivecoreforgefixes
