### ISSUE TITLE
Opis and Build 57 1614

### ISSUE THREAD

**Issue by Solidflip** [CyberdyneCC/Thermos#409]
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/T8z81Pkt

**Explanation of issue:**
Ticking screen crash when client attempts to load

**How to recreate this issue:**
Start the client running FTB infinity evolved v.2.5.0

**Modpack Name:** *(Only if public)*
FTB Infinity Evolved 2.5.0

**Thermos Version:**
1.7.10-1614-57

This issue only occurs when i attempt to load the client with the MobiusCore fix you have provided with OPIS 1.2.5. Without opis the mobius core is fine...but useless =P

**Comment by Time6628** [comment]
The fix only needs to be on the server.

**Comment by Solidflip** [comment]
Had to step out for a while there sorry....

Ive attempted to do what you said, Ive added the thermos fix to the server. But for the client ive used the normal ones. However no matter what i do i get a ticking screen. I tried:

Mobius-thermos on server + on client
Mobius-thermos on server + regular on client

both ways i get the ticking screen. Any help would be appreciated

**Comment by Robotia** [comment]
Could you give the crash log for that?

**Comment by Solidflip** [comment]
Sure! Its the same (i think) as the last

http://pastebin.com/WBTeef0X

**Comment by Solidflip** [comment]
@Robotia @Time6628  Any ideas?

**Comment by Robotia** [comment]
It seems the map writer mod is at fault. Is this mod necessary?

**Comment by Solidflip** [comment]
Mapwriter no, but opis yes. I tried the mapless version from ftb infinity 2.2 a while back but it didnt work either.

**Comment by Penrouk** [comment]
Does anyone have a mapless version of opis. That might be able to fix it.

**Comment by spannerman79** [comment]
see https://github.com/CyberdyneCC/Thermos/issues/137#issuecomment-241874398
