### ISSUE TITLE
Prism?

### ISSUE THREAD

**Issue by enterprise12nx** [CyberdyneCC/Thermos#410]
Just wondering what version of prism i should use for Thermos, the one i use says it rolls back events but nothing changes

**Comment by KasperFranz** [comment]
In general don't use rollbacks with prism and modded items, talking by experiance :)

**Comment by Time6628** [comment]
http://gogs.tcpr.ca/TCPR/Fixes/src/master/Prism-Cauldron/prism-2.0.3-Cauldron-MC1.7-SNAPSHOT.jar
