### ISSUE TITLE
Non-Vanilla blocks in one world - "You cannot use that item here." [Bug]

### ISSUE THREAD

**Issue by CobaltSparkz** [CyberdyneCC/Thermos#411]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

http://paste.feed-the-beast.com/view/22be2ece

**Explanation of issue:**

Players cannot place any modded blocks in my spawn world, only vanilla. Spawn-protection has been removed completely. I've tested it in other worlds, no issues, only my spawn world. After googling the specific error printout it "appears" to be Thermos (Source: https://git.aperture.lol/projects/TCPR/repos/thermos/browse/patches/net/minecraftforge/event/ForgeEventFactory.java.patch?at=4df81b910d10b686959c27d542818f9e5e134cb1&raw )

**How to recreate this issue:**

No idea, it's only one on world, created with MultiWorld

**Modpack Name:** *(Only if public)*

**Mods Installed:**

RR3 Mainline Pack 3.4.0.2

**Plugins Installed:**

http://prntscr.com/big8xo

**Thermos Version:**

57

**Forge Version:**

1614

Any help is greatly appreciated

Many thanks

Sparkz

**Comment by Time6628** [comment]
```
protection:
  spawn-protect: true
```
set this option to false and it will work.
