### ISSUE TITLE
OPIS 1.2.5 - Mobius Core 1.2.5 Crash on Startup [Thermos Build 57]

### ISSUE THREAD

**Issue by alicheek** [CyberdyneCC/Thermos#412]
Server Log: http://pastebin.com/5Et8tUAL

FML Log: http://pastebin.com/d35rzqEW

Popped in Mobius & Opis 1.2.5 into the mods folder server fails to fully start up

**Comment by Time6628** [comment]
https://github.com/CyberdyneCC/Thermos#known-caveats-use-provided-fixes-at-your-own-risk

**Comment by alicheek** [comment]
Thanks i do apologise for the derp move there! :)
