### ISSUE TITLE
Server Stall

### ISSUE THREAD

**Issue by LeChuuck** [CyberdyneCC/Thermos#414]
**Server Log:** https://gist.github.com/LeChuuck/5da12eb5df982dc94e5a32e3d855fb78

**FML Log(s):** https://gist.github.com/LeChuuck/4bafba0127f05921fa2bb3a8fab6b5d6 , https://gist.github.com/LeChuuck/5360dd279d42e59ed93cbecff3721d3d

**Stall Log:** https://gist.github.com/LeChuuck/3adc3e9dfcfc2a5547bcbadacf96e839

**Explanation of issue:** After a few hours stall reports

**How to recreate this issue:** Don't know or what is causing it

**Modpack Name:** *(Only if public)* FTB Sky Factory 2.5.0

**Mods Installed:** Additional Resources by portablejim
AE2 Stuff by bdew
AppleCore by squeek502
Applied Energistics by AlgorithmX2
Audio Death by portablejim
Automagy by Tuhljin
Baconators by Baijson
Baubles by Azanor
Bdlib by bdew
Better Builder's Wands by portablejim
BiblioCraft by Nuchaz
Big Reactors by Erogenous Beef
Botania by Vazkii
Brandon's Core by brandon3055
bspkrsCore by bspkrs
Carpenter's Blocks by Mineshopper
Chance Cubes by Turkey2349
ChatFlow by Vazkii
ChickenChunks by Chickenbones
Chisel 2 by warlordjones, tterrag1098, TheCricket26, Drullkus
CodeChickenCore by Chickenbones
CodeChickenLib by Chickenbones
CoFH Core by CoFH team
CoFH Lib by CoFH team
Compacter by bdew
ComputerCraft by Dan200
Cooking for Blockheads by BlayTheNinth
Custom Main Menu by Lumien
Custom Things by tterrag1098
DecoCraft by RazzleberryFox
Ding by iChun
Draconic Evolution by brandon3055
Dragon Mounts by BarracudaATA
Dual Hotbar by RebelKeithy
Emotes by Vazkii
Ender Tech by Drayshak
EnderCore by tterrag
EnderIO by CrazyPants
EnderStorage by Chickenbones
Ewy's Workshop by EwyBoy
Ex Astris by LoveHoly
Ex Compressum by Blay09
Ex Nihilo by Erasmus_Crowley
Extra Cells by Leonelf
Extra Utilities by RWTema
ExtraTiC by Glassmaker
Forbidden Magic by SpitefulFox
Forge Multipart by Chickenbones
ForgeAnalytics by TamasHenning
FoxLib by Kihira
FTB Islands by FTB, TheCricket26, Kolatra - Granted
FTB Utilities by LatvianModder
FTBLib by jaredlll08, LatvianModder
Garden of Glass by Vazkii
HarvestCraft by MatrexsVigil, Rhodox
Hat Stand by iChun
Hats by iChun
Headcrumbs by ganymedes01
iChunUtil by iChun
Iguana Tweaks for Tinker's Construct by iguana_man, boni
Immersive Engineering by BluSunrize
Immersive Intergration by Unwritten Fun
Immibis Core by immibis
InfiniBows by Myrathi
InfiniteInvo by Funwayguy
InGame Info by Lunatrius
INpure Core by denoflionsx
Inventory Tweaks by Kobata
IronChests by cpw, progwml6
It's Raining Food by insaneau
JABBA by ProfMobius
JourneyMap by techbrew
KleeSlabs by BlayTheNinth
libsandstone by TrainerGuy22
Loot Bags by Malorolam
Loot++ by Tmtravlr
Lunatrius Core by Lunatrius
Magical Crops by Mark719
Mantle by mDiyo, progwml6
McJtyLib by McJty
MFR Magical Crops Compatibility by portablejim
MineFactory Reloaded by skyboy026, powercrystals
MineTweaker by StanH
MobiusCore by ProfMobius
ModTweaker by jaredlll08, joshie, SpitefulFox
Moo Fluids by TheRoBrit
Morpheus by quetzi
Mouse Tweaks by YaLTeR97
MPUtils by GenDeathrow
Natura by mDiyo
NEI Addons by bdew
NEI Integration by Tonius
NEIlootbags by Gigabit101
Not Enough Items by Chickenbones
Open Peripheral Intergration by OpenMods, boq
OpenBlocks by Mikeemoo, boq
OpenEye by Mikeemoo, boq
OpenModsLib by Mikeemoo, boq
OpenPeripheral Core by Mikeemoo, boq
RanchableFluidCows by JDLogic
RedLogic by immibis
Redstone Arsenal by CoFH team
Resource Loader by Lumien
RFTools by McJty
Sampler by Player - Granted
Simple Achievements by tterrag1098, insaneau
Simple Labels by insaneau, tterrag1098
Simply Jetpacks by Tonius
Slabcraft by Blubbeltasche
Snad by TheRoBrit
Solar Flux by Nauktis
Staircraft by Blubbeltasche
StartingInventory by bspkrs
Steve's Factory Manager by Vswe
Storage Drawers by jaquadro
Sync by iChun
Tabula Rasa by King Lemming
Thaumcraft by Azanor
Thaumcraft Inventory Scanning by BlayTheNinth
Thaumcraft NEI Plugin by DjGiannuzz
Thaumcraft Node Tracker by Dyonovan
Thaumic Energistics by Nividica
Thermal Casting by insaneau
Thermal Dynamics by TeamCoFH
Thermal Expansion by CoFH team
Thermal Foundation by CoFH team
TiC Tooltips by squeek502
TiConAutoToolStation by Blubberbub
Tinker's Construct by boni, mDiyo
Translocators by Chickenbones
Tree Growing Simulator by tterrag1098
Twitchcrumbs by BlayTheNinth
Vein Miner by portablejim
Waila by ProfMobius
Waila Harvestability by squeek502
WAILAPlugins by tterrag
Wawla by Darkhax
Wireless Redstone CBE by Chickenbones
Witchery by Emoniph - Granted
WitherCrumbs by Turkey
YUNoMakeGoodMap by LexManos

**Plugins Installed:** EnjinMinecraftPlugin Essentials GroupManager HolographicDisplays uSkyBlock Vault WorldEdit WorldGuard Votifier

**Warmroast Report:** *(Optional)*

**Thermos Version:** Thermos-1.7.10-1614-57

**Forge Version:** 1.7.10 - 10.13.4.1614

**Comment by Robotia** [comment]
The mod at fault is clear in the stall log: at line 10, the VeinMiner mod.

**Comment by LeChuuck** [comment]
Thank you, iv spent so many hours troubleshooting this, is there anything that can be done or just disable the mod?

**Comment by LeChuuck** [comment]
However i looked in another stall log from a earlier date but i don't see anything about VeinMiner in the log.
https://gist.github.com/LeChuuck/0641b3980b2ab1edc3fb25cdc0adaf99

**Comment by Bogdan-G** [comment]
send stall-report's

**Comment by Bogdan-G** [comment]
assumption: interlocking threads

**Comment by LeChuuck** [comment]
Don't know what that means or what is the cause of it?

**Comment by iKaneki-Ken** [comment]
Long story short, just because the same reason for a server crash doesn't show up every time, doesn't invalidate it as a bug.

As it stands right now, I have 4 different crash reasons that I'm trying to fix myself out of 18 that have shown their face over the last 2 years. A good portion of them have been fixed by Robotia as they were server software exceptions, and a few fixed by myself.

This can be fixed, but you need to know how to code, and you need to learn how the mod is doing what it's doing. If you don't know how to code and don't have the drive to learn Java, your only other options are either to hire a java developer to fix it for you, as the developer of the mod to fix the issue or disabled the mod.
