### ISSUE TITLE
Using Spigot-Only Plugins with Thermos

### ISSUE THREAD

**Issue by Omuck3** [CyberdyneCC/Thermos#415]
Hello.  I just found out about Thermos, and was wondering if plugins that only work for Spigot would work in it.  I'm trying to start a modded "Civilization Server."  The standard mods used in the type, including Citadel, cannot work with Bukkit, and as such they do not work with Cauldron.  Can Thermos alleviate this problem?

**Comment by Time6628** [comment]
Most of Spigot is implemented in Thermos. Spigot is a fork of Bukkit, so most of the plugins made for spigot should work with thermos, unless the plugins use things from future versions of MC.

**Comment by Omuck3** [comment]
Wonderful!  Thanks!  Hopefully it works. :)
