### ISSUE TITLE
Failed to start server, java.lang.NullPointerException at org.bukkit.Bukkit.getLogger

### ISSUE THREAD

**Issue by predme** [CyberdyneCC/Thermos#416]
**Server Log:** *[Github Gist](https://gist.github.com/predme/e67bfda7e1bce98842ece7495e03924a)/*

**FML Log(s):** *[Github Gist](https://gist.github.com/predme/e855b9d723f032e1ec312631f7d6b4be)*

**Explanation of issue:**
The server won't start for some weird unexplainable reason. I haven't made any changes to the server the last 2-3 weeks and suddenly out of nowhere, it refuses to start. No new plugins, no updating of Thermos, nothing. What did work was to restart the physical box the server is running on but that's not a feasible way to solve the problem when it takes no time before this problem occurs again. The server has been running fine ever since I launched it. Last night I encountered this for the first time. One box reboot later, and not even 24 hours later the problem has returned.

**How to recreate this issue:**
Not sure to be honest. I haven't made any changes at all.

**Modpack Name:** *(Only if public)*
FTB Infinity Evolved

**Mods Installed:**
Dynmap

**Plugins Installed:**
ColorName, Lockette, Prism, VanishNoPacket, WorldEdit + custom made plugin by myself.

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Alpha 57

**Forge Version:**
1614

I should probably note that the server starts fine if I use the regular FTB server jar.

**Comment by GRANTSWIM4** [comment]
Can you confirm that it's not your custom plugin? 
` org.bukkit.Bukkit.getLogger(Bukkit.java:311) ~[Bukkit.class:1.7.10-1614.57]`

This tells me it's something to do with Bukkit's Logger, witch you might of used inside your plugin.

**Comment by predme** [comment]
I doubt my custom plugin is the cause as I don't think plugins are loaded that early? It doesn't touch anything related to logging, it only touches chat events. It has worked fine for ages so I'm not sure why it suddenly isn't working anymore

**Comment by Robotia** [comment]
Delete entities.yml

**Comment by GRANTSWIM4** [comment]
@predme In your main class, you might of used it to log the starting of your plugin. Now, I'm not doubuting you, I just want to check all the bases.

**Comment by Robotia** [comment]
Like I said, delete entities.yml so it can regenerate, the error is not from a plugin.

**Comment by GRANTSWIM4** [comment]
Thanks for this tidbit of information @Robotia

**Comment by predme** [comment]
Deleting entities.yml solved it, thank you!
