### ISSUE TITLE
Most bukkit commands should be removed, some of them are already broken

### ISSUE THREAD

**Issue by vizv** [CyberdyneCC/Thermos#418]
**Server Log:**
See: http://pastebin.centos.org/47651

**FML Log(s):**
N/A, not a client issue.

**Explanation of issue:**
Most bukkit commands should be removed, because they are broken (e.g., `/achievement` command).

See https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/ad5a4f5e289e43b8dd36e294380e8f1a5f6a1a91#src/main/java/org/bukkit/command/SimpleCommandMap.java

**How to recreate this issue:**
As op, send command `/achievement give stat.killEntity.Spider`

**Modpack Name:**
N/A

**Mods Installed:**
N/A

**Plugins Installed:**
N/A

**Warmroast Report:** *(Optional)*
N/A

**Thermos Version:**
1.7.10-1614

**Forge Version:**
10.13.4.1614

**Comment by djoveryde** [comment]
Doesn't the /achievement give command require a player or an @p at the end of that. The error is stating its missing additional information?

**Comment by vizv** [comment]
@djoveryde If the player parameter omitted, the sender will be the player.

The error is caused by:

Here `statistic` has a type `ENTITY`,
https://github.com/CyberdyneCC/Thermos-Bukkit/blob/ad9519650b6c3a0cf346b9a78d783221e62d99f9/src/main/java/org/bukkit/command/defaults/AchievementCommand.java#L112-L120

But here `getStatistic()` accepts only `statistic` with type `UNTYPED`,
https://github.com/CyberdyneCC/Thermos/blob/master/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java#L607-L612

**Comment by Robotia** [comment]
If Spigot deleted all these commands, how did they replace them? I do not think we will follow them on this action if there was no replacement...some of these commands are very important to have.

**Comment by Bogdan-G** [comment]
^ fully support

**Comment by vizv** [comment]
@Robotia They replaced with the vanilla command I think, I can confirm the vanilla /achievement works fine. Besides, another option is to only fix the broken /achievement command by change `getStatistic(Statistic)` to `getStatistic(Statistic, Entity)`, haven't tried that but it should work.

https://github.com/CyberdyneCC/Thermos/blob/master/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java#L689-L696

Besides, here also need a fix:
https://github.com/CyberdyneCC/Thermos-Bukkit/blob/ad9519650b6c3a0cf346b9a78d783221e62d99f9/src/main/java/org/bukkit/command/defaults/AchievementCommand.java#L149

Btw, how do I generate a patch? Contribution Guidelines is outdated.

**Comment by fewizz** [comment]
@vizv 
1) fork
2) execute '/scripts/setup.sh'
3) do changes
4) 'gradlew genPatches'
5) push changes

**Comment by vizv** [comment]
I have realized remove most of bukkit commands needs lots of work, so #424 is a fix for the /achievement alone.

**Comment by Bogdan-G** [comment]
@vizv what to do if you need to call a function with one argument or it is not necessary?
_ru-text: что делать если потребуется вызвать функцию с одним аргументом или в этом нет необходимости?_

**Comment by vizv** [comment]
@Bogdan-G I didn't understand your question...
