### ISSUE TITLE
Server Doesn't Stop

### ISSUE THREAD

**Issue by cj89898** [CyberdyneCC/Thermos#419]
**Server Log:** *http://paste.feed-the-beast.com/view/de463726*

**FML Log(s):** *http://paste.feed-the-beast.com/view/b276fe09*

**Explanation of issue:**
Server never actually stops.

**How to recreate this issue:**
No Idea

**Modpack Name:** *(Only if public)*
Project Ozone v1.7.10

**Mods Installed:**
Everything in Project Ozone v1.7.10 + BCLForgeLib (Chunk Loader Stuff)

**Plugins Installed:**
http://pastebin.com/raw/xjNz6npA

**Thermos Version:**
1.7.10-1614-server

**Forge Version:**
I only have the thermos.jar in the server folder

**Comment by spannerman79** [comment]
https://github.com/CyberdyneCC/Thermos/issues/414#issuecomment-228033790

Same issue here

**Comment by cj89898** [comment]
My bad if this was duplicate. I checked that one before posting and it didn't look the same.

**Comment by Time6628** [comment]
Issue with projecte.

**Comment by cj89898** [comment]
So projecte crashes the server. But it never ends up stopping it? Should I report this to the projecte mod creator?

**Comment by Time6628** [comment]
The projectE version that is shipped with Project Ozone, causes the server to loop a method until it stalls.

**Comment by cj89898** [comment]
Okay, do you know if there is a way to prevent it or no?

**Comment by Time6628** [comment]
Yea, you have to change the method yourself.

**Comment by Bogdan-G** [comment]
@cj89898 you can change the config setting such a way that it does not consider them each time you start, and took from json file.

**Comment by Time6628** [comment]
@Bogdan-G You cannot.

**Comment by cj89898** [comment]
Already looked in the configs files. Thanks for trying though! :D
