### ISSUE TITLE
MobiusCore Launch Issue

### ISSUE THREAD

**Issue by Yanniclord** [CyberdyneCC/Thermos#420]
**Server Log:**

http://pastebin.com/tVhQFnJf

**FML Log(s):**

None.

**Explanation of issue:**

Happens when i start my server with the latest version of Thermos (57). Happens if i use MobiusCore (normal) or the KCauldron version of MobiusCore.

**How to recreate this issue:**

Start server with MobiusCore

**Modpack Name:** *(Only if public)*

STARGATE GALAXY (Technic Launcher)

**Mods Installed:**

https://cloud.githubusercontent.com/assets/5807595/13573061/01b9de6c-e47e-11e5-9ebe-c8847b913589.PNG

**Plugins Installed:**

![image](https://cloud.githubusercontent.com/assets/5807595/16366176/35a379ee-3c13-11e6-9c75-f8469b2c1590.png)

**Warmroast Report:** *(Optional)*

**Thermos Version:**

57

**Forge Version:**

1614

**Comment by Time6628** [comment]
Get the thermos version of MobiusCore from here https://github.com/CyberdyneCC/Thermos#known-caveats-use-provided-fixes-at-your-own-risk

**Comment by Yanniclord** [comment]
Ok thanks, will try it later.
