### ISSUE TITLE
Server crashing while running The 1.7.10 Pack modpack

### ISSUE THREAD

**Issue by CyberSquime** [CyberdyneCC/Thermos#421]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/CyberSquime/636e9a02611842497f3386275674504d
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/CyberSquime/55b29ca617f121522a9273ae504934ef
**Explanation of issue:**
Trying to make a 1.7.10 Pack server, but it's crashing, and I don't know why.
**How to recreate this issue:**
Install all 1.7.10 pack mods + Flan's mod addons
**Modpack Name:** *(Only if public)*
The 1.7.10 Pack
**Mods Installed:**
http://technicpack.net/modpack/the-1710-pack.453902/mods
**Plugins Installed:**
None (For now)
**Warmroast Report:** *(Optional)*
None
**Thermos Version:**
Build 57
**Forge Version:**
1614

Note: Right now i'm just running this on my PC and I plan to put it on an Akliz server.

**Comment by spannerman79** [comment]
You cannot run client side only mods on a server. (Liteloader for one)

**Comment by Time6628** [comment]
Client side mods on your server, and invalid configs.

**Comment by CyberSquime** [comment]
Oh... well I feel stupid now. Deleting all of that now.
