### ISSUE TITLE
Crash with Steves Carts

### ISSUE THREAD

**Issue by lilmoefow** [CyberdyneCC/Thermos#425]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Crash log -http://pastebin.com/CmLTaiaP

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Hopefully this is enough of it http://pastebin.com/WY5SCr07

**Explanation of issue:**
Not exactly sure seeing as I am not the one causeing the crash its one of the players on my server.  But from my understanding there is a client crash when a Cart Assembler from Steve's Carts is placed.  When the player logs back on everything is fine and you can use the assembler. Once the assembler is activated to start the production of a cart, the server crashes. 

**How to recreate this issue:**
Explained above

**Modpack Name:** *(Only if public)*
BevosTechPack Beta VNC

**Mods Installed:**
This is the share code we use on ATLauncher for the optional mods.  
Share code  -  Ypvl3lDQ

**Plugins Installed:**
I took a screenshot of the plugins we use on the serever cause im lazy and didnt want to type it all out,
http://imgur.com/60aXxYD

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-1.7.10-1614-server-57

**Forge Version:**
forge-1.7.10-10.13.4.1566-1.7.10-universal

Not actually sure if this is actually an issue you guys can do anything about, or if this is even the right place to report this.

**Comment by Time6628** [comment]
`B:removeErroringEntities=true` & `B:removeErroringTileEntities=true` in forge.cfg.

**Comment by lilmoefow** [comment]
Alright both those config changes are done ( I feel like we used to have that config option set,  must have been overwritten during last update)

Will that allow us to actually use that Cart Assembler now though? or is it just going to remove the cart assembler instead of crashing us now?

**Comment by lilmoefow** [comment]
Alright, so the player still gets kicked from the server, and the cart assembler is duped.  One is placed and one gets thrown out your inventory when you get kicked from server.  You can craft the cart though, but it turns out that the hopper on top of the assembler is what might have been causing the crash. Once a hopper is placed on top of the assembler, and coal is put inside it, the hopper is deleted (presumably by that config change). 

http://pastebin.com/u5QT2nQZ

from looking at the errors there, it seems to be an issue with OpenInv plugin we use trying to access the cart assembler placed? But i am probably wrong.

**Comment by iKaneki-Ken** [comment]
It's not OpenInv, from the looks of it, it's DynMap throwing a "get loaded chunk" error. It might be the hopper trying to injected items into, but the cart assembler rejecting it because it doesn't have valid interfaces.

**Comment by Time6628** [comment]
Bug with steve carts I believe, closing.

**Comment by lilmoefow** [comment]
I ony assumed it might have been a thermos issue, cause Steve's carts has not seen any updates in a while, and we were not encountering this issue on older versions of Thermos.  and the crash log states its something to do with both stevescarts and bukkit.  

Either way, one of the players on our server made a "patch" for us to use server side.   What it does exactly is beyond me.  But it works.

https://github.com/kimfy/Patchr
