### ISSUE TITLE
Project E - Missing Lib

### ISSUE THREAD

**Issue by Tencao** [CyberdyneCC/Thermos#426]
**Server Log:** *http://pastebin.com/4VL6ta7F*

**FML Log(s):** *http://pastebin.com/4VL6ta7F*

**Explanation of issue:** When using an item from the project e mod, it crashes due to a missing library that is present in forge, but missing in thermos.

**How to recreate this issue:** Use the archangel ring from the mod

**Mods Installed:** Project E

**Thermos Version:** Build 57

**Forge Version:** 1614

**Comment by Eufranio** [comment]
Sooooooo my crash is thermos fault? God

**Comment by Eufranio** [comment]
I crashed too, same problem. https://github.com/sinkillerj/ProjectE/issues/1277

**Comment by Tencao** [comment]
Yes, I was speaking with the developer of ProjectE last night, and he explained to me that thermos is missing this required lib that forge comes with.

**Comment by Time6628** [comment]
Fixed.
