### ISSUE TITLE
Thermos don't support NMS

### ISSUE THREAD

**Issue by manercraft** [CyberdyneCC/Thermos#429]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:** Thermos don't support NMS

**How to recreate this issue:** Just use NMS in any plugins

**Mods Installed:** 0

**Plugins Installed:** FancyTab

**Warmroast Report:** *(Optional)* https://gyazo.com/a7d8d2a6972d1f2757b52b8fac924fb8.png

**Thermos Version:** Last (Thermos-1.7.10-1614-server.jar Alpha 57)

**Forge Version:** Vanilla client (0 mods)

I know, Cauldron and KCauldron doesn't support NMS, but please:
Is it possible to see the NMS in a future release?

**Comment by spannerman79** [comment]
Short answer - No.

Cauldron and its forks have always had *limited* support for mods and plugins.  Thats the cost of running any cauldron based fork.  You cannot have everything.

If you want a perfect server to run plugins perfectly you will need to use Spigot.  If you want a server to run server to run forge mods perfectly you need to run a vanilla forge server.

You cannot have the best of both worlds when it comes to cauldron.

If you think thats wrong then move to Sponge.

**Comment by Robotia** [comment]
Hi,

It has already been started in previous closed issues that we will not be supporting these plugins, as they use the Java Reflection Api unnecessarily thus creating these problems.

As Spanner Man said, we aim for high compatibility but we can't support everything.

**Comment by MarkehMe** [comment]
Just as a follow up Thermos **does** support nms. You just need to add your own mixin for Thermos/forge as the package is different. 

I haven't found a jar yet with full references that I can read through but this is just from reading the references in [mappings.zip](https://github.com/CyberdyneCC/Thermos/blob/master/src/main/mappings.zip).

eg, you use ```net.minecraft.world.World``` instead of ```net.minecraft.server.v1_7_R4.World```
