### ISSUE TITLE
Disconnected on Server chat 

### ISSUE THREAD

**Issue by ajisfree** [CyberdyneCC/Thermos#430]
**Server Log:** *05.07 11:26:41 [Disconnect] User [11:26:41 INFO]: ajisfree has disconnected, reason: Internal Exception: java.lang.ArrayIndexOutOfBoundsException: -1*

This is all that shows in the log.

**FML Log(s):** **

**Explanation of issue:**

**How to recreate this issue:*Login on thermos server 1.7.10-1614 and try and send a chat message.*

**Modpack Name:** *The 1.7.10 modpack on Technic*

**Mods Installed:Too many to list**

**Plugins Installed:*Essentials, Vault, World Guard* Tried removing all plugins as well but got the same result

**Warmroast Report:** *(Optional)*

**Thermos Version:*thermos server 1.7.10-1614*

**Forge Version:*1.7.10.1614*

**Comment by Time6628** [comment]
You most likely have a client side mod on the server or some mod that changes the chat.

**Comment by clienthax** [comment]
This is caused by the colorchat mod, i havn't got around to seeing exactly why it breaks it yet.

**Comment by ajisfree** [comment]
The 1.7.10 modpack does not use Color Chat mod. The only chat mod i have found is the tabby chat which I disabled but still had the same issue

**Comment by spannerman79** [comment]
TabbyChat (litemod or forge) isn't the issue as both are client side only.

I am on mobile at the moment so you'll have to go through and check to see what mod that's in the server pack that affects client<->server chat

**Comment by Time6628** [comment]
Chat Bubbles maybe?

**Comment by clienthax** [comment]
@ajisfree you are wrong, it does have the mod
