### ISSUE TITLE
Server with TerraFirmaCraft crashes when player joins

### ISSUE THREAD

**Issue by MegaFlary** [CyberdyneCC/Thermos#431]
**Server Log:**
http://pastebin.com/SThrWCd0

**Explanation of issue:**
Server crashes when player joins.

**How to recreate this issue:**
Requires build 54 or newer. Install latest TerraFirmaCraft, connect to server.

**Mods Installed:**
TerraFirmaCraft 0.79.29

**Plugins Installed:**
No plugins.

**Thermos Version:**
Build 54, 55, 56, 57.

**Forge Version:**
1558 / 1614.

**Comment by Time6628** [comment]
This is due to ASM on TerraFC's side. Marking external.

**Comment by MegaFlary** [comment]
Build 53 - works great.

**Comment by MegaFlary** [comment]
Ok, I fixed it myself.

**Comment by spannerman79** [comment]
For the record and for searches - what was your method to fix @MegaFlary ?

**Comment by MegaFlary** [comment]
You should increase offset by 13 here: https://github.com/Deadrik/TFCraft/blob/master/src/ASM/com/bioxx/tfc/ASM/Transform/TF_EntityPlayerMP.java#L22
For example, "59" will be "72".
