### ISSUE TITLE
Server will not start ([main/FATAL]: Failed to start the minecraft server java.lang.NullPointerException)

### ISSUE THREAD

**Issue by Porkchopseesu2** [CyberdyneCC/Thermos#432]
**Server Log:** *http://pastebin.com/UmTVvzfL
---------------------------------------
**FMyLife Log(s):** *http://pastebin.com/A4P2e9Kb
---------------------------------------
**Explanation of issue:**
 When launching my server it will not start up. I was having similar issue on cauldron so I switched to Thermos and it started as normal but has crashed a lot in the last few days. Today it is seeing the same issue as it will now not start.
---------------------------------------
**How to recreate this issue:**
 Try to start my server .
---------------------------------------
**Modpack Name:** *(Only if public)*
  Pixelmon
---------------------------------------
**Mods Installed:**
pixelmon 1.7.10
**Plugins Installed:**
AutoMessage
Buycraftx
*Custom Swear blocker
CoreProtect.jar
Essentials.jar
EssentialsAntiBuild.jar
Essentiakchatjar
EssentialsSpawn.jar
GAlistener.jar
GrefPrevention,jar
HideStream.jar
HolographicDisplays.jar
OpenInvjar
PixelmonCloud.jar
PlayerVautts.jar
ProtocolLib.jar
VauIt.jar
Votifier.jar
VoxeIsniper.jar
worldedit- bukkit-6.1 2.jar
worldGuard,jar
zPermnissions.jar
---------------------------------------
**Warmroast Report:** *(Optional)*
 not sure where to locate this. 
---------------------------------------
**Thermos Version:**
Thermos-1.7.10-1614-server.jar
---------------------------------------
**Forge Version:**
  Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10

**Comment by Time6628** [comment]
Delete entities.yml.

**Comment by Porkchopseesu2** [comment]
I removed that but the server will still not start

**Comment by Time6628** [comment]
Nevermind, delete cauldron.yml.

**Comment by Porkchopseesu2** [comment]
This is what I have in my main directory https://gyazo.com/f84cf0c0d85be767898a5bebcb3eb032 .
I do not have a cauldron.yml

**Comment by Porkchopseesu2** [comment]
Woot Woot that did it! Thanks so much.
