### ISSUE TITLE
Client can't enter the server after installing Forestry

### ISSUE THREAD

**Issue by Lambda-incraft** [CyberdyneCC/Thermos#436]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/Lambda-incraft/7eb34bcc1ddcf5e3b51ca754ba5da1b6
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/Lambda-incraft/3cfa16d115f633bd2587b3b8fddca170
**Explanation of issue:**
Client can't enter the server after installing Forestry 4.2.14.62.Client reports Fatally missing blocks and items
**How to recreate this issue:**
Install forestry on both client and server side, try to enter the server with the client
**Mods Installed:**
gregtech@MC1710,MineFactoryReloaded|CompatForgeMicroblock@1.7.10R2.8.0,DynamicLights_dropItems@1.0.8,BuildCraft|Robotics@7.0.19,AS_UpdateCheck@1.1.6,DynamicLights_flameArrows@1.0.0,BiblioCraft@1.10.5,MineFactoryReloaded|CompatRailcraft@1.7.10R2.8.0,MineFactoryRe
loaded|CompatMystcraft@1.7.10R2.8.0,TwilightForest@2.3.5,BuildCraft|Transport@7.
0.19,WailaHarvestability@1.1.2,mcp@9.05,RotaryCraft@1.0,NEIAddons|Forestry@1.12.
10.33,DynamicLights_otherPlayers@1.0.8,NEIAddons|CraftingTables@1.12.10.33,NEIAd
dons|ExNihilo@1.12.10.33,DamageIndicatorsMod@3.2.3,InputFix@1.7.10-v5,Forestry@4
.2.14.62,TConstruct@1.7.10-1.6.0.build611,FastCraft@1.21,<CoFH ASM>@000,<DragonA
PI ASM>@0,MineFactoryReloaded|CompatAtum@1.7.10R2.8.0,appliedenergistics2@rv2-st
able-8,DragonAPI@1.0,CodeChickenCore@1.0.7.46,MineFactoryReloaded|CompatThermalE
xpansion@1.7.10R2.8.0,BuildCraft|Energy@7.0.19,Railcraft@9.7.0.0,appliedenergist
ics2-core@rv2-stable-8,ThermalDynamics@1.7.10R1.1.0,NEIAddons@1.12.10.33,Dynamic
Lights_entityClasses@1.0.1,DynamicLights@1.3.8,Waila@1.5.10,CoFHCore@1.7.10R3.0.
3,MineFactoryReloaded|CompatAppliedEnergistics@1.7.10R2.8.0,Mineshot@v1.61-1.7.1
0,MineFactoryReloaded@1.7.10R2.8.0,journeymap@5.1.4p1,uniskinmod@1.2-dev4,Therma
lExpansion@1.7.10R4.0.3B1,ProfilerEvents@1.0,ArmorStatusHUD@1.28,MineFactoryRelo
aded|CompatBackTools@1.7.10R2.8.0,MineFactoryReloaded|CompatProjRed@1.7.10R2.8.0
,inventorytweaks@1.59-dev-152-cf6e263,DynamicLights_onFire@1.0.4,BuildCraft|Sili
con@7.0.19,MineFactoryReloaded|CompatIC2@1.7.10R2.8.0,DynamicLights_mobEquipment
@1.0.8,MineFactoryReloaded|CompatVanilla@1.7.10R2.8.0,NEIAddons|AppEng@1.12.10.3
3,MineFactoryReloaded|CompatThaumcraft@1.7.10R2.8.0,FML@7.10.99.99,BuildCraft|Co
re@7.0.19,NEIAddons|Botany@1.12.10.33,NotEnoughItems@1.0.5.120,MouseTweaks@2.4.4
,IC2@2.2.749-experimental,MineFactoryReloaded|CompatExtraBiomes@1.7.10R2.8.0,nei
integration@1.1.2,Mantle@1.7.10-0.3.1.jenkins180,LunatriusCore@1.1.2.21,DynamicL
ights_creepers@1.0.4,MineFactoryReloaded|CompatChococraft@1.7.10R2.8.0,DynamicLi
ghts_thePlayer@1.1.4,DynamicLights_floodLights@1.0.2,MineFactoryReloaded|CompatT
wilightForest@1.7.10R2.8.0,BuildCraft|Factory@7.0.19,Forge@10.13.4.1614,MineTwea
ker3@3.0.10,BigReactors@0.4.3A,MineFactoryReloaded|CompatBuildCraft@1.7.10R2.8.0
,bspkrsCore@6.16,MineFactoryReloaded|CompatForestry@1.7.10R2.8.0,OpenEye@0.6,Min
eFactoryReloaded|CompatSufficientBiomes@1.7.10R2.8.0,BuildCraft|Builders@7.0.19,
MineFactoryReloaded|CompatTConstruct@1.7.10R2.8.0,ThermalFoundation@1.7.10R1.2.0
**Plugins Installed:**
Essentials
**Thermos Version:**
Build 57,also tried build 56
**Forge Version:**
1614

**Comment by spannerman79** [comment]
Server <-> client configuration mismatch.

This is not a thermos issue

**Comment by Lambda-incraft** [comment]
I'm sure I installed the same mods except the singleplayer mods.
If forestry is removed on both side,it'll be okay.
so what's the problem exactly?

**Comment by DiggyWig** [comment]
"Failed to connect to server: there are 8 missing blocks and items"

In other words you have some blocks/items enabled on one side (client/server) but not the other, so as spannerman79 said it's a configuration mismatch.

**Comment by Lambda-incraft** [comment]
I tried to copy the mods and/or config folder to one another and give it another shot,but none of them worked.

**Comment by Lambda-incraft** [comment]
I even tried delete the config folder on both side,no use either.

**Comment by spannerman79** [comment]
Next time let your fingers do some searching before opening non-issues

http://lmgtfy.com/?q=missing+blocks+and+items+forge&l=1

**Comment by Lambda-incraft** [comment]
Ahh...I'm in China and can't use Google easily.And I can't open your link.
Chinese local search engines are always giving me freaking nonsense——none of them worked.
I'm sure I have the same config and forestry version on both sides.

**Comment by Time6628** [comment]
```
[18:14:29] [Netty Client IO #0/INFO]: Found a missing id from the world Forestry:fluid.milk
[18:14:29] [Netty Client IO #0/INFO]: Found a missing id from the world Forestry:canOil
[18:14:29] [Netty Client IO #0/INFO]: Found a missing id from the world Forestry:refractoryFuel
[18:14:29] [Netty Client IO #0/INFO]: Found a missing id from the world Forestry:canFuel
[18:14:29] [Netty Client IO #0/INFO]: Found a missing id from the world Forestry:fluid.milk
[18:14:29] [Netty Client IO #0/INFO]: Found a missing id from the world Forestry:waxCapsuleFuel
[18:14:29] [Netty Client IO #0/INFO]: Found a missing id from the world Forestry:waxCapsuleOil
[18:14:29] [Netty Client IO #0/INFO]: Found a missing id from the world Forestry:refractoryOil
```

**Comment by Lambda-incraft** [comment]
how to solve it？I know the problem is here.how to get the missing id to work？

**Comment by Time6628** [comment]
You need to make sure the client configs/items are the same as the server.

**Comment by Lambda-incraft** [comment]
they ARE the same，I checked them twice before I opened this issue

**Comment by Lambda-incraft** [comment]
i even copied the whole config folder to each other，it didn't work
