### ISSUE TITLE
Books meta don't change

### ISSUE THREAD

**Issue by TheNickSkater** [CyberdyneCC/Thermos#437]
**Server Log:** _(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))_

**FML Log(s):** _(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))_

**Explanation of issue: You cant edit books :/, if you write something in an press done, it wont change anything. Also with the button sign, the book wont get signed.

**How to recreate this issue:**

**Modpack Name:** _(Only if public)_ "onTechBuild"

**Mods Installed:**

**Plugins Installed:**

**Warmroast Report:** _(Optional)_

**Thermos Version:** 54

**Forge Version:** 1614

**Comment by Bogdan-G** [comment]
you test 55-57 version server?

**Comment by enarkay** [comment]
I am also experiencing this issue, and I am on version 57 with forge version 1614.

**Comment by KasperFranz** [comment]
Still seems to be a issue on 58

**Comment by braunly** [comment]
Please, reopen Issue. Book and quill not working on 58.

**Comment by Robotia** [comment]
It seems what I changed didn't fix it, I am planning on spending this Thursday reiterating over the commits (it is a day off for me).

Il me semble que ce que j'ai changé n'a marché pas. Ce jeudi je vais réitérer sur les commits (c'est un jour férié pour moi).

**Comment by Proplex** [comment]
Any progress on this bug? Just had a few players learn the hard way that books weren't saving.

**Comment by insyder1201** [comment]
This still doesn't work on 59 with forge 1614.

**Comment by vediis** [comment]
sameer, would love if you could fix this feature, or have a way to disable this AllUWant protection. Have you considered opening a patreon or paypal donations for your work on Thermos? Many modded servers are still running on 1.7.10 due to mods not updating.

**Comment by vediis** [comment]
@enarkay @TheNickSkater @insyder1201 Have any of you found a fix for this?

**Comment by enarkay** [comment]
@vedisdragon No not really, I've just given up on thermos and went back to (k)cauldron :(

**Comment by vediis** [comment]
Damn, I would hate to go back to KCauldron. Charm of Keeping III and other keepinv items won't work there and Thermos is better for anti griefing because it does Bukkit > Forge.
@enarkay Have you found any fixes for those issues in KCauldron? Also, have there been other major Thermos bugs that made you switch back to KCauldron?

**Comment by enarkay** [comment]
@vedisdragon It's been quite some time so I honestly don't remember, but in addition to the book and quill thing I believe I didn't really experience the allegedly 'better' compatibility with plugins either.

So I've just given up all hope and am awaiting for active use/development of sponge plugins, and in the meantime I hire developers to fix desired plugins to be compatible with cauldron or even make a custom plugin if necessary. That DMCA just bombarded the bridge between forge and bukkit.. I really hate how the roads have separated now and sponge and spigot are each going their own way - such an inefficient and horrible environment for server owners and players if you ask me :(

**Comment by vediis** [comment]
What forum do you use to hire developers? That seems like something I'd be interested in as Thermos is dead. Switching my server back to Cauldron soon. :(

**Comment by enarkay** [comment]
I use the spigot forum for hiring developers but you should note that not many developers are confident or competent when it comes to making plugins for a cauldron server and not a bukkit server. So you might wanna try and contact a developer I always contact for plugins compatible with a cauldron server - his skype is gyurixdev.

**Comment by vediis** [comment]
Many thanks!

**Comment by Bogdan-G** [comment]
>I've just given up on thermos and went back to (k)cauldron :(

here is another fork kcauldron - ffokc, just another variant, the project is not dead in contrast to the other two (not very true it is clear that with KC, because there was no sign(there was no announcement of this, kind of, or i have not seen him) that died)

**Comment by insyder1201** [comment]
@vedisdragon what version of Java are you running? I think I changed from OpenJDK to OracleJDK and pretty much everything in thermos that didn't work for me started working, but it was a while ago so I don't remember it very well.

**Comment by vediis** [comment]
@insyder1201 Did you find that worked better for you than using Cauldron?
I'm using a host and set my server up entirely with FileZilla. Listen my dude, I don't know anything about Java. ;v; I'm learning more every day. If you could perhaps link me a guide for dummies that would be much appreciated!

**Comment by vediis** [comment]
@Bogdan-G 
Hm - is this considered stable enough to use on a server? I need a version that supports Forge 1.7.10 10.13.4.1558

**Comment by vediis** [comment]
@enarkay What version of Cauldron are you using? Could you perhaps provide a link? I was on Cauldron-Reloaded-1.7.10-1.1291.01.0 but I believe the Forge version isn't up to date with 1558, so I had newer mods that wouldn't work.

**Comment by insyder1201** [comment]
@vedisdragon I used Thermos because of its bug fixes, and didn't use Cauldron much. Also, if you are using a host then they, in my opinion, would be using Oracle JDK because some mods don't like OpenJDK. JDK is the Java Development Kit, which contains the JVM(Java Virtual Machine) used to run Java programs like .jar files. Oracle JDK is made by Oracle, the owners of Java, but it has some proprietary code so Linux distributions doesn't include it in their repositories and you'd need to install it from the Java website or a user repository instead. OpenJDK, on the other hand, is an open source JDK and so it is included in nearly all Linux distributions's repositories. It is easier to install on Linux so people often install OpenJDK but this can cause some errors in mods that no matter how you look at them seem like actual bugs in the mod, not just a misconfiguration(as is usually true). People post these bugs on the internet and nearly all of them could be fixed by switching to the Oracle JDK.
But the problem for you seems different if you are using a host. If the host you are using has any repute and isn't just a small one that is really cheap and doesn't know what they are doing, then they most likely are using Oracle JDK already, or their clients don't usually use 1.7.10 modded servers.

**Comment by vediis** [comment]
@insyder1201 I'm using Fadehost, I can ask support what they're using.
Did Thermos ever fix the bug with the book and quill? So far from using Thermos I've noticed that it fixes Forge>Bukkit griefing issues, modded keepinventory items, and it breaks book/quill, witchery added strength feature, custom entities from McMMO/Bukkit, and causes more lag. Also had issues with chunks generating and crashing the server after switching over to Thermos from Cauldron. Not sure what to do at this point, currently waiting for enarkay to recommend a version of Cauldron.

**Comment by insyder1201** [comment]
@vedisdragon If you have tried the latest working version and you still have that problem then I suggest you give up on books and quills. You may have noticed the "NO LONGER DEVELOPED" on the github page of Thermos, so if it doesn't work then nobody is going to fix it, and you'd have to find an alternative.

**Comment by Bogdan-G** [comment]
@vedisdragon 
>Hm - is this considered stable enough to use on a server? I need a version that supports Forge 1.7.10 10.13.4.1558

Why do you need 1558? core and there is a server, or are you talking about? If you are at all about this core, then there is stability, but it depends on the hands of the person the same way.

@insyder1201 
> It is easier to install on Linux so people often install OpenJDK but this can cause some errors in mods that no matter how you look at them seem like actual bugs in the mod, not just a misconfiguration(as is usually true). People post these bugs on the internet and nearly all of them could be fixed by switching to the Oracle JDK.

:confused:  I observe more stability and fewer memory leaks when using OpenJDK than OracleJDK, if you do lacks to lib JavaFX, include him in classpatch.

**Comment by Time6628** [comment]
The book and quill will not be fixed.
Almost all developers use OracleJDK over OpenJDK, so OracleJDK would be your best bet. If you have problems with OracleJDK, it's probably your fault.
