### ISSUE TITLE
[WorldEdit (Forge)] error

### ISSUE THREAD

**Issue by newMySQL** [CyberdyneCC/Thermos#438]
Refuses to work WordEdit Forge Version 6.1.1 , but Version 6.0 works fine .
Error: http://pastebin.com/wbiyFmat
WorldEdit: 6.1.1 http://minecraft.curseforge.com/projects/worldedit/files
Thermos: Build 57
Forge: 1614

**Comment by Time6628** [comment]
World edit forge 6.1.1 is for 1.8.9.

**Comment by djoveryde** [comment]
There is a 6.1 version of worldedit (bukkit) but forge version is only 6.0. Always wise to look at what mc version it requires before posting. There won't be any other version unless it's game breaking, they are working on 1.8/1.9 only that I'm aware of

**Comment by Time6628** [comment]
Actually, here's the 1.7.10 build of WE 6.1.2 for forge and various other versions. http://builds.enginehub.org/job/worldedit/9194

**Comment by newMySQL** [comment]
But why, then, there is a version Show Ignored Content 6.1.1 to 1.7.10? http://minecraft.curseforge.com/projects/worldedit/files/2309699

------------------------------------------------------------------------------------------

Established worldedit-forge-mc1.7.10-6.1.2-SNAPSHOT-dist.jar Http://builds.enginehub.org/job/worldedit/9194 of links and a similar error when you run .

**Comment by Time6628** [comment]
Dunno.

**Comment by newMySQL** [comment]
And if you use vanilla + forge Server Core , then everything is fine start.

**Comment by spannerman79** [comment]
To correctly use worledit on a cauldron (or its forks) server you need **both** worldedit plugin and mod on the server.

**Comment by newMySQL** [comment]
I and so worth the plugin (v6.1) and mod (v6.0), but I really want to mod v6.1 as there is added support for multipart

**Comment by Time6628** [comment]
You nee the bukkit 6.1 version and the Forge 6.1 version.

**Comment by newMySQL** [comment]
Time6628, yes. plugin version , and so I have is 6.1. mod and I can not seem to install version 6.1 or higher
