### ISSUE TITLE
People still can't login in Thermos server

### ISSUE THREAD

**Issue by lightning02** [CyberdyneCC/Thermos#439]
**Server Log:** https://www.dropbox.com/s/yqddtq1eaexzh69/latest.log?dl=0

**FML Log(s):** https://www.dropbox.com/s/iin5rajczeeif7f/fml-server-latest.log?dl=0

**Explanation of issue:** The client and the server side are synched (except for client side mods naturally), when people try to join in the server, however, the server crash and close, while the client doesn't have any problem.
I've tryed with both thermos build 55 and 57 and the issue is the same.
I've also tryed with a 1.7.10 normal forge server, it works without any problem.
http://imgur.com/a/3QvJZ

**How to recreate this issue:** To reproduce, I guess you can just use the same mods and eventually track it down...

**Mods Installed:** http://pastebin.com/ZT3UxCHP

**Plugins Installed:** No plugins installed

**Warmroast Report:** 

**Thermos Version:** build 55 and build 77 (tried both)

**Forge Version:** (1.7.10-1614)

I've downloaded the tfc master at github, then modified the file TF_EntityPlayerMP as you suggested in the other thread-issue and finally built all in a new jar with the express .bat file in the master folder (a friend helped me with that btw)..
In the end I've replaced the new jar and tryed again.
The result is that the server no longer crash when people try to log-in, but they aren't able to log-in... this doesn't occur on normal forge server, only with thermos, and even with build 53...
Any other suggestion? :/
I re-open the issue since isn't solved atm
here are the logs
https://www.dropbox.com/s/2na9bclho1apw6y/fml-server-latest.log?dl=0
https://www.dropbox.com/s/dkci79rfd8n63wd/latest.log?dl=0
http://i.imgur.com/lzL3jIr.png?1

**Comment by Robotia** [comment]
Add "--noverify" to your server start arguments please

**Comment by lightning02** [comment]
I add that after -log-strip-color, right?
I added that in the start.bat but the problem persist.. I guess the syntax is correct, you check it here and tell me if I'm wrong eventually;
http://i.imgur.com/JpaJo5W.png?1

this is the new fml latest log, idk if something changed
https://www.dropbox.com/s/bailqqirahi58vd/latest.log?dl=0
https://www.dropbox.com/s/1yff0bg42cw1ytl/fml-server-latest.log?dl=0

sometime the connection is forcely closed by the server, sometimes it keep sayng Loggin in... and never resolve the connection (this probably because I've set connection throttle to -1) it just can't make you log-in for some reason

**Comment by Robotia** [comment]
The no verify argument should be put right after java, does the log end up being the same?

**Comment by lightning02** [comment]
Thanks god you exist Robotia.
With the no verify argument added correctly now it works! 
But some precisation for people that may will look into this thread in the future I have to notify: this argument seems doesn't work with the modified version of Terrafirmacraft; you have to use the original one with the original PlayerMP values (and this is good), if you use the modified version of tfc as in #431 the server will not even load and will crash on the beginning.
Thanks again Robotia btw :)

**Comment by Robotia** [comment]
No problem!
