### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.World.func_72827_u()Ljava/lang/String;

### ISSUE THREAD

**Issue by clienthax** [CyberdyneCC/Thermos#441]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.ubuntu.com/19137426/

Crash report
http://pastebin.ubuntu.com/19137612/

**Explanation of issue:**
See stack trace

**How to recreate this issue:**
Seems to trigger from world gen

**Modpack Name:** *(Only if public)*
1.7.10 pack

**Plugins Installed:**
Plugins (19): MultiWorld, WorldEdit, Essentials, EssentialsChat, PermissionsEx, GlobalMarket, TuxTwoLib, WorldBorder, BuycraftX, Vault, Votifier, EssentialsSpawn, ItemRestrict, WorldGuard, ProtocolLib, MultiInv, RandomTP, HolographicDisplays, GAListener

**Thermos Version:**
1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.57 (MC: 1.7.10)

**Comment by Time6628** [comment]
You have a mod on the server that is calling a client side method.

**Comment by Robotia** [comment]
As Time noted, closing issue.

**Comment by clienthax** [comment]
@Time6628 @Robotia Turns out you was right, but its thermos thats actually doing it -.-
    public void decorateChunk(World p_150512_1_, Random p_150512_2_, BiomeGenBase p_150512_3_, int p_150512_4_, int p_150512_5_)
    {
      int ct = 0;
      while(decorateLock.isLocked())
      {
          try { Thread.sleep(100L); } catch(Exception e) {} finally { ct++; }
          if(ct > 100 ) { throw new RuntimeException("Generating a chunk in world " + this.currentWorld.getProviderName() + " took longer than 10 seconds, Thermos needs to crash so the server doesn't time out...sorry!"); } // Thermos - Decoration took too long, we'll have to crash the server at this point so it doesn't hang.
      }

**Comment by LemADEC** [comment]
Issue is still reproduced on build 57
