### ISSUE TITLE
Thermos server simply doesn't launch.

### ISSUE THREAD

**Issue by popatop15** [CyberdyneCC/Thermos#443]
Logs...
There is absolutely no output to console and only blank log files are saved.

Issue:
When I start the server using a java command, it simply stops without logging anything. This is particularly confusing because my server has been running for weeks now with no interruption.

Recreate?:
I'm stumped on trying to recreate the issue. I suppose if I really wanted to fix this I might could just make a new server and use a new jar, but that would take a little time and effort that I don't have atm. Besides, if this is a bug, I would like you guys to know. 

Modpack:
I'm using Direwolf20 1.10.0

Plugins:
Basic plugins. Essentials, World Edit, World Guard, Prism.

Thermos:
Thermos-1.7.10-1558-57-server.jar

Forge:
1558

**Comment by popatop15** [comment]
BTW the java command I am using is the one that is in the installation instructions. I have played around a little more trying to get it to work. My server is really low on disk space, so if it can't run with 2.8GB of available storage then that might be the problem, working on that now. However, I don't think that is the issue. I have tried replacing the jar and nothing happened. It just launches and stops without logging a single thing to the console. All I see is restarting text from my launch script.

**Comment by popatop15** [comment]
Even updating the jar file to the latest 1614 version (a version that shouldn't be compatible with my version of forge) doesn't log anything.

**Comment by Time6628** [comment]
Did you upload the libraries?

**Comment by popatop15** [comment]
Yes, like I said above, it has been running fine for weeks until now. Plus, would it not tell me that it was missing the libraries?

**Comment by popatop15** [comment]
I think it might be disk space causing this issue, but if you have any suggestions on what I can try it would be much appreciated.

**Comment by Time6628** [comment]
Have you used all your diskspace?

**Comment by popatop15** [comment]
If you read my first comment, I have 2.8GB free. Not a lot, but shouldn't it be enough to at least start the server? I really just don't want to be told to get a new hard drive and then the topic closed unless you know for sure the disk space is the issue.

**Comment by Time6628** [comment]
Can you send me the latest.log?

**Comment by Time6628** [comment]
Does the server have permissions to read and write in the server directories?

**Comment by popatop15** [comment]
Yes, the user I used to execute the jar owned all of the files in the directory and had R/W permission.
The last log before everything broke:
https://gist.github.com/popatop15/342467b368e7d8a30dd1d4ff78928e8e

**Comment by popatop15** [comment]
this it is important to note that the latest log file that I just sent contains information regarding Thermos 1614 when I tried to swap out the jars. The latest.log is blank when I try to launch the 1558 version.

**Comment by Time6628** [comment]
Delete tileentities.yml.
