### ISSUE TITLE
Thermos 1.8/1.9

### ISSUE THREAD

**Issue by checkplys** [CyberdyneCC/Thermos#444]
When will thermos for 1.8 or 1.9 be released? Currently there's no way to install mods & plugins in a 1.8 or 1.9 server.

**Comment by BobGamingHD** [comment]
I agree with this, people say about sponge but it doesn't implement spigot or bukkit and the plugin list is very short at the moment. A version for 1.8/1.9 would be brilliant.

**Comment by Eufranio** [comment]
Lunchbox is in progress.

**Comment by Time6628** [comment]
LunchBox will be a Forge mod that implements the Bukkit API. No ETA on when it will be released.
https://github.com/CyberdyneCC/LunchBox
