### ISSUE TITLE
[Mod] Mine & Blade: Battlegear 2

### ISSUE THREAD

**Issue by FredericFernandes** [CyberdyneCC/Thermos#446]
Hello with you! Then I have a problem with the MOD Mines & Blade: Battlegear 2 which allows added Weapons two hands and other, however on Thermos flask we do not see the weapons on the 2nd hands of a player what poses problem! This bug not being present on Cauldron I think that it is about a class which he does not find or who is hidden. And of course there is no error message on the console.

If ever somebody would have a solution 

forge-1.7.10-10.13.4.1566-1.7.10-universal
Thermos-1.7.10-1492-57-server
minecraft_server.1.7.10

**Comment by iKaneki-Ken** [comment]
I read "Hello with you!" as "Hell with you!" initially.

Anyway, we need more than the information posted here. We need a full list of mods and plugins that you utilize in order to properly help you further.

**Comment by Robotia** [comment]
Not enough information and no response from OP. Assuming resolved or no longer an issue.
