### ISSUE TITLE
ModSortingException: There was a cycle detected in the input graph, sorting is not possible

### ISSUE THREAD

**Issue by BlayzerQ** [CyberdyneCC/Thermos#447]
When i install GregTech 6, i get this crash. 

---- Minecraft Crash Report ----
// There are four lights!

Time: 14/07/16 17:35
Description: Exception in server tick loop

cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190)
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199)
	at cpw.mods.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145)
	at cpw.mods.fml.common.toposort.ModSorter.sort(ModSorter.java:133)
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:272)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.57
	Plugins: ~~ERROR~~ NullPointerException: null
	Disabled Plugins: ~~ERROR~~ NullPointerException: null
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 700262688 bytes (667 MB) / 1056309248 bytes (1007 MB) up to 2130051072 bytes (2031 MB)
	JVM Flags: 8 total; -Xmx2048M -Xms1024M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -Xincgc
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 83 mods loaded, 184 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{7.10.99.99} [Forge Mod Loader] (Thermos.jar) 
	U	Forge{10.13.4.1614} [Minecraft Forge] (Thermos.jar) 
	U	kimagine{0.2} [KImagine] (minecraft.jar) 
	U	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	U	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	U	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	U	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	U	OpenComputers|Core{1.5.19.37} [OpenComputers (Core)] (minecraft.jar) 
	U	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	U	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	U	ae2stuff{0.5.1.9} [AE2 Stuff] (ae2stuff-rv3-0.5.1.9-mc1.7.10.jar) 
	U	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
	U	aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar) 
	U	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	U	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	U	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	U	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
	U	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
	U	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
	U	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
	U	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
	U	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (carpentersblocks_server.jar) 
	U	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	U	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	U	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) 
	U	DragonsRadioMod{1.7.1} [Dragon's Radio Mod] (Dragon's Radio Mod-MC1.7.10-1.7.1.jar) 
	U	Emotes{1.0} [Emotes] (Emotes 1.0.1.jar) 
	U	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.31_beta.jar) 
	U	EnderIO{1.7.10-2.3.0.425_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.425_beta.jar) 
	U	EventHelper{1.4} [EventHelper] (EventHelper-1.4.jar) 
	U	exastris{MC1.7.10-1.16-36} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-36.jar) 
	U	exnihilo{1.38-49} [Ex Nihilo] (Ex-Nihilo-1.38-49.jar) 
	U	excompressum{1.0} [Ex Compressum] (excompressum-mc1.7.10-1.1.113.jar) 
	U	extracells{2.3.7} [Extra Cells 2] (ExtraCells-1.7.10-2.3.7b176.jar) 
	U	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities_server.jar) 
	U	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.3.jar) 
	U	Forestry{3.5.7.16} [Forestry for Minecraft] (forestry_1.7.10-3.5.7.16.jar) 
	U	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	U	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	U	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	U	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375.jar) 
	U	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375.jar) 
	U	gvc{0.6.1} [�aGliby's�f Voice Chat Mod] (GlibysVC-1.7.10-0.6.1.jar) 
	U	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	U	gregapi{GT6-MC1710} [Greg-API] (gregtech_1.7.10-6.03.06.jar) 
	U	gregapi_post{GT6-MC1710} [Greg-API-Post] (gregtech_1.7.10-6.03.06.jar) 
	U	gregtech{GT6-MC1710} [GregTech] (gregtech_1.7.10-6.03.06.jar) 
	U	HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar) 
	U	wrenchPlugin{0.0.1} [IC2 Wrench Plugin] (IC2 Wrench Plugin Version 1.0.3.jar) 
	U	IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2] (IC2NuclearControl-2.3.3a-Exist.jar) 
	U	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.DEV.GITBORK.jar) 
	U	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	U	immersiveintegration{0.6.8} [Immersive Integration] (immersiveintegration-0.6.8.jar) 
	U	IC2{2.2.817-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.817-experimental.jar) 
	U	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	U	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	U	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	U	Mekanism{9.0.2} [Mekanism] (Mekanism-1.7.10-9.0.2.271.jar) 
	U	MekanismGenerators{9.0.2} [MekanismGenerators] (MekanismGenerators-1.7.10-9.0.2.271.jar) 
	U	MekanismTools{9.0.2} [MekanismTools] (MekanismTools-1.7.10-9.0.2.271.jar) 
	U	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	U	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	U	MrTJPCoreMod{1.1.0.32} [MrTJPCore] (MrTJPCore-1.1.0.32-universal.jar) 
	U	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.0.jar) 
	U	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	U	OpenComputers{1.5.19.37} [OpenComputers] (OpenComputers-MC1.7.10-1.5.19.37-universal.jar) 
	U	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	U	PneumaticCraft{1.12.7-150} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.7-150-universal.jar) 
	U	PowerUtils{1.7.10-1.0.4} [PowerUtils] (PowerUtils-1.7.10-1.0.4.jar) 
	U	PracticalLogistics{0.2.4} [Practical Logistics] (Practical-Logistics-1.7.10-0.2.4.jar) 
	U	ProjRed|Core{4.7.0pre10.93} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre10.93-Base.jar) 
	U	ProjRed|Compatibility{4.7.0pre10.93} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre10.93-Compat.jar) 
	U	ProjRed|Integration{4.7.0pre10.93} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
	U	ProjRed|Transmission{4.7.0pre10.93} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar) 
	U	ProjRed|Illumination{4.7.0pre10.93} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre10.93-Lighting.jar) 
	U	Railcraft{9.10.0.0} [Railcraft] (Railcraft-1.7.10-9.10.0.0.jar) 
	U	SonarCore{1.1.3} [SonarCore] (SonarCore-1.7.10-1.1.3.jar) 
	U	StevesWorkshop{0.5.0} [Steve's Workshop] (StevesWorkshop-0.5.1b.jar) 
	U	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	U	TickProfiler{1.7.10} [TickProfiler] (TickProfiler-1.7.10.39.jar) 
	U	UsefulFood{1.4.5} [UsefulFood] (UsefulFood-1.7.10-1.4.5.jar) 
	U	ztech{0.0.2} [Ztech] (ZTech-0.0.2.jar) 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by spannerman79** [comment]
Usually this is a mod issue.

Example;
Mod A wants to load before Mod B, Mod B wants to load before Mod A. Rinse & repeate.

----

Last time i saw this was...ohhh years ago. pre 1.6.4 at any rate.

**Comment by Time6628** [comment]
Non-thermos issue.
