### ISSUE TITLE
Unable to start Server with Thermos

### ISSUE THREAD

**Issue by zero80472** [CyberdyneCC/Thermos#449]
**Server Log:** *http://pastebin.com/rt4LrAA5*

**FML Log(s):** *http://pastebin.com/XTFS6qdr*

**Explanation of issue:** Server Fails to start

**How to recreate this issue:** Launched Bat file nothing happens then error 
Launch Args i used (form the install guide (just modded Memory ) 

Java " java -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m  -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms6G -Xmx8G -XX:hashCode=5 -Dfile.encoding=UTF-8 -jar Thermos-1.7.10-1448-server.jar --log-strip-color "

**Modpack Name:** *Crundee Craft*

**Mods Installed:** http://pastebin.com/pEVwK5Ri

**Plugins Installed:** None 

**Warmroast Report:** *(Optional)*

**Thermos Version:** Thermos-1.7.10-1448-server

**Forge Version:** forge-1.7.10-10.13.4.1448-1.7.10-universal

Im avalable on Skype or teamspeak

Thanks
Zero80472

**Comment by Time6628** [comment]
Remove mobiuscore or replace it with the thermos version.

**Comment by zero80472** [comment]
Where can i get a Thermos Version Of mobius core (been looking and cant find any)

**Comment by Time6628** [comment]
https://github.com/CyberdyneCC/Thermos#known-caveats-use-provided-fixes-at-your-own-risk
