### ISSUE TITLE
"A problem occured running the server launcher"

### ISSUE THREAD

**Issue by rocketdoge** [CyberdyneCC/Thermos#450]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/DRBLkdfM
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/qjfZd1rD
**Explanation of issue:**
Error "A problem occured running the server launcher" and following server crash on startup
**How to recreate this issue:**
Start Thermos-server.jar with FTB Sky Factory 2.5 installed
**Modpack Name:** *(Only if public)*
Feed The Beast SkyFactory 2.5
**Mods Installed:**
No other than included in the modpack
**Plugins Installed:**
None
**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-server version 57-1614 (Same error with versions 54,55,56)
**Forge Version:**
1614

**Comment by spannerman79** [comment]
Dupe #449

**Comment by rocketdoge** [comment]
#449 has litterally been opened minutes after I gave up yesterday evening after hours of troubleshooting without success. Thank you ^^
