### ISSUE TITLE
All tiles stop working

### ISSUE THREAD

**Issue by BlayzerQ** [CyberdyneCC/Thermos#455]
Sometimes, all the machines, blocks of mods - all tiles stop working. We have to do a restart to get everything working again.
This problem only in a thermos, no one I have it.
Last version Thermos.

**Comment by iKaneki-Ken** [comment]
Thermos/Cauldron has a feature that forces tile entities to stop ticking if there's no players nearby.

**Comment by BlayzerQ** [comment]
All tiles on the map, for all

**Comment by Bogdan-G** [comment]
reboot server?

**Comment by BlayzerQ** [comment]
Reboot fix this.

**Comment by BlayzerQ** [comment]
But, sometimes this problem again.

**Comment by Bogdan-G** [comment]
reboot server every 6-12h

**Comment by BlayzerQ** [comment]
Reboot every 4h. This problem (for me) very rarity. (for friends - common)

**Comment by Time6628** [comment]
Please follow the format, once again invalid.
