### ISSUE TITLE
An error during assembly

### ISSUE THREAD

**Issue by maksim182003** [CyberdyneCC/Thermos#456]
C:\Users\Maxim\Desktop\Thermos\Thermos\src\main\java\thermos\ThermosClassTransformer.java:13: error: package pw.prok.imagine.asm does not exist
import pw.prok.imagine.asm.ImagineASM;
                          ^
C:\Users\Maxim\Desktop\Thermos\Thermos\src\main\java\thermos\ThermosClassTransformer.java:14: error: package pw.prok.imagine.asm does not exist
import pw.prok.imagine.asm.Transformer;
                          ^
C:\Users\Maxim\Desktop\Thermos\Thermos\src\main\java\thermos\ThermosClassTransformer.java:18: error: cannot find symbol
public class ThermosClassTransformer implements Transformer {
                                                ^
  symbol: class Transformer
C:\Users\Maxim\Desktop\Thermos\Thermos\src\main\java\thermos\ThermosClassTransformer.java:17: error: package Transformer does not exist
@Transformer.RegisterTransformer
            ^
C:\Users\Maxim\Desktop\Thermos\Thermos\src\main\java\thermos\ThermosClassTransformer.java:20: error: cannot find symbol
    public void transform(final ImagineASM asm) {
                                ^
  symbol:   class ImagineASM
  location: class ThermosClassTransformer
C:\Users\Maxim\Desktop\Thermos\Thermos\src\main\java\thermos\ThermosClassTransformer.java:36: error: cannot find symbol
    public void extractFrom(ImagineASM asm, InsnList list) {
                            ^
  symbol:   class ImagineASM
  location: class ThermosClassTransformer
C:\Users\Maxim\Desktop\Thermos\Thermos\src\main\java\thermos\ThermosClassTransformer.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

**Comment by Bogdan-G** [comment]
check libraries exist

**Comment by Time6628** [comment]
You're missing the kImagine library. This is most likely due to protick's repo now have to have devs authenticate with it before being able to download the libraries.
