### ISSUE TITLE
items disappear

### ISSUE THREAD

**Issue by BlayzerQ** [CyberdyneCC/Thermos#457]
Some times some items disappear from chests (ironchest), ME (appenerg) when leave the game or leave the chunk (unload chunk).
Last version of Thermos.

**Comment by Bogdan-G** [comment]
please normal formed issue

**Comment by spannerman79** [comment]
@BlayzerQ When you opened your issue there was a template for you to fill out.  That template was there for a reason.

I think this issue should be closed due to an incorectly opened issue - which can now be stated as templates are an accepted method to follow whilst opening issues.

**Comment by iKaneki-Ken** [comment]
@BlayzerQ So, what exactly are you expecting the people in this github to say with such a lack of useful information?

We need logs, modpack, plugins and exact thermos version.
