### ISSUE TITLE
[15:54:03 ERROR]: Please report this to https://github.com/TCPR/Thermos/issues

### ISSUE THREAD

**Issue by lightning02** [CyberdyneCC/Thermos#461]
The server is going slow!
http://pastebin.com/sGPU9jS7
Logs:
https://www.dropbox.com/s/t0dga5lzl35rwue/fml-server-latest.log?dl=1
https://www.dropbox.com/s/fcesmmbrmgyevzy/latest.log?dl=1

**Comment by spannerman79** [comment]
http://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod is the issue - if you looked at your own log.

**Comment by Time6628** [comment]
Not Thermos.
