### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by CobaltSparkz** [CyberdyneCC/Thermos#463]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

http://pastebin.com/Rd2MDxsf

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

As Above

**Explanation of issue:**

Server crashed after filling console with said issue

**How to recreate this issue:**

N/A

**Modpack Name:** *(Only if public)*

RR3 Mainline

**Mods Installed:**

Pack Default + Dynmap, Worldedit, MTRM, ASync WorldEdit 

**Plugins Installed:**

![image](https://cloud.githubusercontent.com/assets/17088374/17231980/e995d3d0-551c-11e6-90a7-53c8ab516853.png)

**Warmroast Report:** *(Optional)*

**Thermos Version:**

57

**Forge Version:**

1614

**Comment by Time6628** [comment]
Something with ancient ware fare.

**Comment by MixSt** [comment]
**1.** Try to use latest version of Ancient Warfare
[https://mods.curse.com/mc-mods/minecraft/224602-ancient-warfare-2#t1:other-downloads](url)
**2.**  From your paste `net.shadowmage.ancientwarfare.automation.tile.torque.multiblock.TileWindmillBlade.validateSetup(TileWindmillBlade.java:120)`

`net.shadowmage.ancientwarfare.core.util.BlockFinder.connect(BlockFinder.java:74)`
i see that AW2 trying to create multiblock sructure WindMill, but something goes wrong. Do you have Essentials AntiBuild plugin installed?(try to remove it)
**3.** Maybe your construction stands between two WG regions. Try to add AW2's fake-player to OPs(i don't know it's name, use Google)
**4.** Try to start server without plugins.

**Comment by aetherpirate** [comment]
https://github.com/shadowmage45/AncientWarfare2/issues/490

my issue may be related.
