### ISSUE TITLE
holographic-displays

### ISSUE THREAD

**Issue by origamerpro** [CyberdyneCC/Thermos#464]
**Server Log:** *no log*

**FML Log(s):** *no log*

**Explanation of issue:** holographic incorrect display.

**How to recreate this issue:** install holographic-displays on server, create HD and look on him.
http://puu.sh/qikv2/82c15dec5d.jpg
http://puu.sh/qikxz/f2ebed214d.jpg

Seen strictly diagonally only. 5 mm left/right and dont seen HD.

**Modpack Name:** *(Only if public)*

**Mods Installed:** no
**Plugins Installed:** holographic-displays 2.1.10-13 official and fixed version

**Warmroast Report:** *(Optional)* no

**Thermos Version:** 57

**Forge Version:**1614

**Comment by origamerpro** [comment]
fixed

**Comment by spannerman79** [comment]
If your issue is fixed then don't just rename - actually close your issue yourself.

**Comment by KasperFranz** [comment]
I don't have this issue on my machine - might be becase i'm using another version of Holographics display (version 2.1.6)

**Comment by origamerpro** [comment]
Sorry that problem FastCraft mod...

**Comment by spannerman79** [comment]
If you can find and old version of FastCraft 1.21 you can use that - but you cannot use it in a modpack - against Players conditions of use.

My drop in replacement for FastCraft is CoFHTweaks for client side.

**Comment by origamerpro** [comment]
big thx
