### ISSUE TITLE
What is it? Warn in console every 2 minutes

### ISSUE THREAD

**Issue by mrRaDiC** [CyberdyneCC/Thermos#465]
What is it? Warn in console every 2 minutes. Please help me.

http://i.imgur.com/qVKT0CZ.png

Mods Installed: TerraFirmaCraft 0.79.29
Thermos Version: 57
Forge Version: 1614

**Comment by KasperFranz** [comment]
as I see it, it is because of the updater can't detech either your or the newest version

**Comment by Time6628** [comment]
Disable update checker in thermos.yml.
