### ISSUE TITLE
Book and quill not working

### ISSUE THREAD

**Issue by enarkay** [CyberdyneCC/Thermos#467]
**Explanation of issue:**
The book and quill isn't quite working. No matter how many times and in different ways I try to write with a book and quill, the book and quill will not transform into a written book but simply stay as the book and quill it is. I've tried everything I could possibly think of, and even after signing and naming the book after writing, nothing will save. A side problem worth mentioning is that even though the book and quill does not save any of the texts, author, or title, it seems to be recognized as a used book since I can no longer enter texts into the book and quill after any first attempts. I've confirmed that this does not happen on a singleplayer world or on a lan server even with others invited, and is a unique problem that only happens on thermos.

**How to recreate this issue:**
Take out a new book and quill while on thermos server and try writing in it.

**Mods Installed:**
- BiblioCraft[v1.11.5][MC1.7.10]
- CustomNPCs_1.7.10d(21feb16)

**Plugins Installed:**
- EssentialsX-2.0.1
- worldedit-bukkit-6.1.3
- AsyncWorldEdit
- AsyncWorldEditInjector

**Warmroast Report:** *(Optional)*
Do not know what this is

**Thermos Version:**
Thermos-1.7.10-1614-57

**Forge Version:**
If this means the client forge version, then I used 1.7.10 forge-10.13.4.1614

**Comment by enarkay** [comment]
**Update**
I have just confirmed that this is a problem on thermos side, since I just tested a raw thermos server with no mods & plugins and the problem with the book and quill remains the same.

**Comment by Time6628** [comment]
Dupe #437

**Comment by enarkay** [comment]
My sincere apologies, I should've checked through the already reported issues more carefully.
