### ISSUE TITLE
Dont compiling sources

### ISSUE THREAD

**Issue by linkinkov** [CyberdyneCC/Thermos#470]
Picture to explain issue: https://monosnap.com/file/01oi7NFwmRn7vPHVLvYiToBiCgjvV3

**Comment by Robotia** [comment]
Prototik's maven either offline or broken

**Comment by Time6628** [comment]
Pretty sure you have to authenticate with it before you can use it. I'm not quite sure how though.

**Comment by spannerman79** [comment]
Don't use GitHub desktop for one - it dumbs thing down *too* much when using Git.  Add your Git SSH key to https://gitlab.prok.pw/profile/keys

**Comment by MegaFlary** [comment]
You should import prok.pw SSL certificate.
https://docs.oracle.com/javase/tutorial/security/toolsign/rstep2.html

**Comment by linkinkov** [comment]
I import ssl sertificate, but nothing is change, can anybody send zip archive with full sources?

**Comment by Robotia** [comment]
I can distribute a copy of my gradle cache which should fix things, but it is 396MB. Contact me by email and I will send you a link.

**Comment by linkinkov** [comment]
Thanks a lot

**Comment by fewizz** [comment]
@linkinkov (https://yadi.sk/d/T3ATNCFTtvife)[Here] . (I late =_= )

**Comment by linkinkov** [comment]
@fewizz 404 :c

**Comment by fewizz** [comment]
@linkinkov . copy to "USERNAME"/.gradle/caches/modules-2/files-2.1/

**Comment by Robotia** [comment]
@linkinkov let me know if that worked, if not I will upload the 396MB cache to Yandex Disk

**Comment by MegaFlary** [comment]
There is no reason to upload all of 396 MB cache.

**Comment by linkinkov** [comment]
Now compiling without problem, thank you friends!
