### ISSUE TITLE
Server startup crash

### ISSUE THREAD

**Issue by Spectrumize** [CyberdyneCC/Thermos#473]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/39BYFJNu

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/wZ1a21D1

**Explanation of issue:**
I uploaded and ran thermos on my server and now i have added mods to it but whenever i click start now the server gets up to checking eula then it crashes
**How to recreate this issue:**
Run a server with thermos and add the mods and config from skyfactory 2.5.3
**Modpack Name:** *(Only if public)*
skyfactory 2.5.3

**Mods Installed:**
![list of mods](https://cloud.githubusercontent.com/assets/20775715/17298942/0d651bce-5804-11e6-9d82-8b81f64c9636.PNG)

**Plugins Installed:**
non

**Warmroast Report:** *(Optional)*
no clue what this is anyway

**Thermos Version:**
Thermos-1.7.10-1614-server.jar
**Forge Version:**
forge-1.7.10-10.13.4.1614.jar

**Comment by iKaneki-Ken** [comment]
Try setting the setting inside eula.txt to true.

**Comment by Spectrumize** [comment]
thanks
