### ISSUE TITLE
Who is guilty thermos or mods?

### ISSUE THREAD

**Issue by LeftBoy** [CyberdyneCC/Thermos#476]
**Crash Log:**
http://pastebin.com/94knkQ7M
http://pastebin.com/HqdhENFK
**Server Log:**
http://pastebin.com/r1m4Y7Vx
**Explanation of issue:**
I don't know why the server was crashed
**How to recreate this issue:**
I don't know.
**Mods Installed:**
Aether II (with lib gilded games util), TinkerConstruct (with lib Mantle), Biomes o' plenty, Carpentersblocks, Chisel 2, Bibliocraft, Furniture Mod, WildCaves, CustomNPC, IronChests, OceanCraft, ItemPhysic (with lib CreativeCore), Infernal Mobs.
**Plugins Installed:**
CoreProtect, WorldEdit, DupeFixer, Essentials, ChatGame, ClearLag, AutoMessage, PlugMan, WorldBorder, PowerNBT, MineBlocker, ProtocolLib, WorldGuard, MaxBans, EssentialsChat, PermissionsEx, BanItem, ModFixNG, WGExtender, StatsPvP, MachineGuardReloaded, Vault, CombatTag, ChatGuard, EssentialsSpawn, TrueCommand, Timeismoney, RandomTP, ShoppingCartReloaded, SimpleClans, ScoreboardStats
(many plugins - my own development)
**Thermos Version:**
Thermos:1.7.10-1614.57
**Question:**
    Found chunk: true
    Location: World: (71339,11,16), Chunk: (at 11,0,0 in 4458,1; contains blocks 71328,0,16 to 71343,255,31), Region: (139,0; contains chunks 4448,0 to 4479,31, blocks 71168,0,0 to 71679,255,511)
What is this??? Location: World: (71339,11,16)
I use WorldBorder and my World limited on 3500 blocks .

**Comment by Robotia** [comment]
Hello,

The crash report gives the wrong idea -- the cause is terrain generation taking too long (due to a mod), there was a mistake in the code that forces the server to shut down that throws this crash report.

Solution: Either pregenerate your world or examine the additional world generators to determine which one is causing your time out.

Thank you,

Robotia

**Comment by spannerman79** [comment]
*Personal Experience Only - Not to be taken as fact or truth*

While Biomes O Plenty does create some pretty good worldgen it also has little "issues" if you use any other mod that hooks into worldgen as well.  Sometimes they don't play nice together and causes issues.

I cannot state as to which mods cause this as its never the same each and every time.  This isn't restricted to just Cauldron or its forks but also vanilla forge as well.

I haven't reported those issues as I could not reproduce them each and every single time - hence why I cannot give proof and stated that this is my personal experience.
