### ISSUE TITLE
Lags and crash

### ISSUE THREAD

**Issue by SkydeFR** [CyberdyneCC/Thermos#477]
**Server Log:**
http://pastebin.com/TDyFr7aE

**FML Log(s):**
http://pastebin.com/TDyFr7aE

**Explanation of issue:**
Randomly I think, with no apparent reason, the server starts to lag, these errors fill the console and the server finally crash.

**How to recreate this issue:**
Just start the server, I think some players need to be connected and just wait.

**Modpack Name:**
*[FTB infinity Evolved](https://www.feed-the-beast.com/projects/ftb-infinity-evolved)* (last version : 2.5.0)

**Mods Installed:**
FTB Infinity Evolved Modpack + ChickenChunks (disabled by default) + Dynmap
Here is the contained of my mods folder: http://pastebin.com/5jm1R6yc 

**Plugins Installed:**
![Screenshot](http://puu.sh/qorq1/f38bf84a5f.png)
Here is the contained of my plugin folder: http://pastebin.com/RNxfg4UA

**Warmroast Report:** *(Optional)*

**Thermos Version:**
1.7.10-R0.1-SNAPSHOT : 1.7.10-1614.55 (MC: 1.7.10)

**Forge Version:**
10.13.4.1614

**Comment by MixSt** [comment]
This is non-thermos issue. Plugin Prism has troubles with sql connection (log errors). I think you use remote sql connection, that throttles your server. Disable Prism and try again.

**Comment by Robotia** [comment]
Thank you for explaining this @MixSt, you beat me to it!

**Comment by SkydeFR** [comment]
Thanks, but I've got a "timed out" problem bow, I saw this issue https://github.com/CyberdyneCC/Thermos/issues/105 but I don't know if it's 100% similar or not.

I used sampler and here is two stall reports :
http://pastebin.com/VYzs3hMW and http://pastebin.com/1Ghst0kD

**Comment by Robotia** [comment]
Looks like Dynmap rendering code is at fault, have you tried running your without it?

**Comment by Time6628** [comment]
This is a conflict between Extra Utilities and Thaumcraft. Essentially thaumcraft is trying to generate something in the deep dark, but it can't, so the server stalls out. Only way to fix this is to disable thaumcraft gen or aura node gen.

**Comment by SkydeFR** [comment]
Seems good now, thanks for your help =)

**Comment by SkydeFR** [comment]
I'm sorry for reopening this issue but I've got new crashes and I haven't got any idea where does the problem..

Here are two stall reports : 
http://pastebin.com/dH5sYak0 and http://pastebin.com/4c92BJbf
And here is a crash report : http://pastebin.com/TruhSbed

**Comment by Robotia** [comment]
Twilight forest is at fault.

I am sorry but this is not a general server help forum, it is for issues clearly related to Thermos. If you need help and you aren't sure what the cause is, please join the Discord server and talk to us there first.

Thanks,

Robotia
