### ISSUE TITLE
Factions Support?

### ISSUE THREAD

**Issue by Andrew2070** [CyberdyneCC/Thermos#478]
Modpack Name:  Post Blast
Explanation of issue:
[Attempting to Use Factions protection against Modded Containers]
[So as to prevent normal users from accessing each others modded chests/machines]
[Was wondering if Thermos adds support for Modded Ids to be used under Factions MCONF]

The default configuration for the Container array is as follows:
"materialsContainer": [
"DISPENSER",
"CHEST",
"FURNACE",
"BURNING_FURNACE",
"JUKEBOX",
"BREWING_STAND",
"ENCHANTMENT_TABLE",
"ANVIL",
"BEACON",
"TRAPPED_CHEST",
"HOPPER",
"DROPPER"
],

I have spoken to Factions/MassiveCore Devs.
They locked it, and refered me to a previously made issue.
Which concerned a commandsender error in Kcauldron compatability.

Anyhow, that doesn't relate to this.
They didn't tell me what I should do or how I should do it.
Many people suggested thermos, and check if that works.

[Ids didn't seem to work with Kcauldron in that array when manually listed]

My question is, does this allow Bukkit to read Forge Modded Items by name/id?
If so, can names suchas IronChest:BlockIronChest be used in the containers array?

Mods Installed:
[174 Mods]
[You want the list?]

Plugins Installed: 
[34 Plugins]
[Factions, FactionsPlus, ItemRestrict, PlugMan, BuyCraft, Essentials, HeroChat, etc]

~Peace, and thank you.

**Comment by spannerman79** [comment]
Use search....
https://github.com/CyberdyneCC/Thermos/issues/353

**Comment by Time6628** [comment]
> Can both Factions/Thermos staff stop referring me to topics unrelated to my issue.
My issue is in regards to making FACTIONS comply with MODS.
It is not an error being thrown, it is a compatability question.
I refuse to use MyTown2 on a WW3 type ModPack, and I REQUIRE Factions.
I hope the message is clear that I am looking for help in finding the right method,
of modifying the factions code or configuration to comply with minecraft forge mod ids/block names.

It is not an issue with Thermos or MassiveCraft or Factions, it's an issue with you not being able to understand how to use configs. You can use any bukkit material name you want in the config.

**Comment by Andrew2070** [comment]
Okay,

Then how exactly do I do that? @Time6628 

Listing the Id here doesn't work and returns null.
Using the block name doesnt work here and returns null.

Thermos won't work with it either, so can i please just know how I can list modded items in that array? and get them to work as well please.

**Comment by Time6628** [comment]
Hold them item in your hand and do /itemdb. That will give you the bukkit material name. Or you could just use LWC and place signs on blocks and lock them... since factions has LWC support...

**Comment by Paralaxus** [comment]
Is this the correct method:
    "OPENCOMPUTERS_REDSTONE",
    "OPENCOMPUTERS_RELAY",
    "OPENCOMPUTERS_SCREEN1",
    "OPENCOMPUTERS_SCREEN2",
    "OPENCOMPUTERS_SCREEN3",
    "OPENCOMPUTERS_RACK",
    "OPENCOMPUTERS_SWITCH",
    "OPENCOMPUTERS_PRINTER",
    "OPENCOMPUTERS_WAYPOINT",
    "OPENCOMPUTERS_NETSPLITTER",
    "OPENCOMPUTERS_TRANSPOSER"

**Comment by Paralaxus** [comment]
or is it OPENCOMPUTERS:TRANSPOSER versus OPENCOMPUTERS_TRANSPOSER
