### ISSUE TITLE
Build 55 - thaumcraft obelisks fail to spawn in overworld

### ISSUE THREAD

**Issue by djoveryde** [CyberdyneCC/Thermos#479]
I have both a factions and towny server running the same modpack with thaumcraft in. For some reason the obelisks aren't loading into the world as an auto generating item nor are the priests who chant usually around the obelisk. As they don't support thermos I was wondering if there is a reason for this? The ores generate but not structures.

**Comment by Time6628** [comment]
Check your configs.

**Comment by djoveryde** [comment]
Configs are fine and even reset, tested it on a completely clean setup as well and still nothing

**Comment by Time6628** [comment]
Most likely a plugin issue. I have multiple servers with thaumcraft and this does not occur.
