### ISSUE TITLE
Error and disconnect from server when try to create space station with GC mod.

### ISSUE THREAD

**Issue by Krysinski** [CyberdyneCC/Thermos#480]
**Server Log:** http://pastebin.com/cVAQJzqq
**FML Log(s):** http://pastebin.com/2bfi3QxC
**Explanation of issue:** Cant create space station by pressing button: it return me to Celestial Map without any selected object (like when i click on space). In SP i can create station by click on resource list (maybe inventory visual bug). In MP i get error and disconnect from server.
**How to recreate this issue:** try to create space station with GC mod
**Modpack Name:** *(Only if public)*
**Mods Installed:**
AdvancedSolarPanel-1.7.10-3.5.1.jar
appliedenergistics2-rv3-beta-6.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
BiblioWoods[Forestry][v1.7].jar
catwalks-2.0.4.jar
Chisel2-2.5.1.44.jar
[CLIENT]neiaddons-1.12.14.40-mc1.7.10.jar
[CLIENT]NEIIntegration-MC1.7.10-1.1.1.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.2-325.jar
coroutil-1.7.10-1.1.5.jar
CustomOreGen-1.7.10-1.2.24.jar
CyanosLootableBodies-1.7.10-backport_1.3.7.jar
EnderCore-1.7.10-0.2.0.34_beta.jar
EnderIO-1.7.10-2.3.0.425_beta.jar
forestry_1.7.10-4.2.14.62.jar
GalacticraftCore-1.7-3.0.12.460.jar
Galacticraft-Planets-1.7-3.0.12.460.jar
HardcoreDarkness-MC1.7.10-1.7.jar
ic2ca-1.7.10-1.14.5.06.jar
IC2NuclearControl-2.4.1a.jar
immibis-core-59.1.4.jar
industrialcraft-2-2.2.822-experimental.jar
ironchest-1.7.10-6.0.62.742-universal.jar
MicdoodleCore-1.7-3.0.12.460.jar
MineTweaker3-1.7.10-3.0.10B.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
redlogic-59.1.13.jar
[SERVER]EventHelper-1.4.jar
[SERVER]FastLeafDecay-1.7.10-1.3.jar
[SERVER]GraviSuite-1.7.10-2.0.3.jar
[SERVER]Morpheus-1.7.10-1.6.20.jar
[SERVER-NOCLIENT]weaponmod-1.14.3.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.1.2-240.jar
ThermalFoundation-[1.7.10]1.2.3-112.jar
Treecapitator-universal-2.0.4.jar
zombieawareness-1.9.6 for MC v1.7.10.jar
Ztones-1.7.10-2.2.1.jar

**Plugins Installed:** 
[1.22.9]PermissionsEx.jar
[1.4.1]Vault.jar
[1.8.1]WorldBorder.jar
[189]WGExtender.jar
[2.0.2]PlugMan.jar
[2.13.1]Essentials.jar
[2.13.1]EssentialsChat.jar
[2.13.1]EssentialsSpawn.jar
[2.1]MachineGuard_Reloaded.jar
[2.5.2]AutoMessage.jar
[2.8.0]DeathMessages.jar
[3.1]GoreaRestrict.jar
[3.6.4]ProtocolLib.jar
[7.2]ChatGuard.jar
[72]ModFixNG.jar
AutoSaveWorld_888.jar
KitPlugin.jar
LokiBlocker0.5.4.jar
Multiverse-Core-2.5.0-SNAPSHOT.jar
Multiverse-Portals-2.5.0-SNAPSHOT.jar
MyWarp_3.0.beta3.jar
NoVillagerTrading.jar
PvPToggle.jar
[RUS-15_53][6.1]worldedit.jar
[RUS-v.0.7][6.1]]worldguard.jar
WorldGuardEventWrapper.jar

**Warmroast Report:** *(Optional)*
**Thermos Version:** 1.7.10-1614.57
**Forge Version:** 1614
this issue on micdoodle https://github.com/micdoodle8/Galacticraft/issues/2242

**Comment by spannerman79** [comment]
On generation of Space station you are in default world/Overworld - non multiverse/plugin created/generated world?

If not then *possibly* related to https://github.com/micdoodle8/Galacticraft/issues/2182

**Comment by Krysinski** [comment]
I tested both variants: from dim 0 and from dim 11 (multiverse world, but it set as default overworld in GC config), allways get error. I try use b46, same error. Also GC configs: client=server.
multiverse conf: http://pastebin.com/D3Qwt3u3

**Comment by spannerman79** [comment]
https://github.com/micdoodle8/Galacticraft/issues/2191#issuecomment-220574132

**Comment by Krysinski** [comment]
There is no problem to launch to planets.

**Comment by Time6628** [comment]
Most likely an issue between multiverse and GC. Marking external.

**Comment by Krysinski** [comment]
This is not Thermos issue!
I can create Space station wihtout errors if set this to 0 in GC config:

```
# Dimension ID for the Overworld (as seen in the Celestial Map)
I:idDimensionOverworld=0
```
Problem is actualy when i change this to not 0.
