### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by xxsuperdreamxx** [CyberdyneCC/Thermos#482]
Forge log: http://pastebin.com/d54pMP9E
Server log: http://pastebin.com/0fZLC9Xe
When I try to start the server after maybe 2 min server console crash.
Name of Modpack Project Ozone 2 0.1.4
151 or 206 mods
 0 plugins 
Thermos version: Thermos-1.7.10-1492-57-server
Forge version:  Forge-10.13.4.1614

**Comment by xxsuperdreamxx** [comment]
IF someone fixed the problem I will be happy I have deleted the FastCraft and nothing I think some other mods are the problem

**Comment by Robotia** [comment]
You're downloading an older forge version of Thermos. Download 1614

**Comment by Time6628** [comment]
Remove opis.

**Comment by xxsuperdreamxx** [comment]
@Robotia and @Time6628 Thank you so much now it work and if I have problem I will write you guys again have a nice day, guys :)
