### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by FloppyDi** [CyberdyneCC/Thermos#483]
Server Log: [http://pastebin.com/kgdq77ip](http://pastebin.com/kgdq77ip)
Server сrash repeatedly. I've 5-10 crashes in a day.

Plugins Installed: 
WorldBorder, NightAttack, NoSpawnChunks, WorldEdit, VoxelSniper, VIP-GOD, Lores, dFix, Vault, MineBlocker, PermissionsEx, Prism, WorldGuard, UnionAPI, NoobProtector, boosCooldowns, AutoMessage, dAdmin, WGFix, Scavenger, ColoredTags, OpenInv, dChat, BanManager, ClearLag, ProtocolLib, HolographicDisplays, AutoSaveWorld, dProtect, WGExtender, Essentials, ModFixNG, AsyncWorldEdit, UniShop, uHome, EssentialsSpawn, UTServerModule, MachineGuard_Reloaded, ReActions, TouchscreenHolograms, EssentialsChat

Mods:
mcp{9.05}[MinecraftCoderPack](minecraft.jar)
FML{7.10.99.99}[ForgeModLoader](thermos.jar)
Forge{10.13.4.1614}[MinecraftForge](thermos.jar)
kimagine{0.2}[KImagine](minecraft.jar)
AM2-Preloader{0.0.3}[AMCore](minecraft.jar)
CodeChickenCore{1.0.7.47}[CodeChickenCore](minecraft.jar)
NotEnoughItems{1.0.5.120}[NotEnoughItems](NotEnoughItems-1.7.10-1.0.5.120-universal.jar)
ThaumicTinkerer-preloader{0.1}[ThaumicTinkererCore](minecraft.jar)
AnimationAPI{1.2.4}[AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar)
arsmagica2{1.4.0.009}[ArsMagica2](1.7.10_AM2-1.4.0.009.jar)
mod_AsyncWorldEdit_Injector{2.1.0}[AsyncWorldEditInjector](AsyncWorldEditInjector.jar)
Baubles{1.0.1.10}[Baubles](Baubles-1.7.10-1.0.1.10.jar)
Thaumcraft{4.2.3.5}[Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar)
Waila{1.5.10}[Waila](Waila-1.5.10_1.7.10.jar)
Automagy{0.28.2}[Automagy](Automagy-1.7.10-0.28.2.jar)
BiblioCraft{1.11.5}[BiblioCraft](BiblioCraft[v1.11.5][MC1.7.10].jar)
BiomesOPlenty{2.1.0}[BiomesO'Plenty](BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar)
AWWayofTime{v1.3.3}[BloodMagic:AlchemicalWizardry](BloodMagic-1.7.10-1.3.3-17.jar)
Botania{r1.8-249}[Botania](Botania-r1.8-249.jar)
TwilightForest{2.3.7}[TheTwilightForest](twilightforest-1.7.10-2.3.7.jar)
chisel{2.5.1.44}[Chisel2](Chisel2-2.5.1.44.jar)
CarpentersBlocks{3.3.8}[Carpenter'sBlocks](Carpenter'sBlocksv3.3.8-MC1.7.10.jar)
ChickenChunks{1.3.4.19}[ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar)
chocolateQuest{1.0}[ChocolateQuest](chocolateQuest_Ghast_fix_by_iota.jar)
customnpcs{1.7.10d}[CustomNpcs](CustomNPCs_1.7.10d(21feb16)_JERA_server.jar)
dMod{0.1}[dMod](dMod.jar)
DummyCore{1.13}[DummyCore](DummyCore1.13.jar)
endercore{1.7.10-0.2.0.36_beta}[EnderCore](EnderCore-1.7.10-0.2.0.36_beta.jar)
EventHelper{1.6}[EventHelper](EventHelper-1.6.jar)
evilcraft{0.9.9}[EvilCraft](EvilCraft-1.7.10-0.9.9.jar)
fastleafdecay{1.4}[FastLeafDecay](FastLeafDecay-1.7.10-1.4.jar)
ThaumicTinkerer{unspecified}[ThaumicTinkerer](ThaumicTinkerer-2.5-1.7.10-527.jar)
ForbiddenMagic{1.7.10-0.575}[ForbiddenMagic](ForbiddenMagic-1.7.10-0.575.jar)
HardcoreEnderExpansion{1.8.6}[HardcoreEnderExpansion](HardcoreEnderExpansionMC-1.7.10v1.8.6.jar)
iChunUtil{4.1.3}[iChunUtil](iChunUtil-4.1.3.jar)
Hats{4.0.1}[Hats](Hats-4.0.1.jar)
IronChest{6.0.62.742}[IronChest](ironchest-1.7.10-6.0.62.742-universal.jar)
magicalcrops{4.0.0_PUBLIC_BETA_4b}[MagicalCrops:Core](magicalcrops-4.0.0_PUBLIC_BETA_5.jar)
magicalcropsarmour{4.0.0_PUBLIC_BETA_4}[MagicalCrops:Armoury](magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar)
magicalcropsdeco{4.0.0_PUBLIC_BETA_4a}[MagicalCrops:Decorative](magicalcropsdeco-4.0.0_PUBLIC_BETA_4a.jar)
MineTweaker3{3.0.10}[MineTweaker3](MineTweaker3-1.7.10-3.0.10B.jar)
MoarSigns{1.2.3}[MoarSigns](MoarSigns-1.7.10-1.2.3.jar)
modtweaker2{0.9.5}[ModTweaker2](ModTweaker2-0.9.5.jar)
moreplayermodels{1.7.10b}[MorePlayerModels](MorePlayerModels_1.7.10b.jar)
NBTEdit{1.7.2.2}[In-gameNBTEdit](NBTEdit_1.7.10.jar)
libsandstone{1.0.0}[libsandstone](LibSandstone-1.0.0.jar)
xreliquary{1.2}[Reliquary](Reliquary-1.2.257.jar)
smoothbedrock{2.2.0.9}[SmoothBedrock](SmoothBedrock-1.7.10-2.2.0.9.jar)
ThaumcraftMobAspects{1.7.2-2A}[ThaumcraftMobAspects](ThaumcraftMobAspects-1.7.2-2A.jar)
thaumicbases{1.3.1710.2}[ThaumicBases](ThaumicBases-1.3.1710.4.jar)
ThaumicExploration{0.6.0}[ThaumicExploration](ThaumicExploration-1.7.10-1.1-55.jar)
ThaumicHorizons{1.1.9}[ThaumicHorizons](thaumichorizons-1.7.10-1.1.9.jar)
TravellersGear{1.16.6}[Traveller'sGear](TravellersGear-1.7.10-1.16.6.jar)
WailaHarvestability{1.1.6}[WailaHarvestability](WailaHarvestability-mc1.7.10-1.1.6.jar)
wailaplugins{MC1.7.10-0.2.0-23}[WAILAPlugins](WAILAPlugins-MC1.7.10-0.2.0-23.jar)
wawla{1.3.1}[WhatAreWeLookingAt](Wawla-1.0.5.120.jar)
witchery{0.24.1}[Witchery](witchery-1.7.10-0.24.1.jar)
witcherycmd{1.1.1}[WitcheryCommand](WitcheryCommand-1.1.1.jar)
worldedit{6.0-beta-01}[WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar)

Forge 10.13.4.1614 59 mods loaded, 59 mods active
Thermos Version:cyberdynecc:Thermos:1.7.10-1614.57

**Comment by KasperFranz** [comment]
It is the coord -3336,3,1472 there have a problem  - what is there at that location? (don't fly to it - use MCedit or similiair to see)

**Comment by FloppyDi** [comment]
Nothing. Just blocks.

**Comment by spannerman79** [comment]
`-XX:MaxGCPauseMillis=500` ?!  Thats more then likely the cause, GC pausing for too long.  That is allowing GC to pause Java instance for **up to** half a second.  That works out to 10 full ticks.

That means during any GC your TPS will never get above 10.

**Comment by FloppyDi** [comment]
But always TPS~20

**Comment by FloppyDi** [comment]
Interesting. Blocks crush only in wg territories. 
May even crush in unloaded chunks.

**Comment by Robotia** [comment]
The crash is due to a null chunk. One of your plugins/mods (I think it is likely NoSpawnChunks) is likely forcefully unloading chunks in an unsafe manner.

**Comment by FloppyDi** [comment]
О, атлична, на родном будет немного проще объяснить. Отключал этот плагин и даже пробовал переставляют эти же плагины, но на другой модпак. Таких проблем не было.

**Comment by FloppyDi** [comment]
Что странно, это происходит в уже отгруженных чанках, а потому, NoSpawnChunks сложно винить.

**Comment by fewizz** [comment]
С чего ты взял что они знают рус? :smile:

**Comment by FloppyDi** [comment]
Почта Robotia меня натолкнула на это + пару раз видел его ответы на родном.

**Comment by Time6628** [comment]
Not thermos as far as I know, marking external.

**Comment by iKaneki-Ken** [comment]
All in all, removing any plugins that force unloads chunks. You're not only looking at probable block/chunk corruption. You'll also probably face chunks, tile entities and entities reverting back to a previous state when they were last properly saved. If you set up your forge and bukkit yml's properly, you'll never have an issue with too many chunks being loaded up.

**Comment by MixSt** [comment]
En: You have damaged block at  World: (-3336,3,1472)(Exception getting block type in world) Just try to remove it by mcedit,
Try to set **B:removeErroringEntities B:removeErroringTileEntities** to **true** in your server forge.cfg in config folder.
Ru: У тебя поврежденный блок, который крашит сервак(Exception getting block type in world). не нужно ничего придумывать. Термос не при делах. Удали его mcedit. Для начала поставь в конфиге форджа **B:removeErroringEntities B:removeErroringTileEntities** в **true** и включи сервер.

**Comment by FloppyDi** [comment]
Первое что я делал, это проверял координаты. Причём, когда regionfixer ничего не обнаружил, я решил проверить это место в игре. И там абсолютно никаких проблем. Если бы это был обычный коррапт, я бы не писал сюда. 

Эта ерунда раньше происходила примерно в одно время (с погрешностью в 1-3 часа). Теперь вообще перестало о_о

**Comment by Bogdan-G** [comment]
баги кросс взаимодейсвия или чекать надо было что в точке той происходило, этот блок на краю чанка был?

**Comment by FloppyDi** [comment]
Эх, спасибо всем за ответы, но боюсь всё, что вы советовали уже было проверено.
