### ISSUE TITLE
Lag problem coming from BuildCraft

### ISSUE THREAD

**Issue by runescapejon** [CyberdyneCC/Thermos#489]
Hello i am having a bit of lag problem with BuildCraft i had ready submit an issue on there any way to fix this problem asap 
Lag's log: http://pastebin.com/KxbsJXBb
BuildCraft Issue: https://github.com/BuildCraft/BuildCraft/issues/3415

Thanks

**Comment by Time6628** [comment]
```
timeout-time: 9000
```
in spigot.yml.

**Comment by runescapejon** [comment]
Thanks
