### ISSUE TITLE
https://github.com/CyberdyneCC/Thermos/issues/441

### ISSUE THREAD

**Issue by clienthax** [CyberdyneCC/Thermos#490]
Since you closed it without fixing.
https://github.com/CyberdyneCC/Thermos/issues/441

**Comment by Robotia** [comment]
There is a feature called reopen. 

The reason for the crash was explained in a conversation on discord. After 10 seconds of waiting, the server is forcibly crashed because something has gone wrong with the biome decorator and it doesn't look like it will recover.

**Comment by clienthax** [comment]
Fuck me are you people stupid?
You are calling a client side function in that error message which crashes the server before that point.
Also with this fixed (made the method both sides) it seems to recover from worldgen bugs only kicking the person who was in the chunk being generated.

**Comment by Robotia** [comment]
How long does it take to recover? It typically hangs for longer than 30 seconds and by that time player connections start timing out.

You will receive no help for calling people stupid. If that's the attitude you want to have, find someone else to fix your problems.

**Comment by clienthax** [comment]
@Robotia it usually hangs for about 30 then shows the error+ stack, then kicks anyone near that chunk
Server does seem to recover after that without all out crashing, which is much nicer than a full restart of the server.

Thanks for fixing, the statement above was mainly to get someone to actually read the issue instead of dismissing it as a server mod bug once again after I explained the issue multiple times..
