### ISSUE TITLE
Problem with [NMS] libraries.

### ISSUE THREAD

**Issue by kalek3** [CyberdyneCC/Thermos#492]
**Server Log: No errors

**FML Log(s): No errors

**Explanation of issue: I have a big problem with Thermos: Holograms didn't work, like holografic displays and damage indicators, I think its because there are missing libraries in thermos, like NMS, I will very apraciate it if somebody can help me fo fix it and to solve this tidious problem. Thanks

**Mods Installed: AdventureBackPack, BattleGear, FastCraft, Metallurgy, SurvivalTwiks, GlibisVC-MOD, JourneyMap, CustomNPC, TICKPROFILER, Trashslot.

**Plugins Installed: Essentials, PermissionsEX, ProtocolLib, MultiverseCore, WorldGuard, HolographicDisplays, CombatHit-Indicator, Mcore, WorldEdit, QuickTrade.

**Thermos Version:1.7.10 BUILD-58ALPHA 1614

**Comment by KasperFranz** [comment]
I don't have a problem with that on my server
