### ISSUE TITLE
Problem with NMS libraries.

### ISSUE THREAD

**Issue by kalek3** [CyberdyneCC/Thermos#493]
**Server Log: No errors

**FML Log(s): No errors

**Explanation of issue: I have a big problem with Thermos: Holograms didn't work, like holografic displays and damage indicators, I think its because there are missing libraries in thermos, like NMS, I will very apraciate it if somebody can help me fo fix it and to solve this tidious problem. Thanks

**Mods Installed: AdventureBackPack, BattleGear, FastCraft, Metallurgy, SurvivalTwiks, GlibisVC-MOD, JourneyMap, CustomNPC, TICKPROFILER, Trashslot.

**Plugins Installed: Essentials, PermissionsEX, ProtocolLib, MultiverseCore, WorldGuard, HolographicDisplays, CombatHit-Indicator, Mcore, WorldEdit, QuickTrade. 

**Thermos Version:1.7.10 BUILD-58ALPHA 1614

**Comment by Time6628** [comment]
It's probably fastcraft.

**Comment by masterfapper72** [comment]
Hi, in a collaborator of kalek, we already tryed to remove fastcraft, but it does not change

**Comment by djoveryde** [comment]
If it's the damage indicators mod it works perfectly fine for me. Try pasting in the startup log for the server as you have given the team literally nothing to go by aside from something potentially missing.

**Comment by Time6628** [comment]
Closing this as no logs were provided and it's most likely not a thermos problem.

**Comment by Robotia** [comment]
Hi,

We are unable to support NMS properly because the mapping is a difficult process. I know of some plugins (i.e. BlivTrails) that have been able to provide compatibility for Forge-based, Bukkit-implementing server software. You might want to ask the author of HolographicDisplays to implement compatibility.

Thank you,

Robotia
