### ISSUE TITLE
Timings are not working on Thermos 58

### ISSUE THREAD

**Issue by Esctogrillo** [CyberdyneCC/Thermos#495]
**Server Log:** *Not necessary*

**FML Log(s):** *Not necessary*

**Explanation of issue:** *The command /timings are not working properly. When typed /timings paste (after /timings on), the answer is "View timings results can be viewed at http://www.spigotmc.org/go/timings?url=0"*

**How to recreate this issue:** *Up*

**Modpack Name:** *JordannPack*

**Mods Installed:** *Not necessary*

**Plugins Installed:** 
![screenshot_2](https://cloud.githubusercontent.com/assets/14919996/17834826/b7997a58-6728-11e6-9afa-fd479ac0731d.png)

**Warmroast Report:** *Not necessary*

**Thermos Version:** *Tested on 57 and 58*

**Forge Version:** *1614*

**Comment by Time6628** [comment]
We need logs.

**Comment by Esctogrillo** [comment]
There is no log, is just a command that not work correctly.

**Comment by Time6628** [comment]
Just give the logs anyways please.

**Comment by djoveryde** [comment]
Generally when a command is fired it will error in console if it's not working. Hence why logs are required as its timely to look through code for an unknown cause.

**Comment by KasperFranz** [comment]
This is not a thermos problem as it is happening on a normal spigot server too.

I think it is related to 
https://twitter.com/md__5/status/765072583351861248
https://twitter.com/md__5/status/765072699693469696

**Comment by Time6628** [comment]
> I think it is related to 
https://twitter.com/md__5/status/765072583351861248
https://twitter.com/md__5/status/765072699693469696

Those tweets have nothing to do with this.

**Comment by MegaFlary** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/e0e1771a6d74ca46433feb0235053eee6f792578

**Comment by Robotia** [comment]
This is now fixed, thanks to @MegaFlary :+1: 
Hotfix will be released soon
