### ISSUE TITLE
Thermos 58 Update

### ISSUE THREAD

**Issue by lilmoefow** [CyberdyneCC/Thermos#496]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/8U4Si55h
(That is specifically just the error being spammed in console. i can provide more of FML if it is required.)

**Explanation of issue:**
Just updated to Thermos 58 on our Beyond Reality server, and we were getting non stop console spam.  Something about thaumcraft golems and Essentials.   
**How to recreate this issue:**
Update your server to use Thermos-1.7.10-1614-server-58
**Modpack Name:** *(Only if public)*
Beyond Reality 2.4.1 R1
**Mods Installed:**

**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-1.7.10-1614-server-58
**Forge Version:**
forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by Robotia** [comment]
Can you give a longer log? It gets cut off at the important part.

**Comment by lilmoefow** [comment]
http://pastebin.com/7JT9acwV

Hope that is enough.

**Comment by Razorskills** [comment]
I hate how pastebin has a limit to the pastes. If you have a dropbox acc, you could put the whole log file in dropbox and link the file, it functions the same way as pastebin for reading it in web.

**Comment by iKaneki-Ken** [comment]
Wait, so from what I'm reading is the fake player is active, but isn't considered online? How does that work?

**Comment by Time6628** [comment]
Or use github gist.

**Comment by lilmoefow** [comment]
https://gist.github.com/lilmoefow/14a7737c02ca6ab708a3ecdf95e3ba33

What i was originally was pulling the log from was the latest one i had when i first noticed the issued and pulled the log file..

That there is the full log file start to stopping the server.

**Comment by Robotia** [comment]
Thanks!

**Comment by lilmoefow** [comment]
Thanks for the quick response and fix :+1:
