### ISSUE TITLE
Crash with Aether II

### ISSUE THREAD

**Issue by LeftBoy** [CyberdyneCC/Thermos#499]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/35QC5keC
**Mods Installed:**
Aether II, Biomes o plenty, chisel 2, oceancraft, CFM, CustomNPC, TinkerConstruct, BiblioCraft.
**Plugins Installed:**
AutoMessage, BanItem, ChatGame, ChatGuard, ClearLag, CombatTag, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, Jobs, MachineGuardReloaded, MaxBans, ModFixNG, PermissionsEx, PlugMan, PowerNBT, ProtocolLib, RandomTP, ScoreboardStats, ShoppingCartReloaded, SimpleClans, StatsPvP, Vault, WGExtender, WorldBorder, WorldEdit, WorldGuard
**Thermos Version:**
Latest Thermos-1.7.10-1614-57.zip

**Comment by spannerman79** [comment]
I would say its  some issue with a flying mob in Aether II from that crash log.

**Comment by Time6628** [comment]
Not thermos.
