### ISSUE TITLE
Error installations Skyblock 2.5

### ISSUE THREAD

**Issue by medaion** [CyberdyneCC/Thermos#500]
Good evening,
My question may seem stupid but I want a thermos versions compatible with modpack Skybloc 2.5
Is that compatible versions as to what days?

If so can you give me the link of the download.
Sorry for my english I'm french.

**Comment by Robotia** [comment]
Bonjour,

Ce n'est pas un soucis si vous êtes français, je peux comprendre.
Je ne suis pas sûr lesquels problèmes vous avez rencontre. Pouvez-vous les raconter?

Merci,

Robotia

**Comment by Time6628** [comment]
Sky Factory 2.5 works just fine with Thermos.

**Comment by alicheek** [comment]
@medaion make sure that Mobiuscore is disabled in the mods folder i think origionally they have that enabled and thermos doesnt work with the default version, its actually not needed.

**Comment by Robotia** [comment]
@medaion 
Est-ce que votre problème a été resolu?

Merci,

Robotia

**Comment by medaion** [comment]
Bonsoir , 
Merci d'avoir répondu aussi rapidement .
Je viens tout juste de faire le test avec ce que Alicheek as dit . 
Et oui le serveur fonctionne maintenant avec thermos merci beaucoup . 

C'étais juste mobiuscore qui causais le problème . 
Par contre le fait de désactivé cela  ne causeras pas d'instabilité ? 

Encore une fois merci beaucoup ! sans vous je serrais sans protections & sans plugin .

**Comment by Robotia** [comment]
Bonjour,

Il y a seulement un problème avec l'enlèvement de MobiusCore (duquel je connais). Opis ne marche pas quand MobiusCore n'est pas disponible.

Merci,

Robotia

**Comment by medaion** [comment]
Bonjours
Parfait , merci beaucoup d'avoir répondu a mes inquiétude du fait de le désactivé. 

Cordialement , medaion

**Comment by Robotia** [comment]
Ce n'est pas un problème! 

Je suis en train de fermer ce billet. Faire un comment ici si vous recontrez quelques autres problèmes avec SkyFactory 2.5. 
(I am about to close this ticket. Make a comment here if you encounter other problems with SkyFactory 2.5).
