### ISSUE TITLE
Server shuts down unexpectedly

### ISSUE THREAD

**Issue by Arobcher** [CyberdyneCC/Thermos#501]
**Server Log:** *(https://gist.github.com/Arobcher/bd5ac30058c0d3ec3a3a5d2f325d7d10)*

**FML Log(s):** *(https://gist.github.com/Arobcher/373e298d125ff29445e9e7acbf48214e)*

**Explanation of issue:*Abnormal server crashes*

**How to recreate this issue:*I do not know, but it can provide reports*

**Modpack Name:*http://www.filedropper.com/mods_15* *(Only if public)*

**Mods Installed:*
![9 aj4 tpyxj0t2k1lee0 m9](https://cloud.githubusercontent.com/assets/11995478/17899806/1f2eb134-698f-11e6-8b92-3854a41f63be.png)
*

**Plugins Installed:*
![djiaxa ba_7tx0aq 6bj d](https://cloud.githubusercontent.com/assets/11995478/17899697/c574ea0a-698e-11e6-9d82-39a59ceb9cc3.png)
*

**Warmroast Report:** *(Optional)*
[optionsshaders.txt](https://github.com/CyberdyneCC/Thermos/files/433025/optionsshaders.txt)

**Thermos Version:*Thermos-1.7.10-1614-57-server*

**Forge Version:*1.7.10-Forge10.13.4.1614-1.7.10*

**Comment by spannerman79** [comment]
This is not abnormal - you are using a modified version of forestry that hasn't been updated to use updated fuel burn - https://gist.github.com/Arobcher/373e298d125ff29445e9e7acbf48214e#file-gistfile1-txt-L308

https://minecraft.curseforge.com/projects/forestry/files/2320118 is the correct one to use.

**Comment by Arobcher** [comment]
Appear
The server is going slow. Last server tick was 38934ms ago
Last Tick: 1471946312511 Current Time: 14719463514445 Warning: 0000 Timeout: 90000
Then shut down the server, how to solve?

**Comment by Robotia** [comment]
@Arobcher the issue is the haveric mod, 
[This](https://gist.github.com/Arobcher/90a7d4d64fcbf72f82c02ea5381246fa#file-servercrash-L91) line shows that the server thread gets stuck on it.
