### ISSUE TITLE
RTG Generation is broken on Thermos (reopened)

### ISSUE THREAD

**Issue by NoireMann** [CyberdyneCC/Thermos#503]
**Explanation of issue:**
World generation and chunk populating partly fixed in #486 , but there are lots of generation problems still.

Lots of single unpopulated (bald) chunks without trees and decorations, weird tree and other things generation (trees are cut near the chunk borders)

Streams` rivers are generating, water is placed but cobblestone still spawns above the generated water.

**How to recreate this issue:**
Try to generate a world on Thermos 58 with RTG, Climate Control, Fastcraft and Streams (+Farseek)

**Mods Installed:**
RTG, Farseek, Streams, Climate control, Biomes o Plenty

**Plugins Installed:**
WorldBorder

**Thermos Version:** build 58

**Comment by spannerman79** [comment]
Dupe #486

**Comment by NoireMann** [comment]
Nope, this is the reopening of my #486 issue

**Comment by Robotia** [comment]
To reopen an issue on GitHub, you must click `Reopen issue` at the bottom of the page. Please do that with #486. 

Thanks,

Robotia

**Comment by NoireMann** [comment]
I tried to reopen the #486, but there is no any "reopen" button :C

**Comment by fewizz** [comment]
@NoireMann you can't, bcs @Robotia closed the issue.

**Comment by NoireMann** [comment]
Yea, but how should i make my issue actual again? This new thread was closed, and I can`t reopen the old one.

**Comment by Robotia** [comment]
Are you unable to reopen the issue? It might be because of repository permissions.

Est-ce que vous ne pouvez pas reouvrir le billet? Ca pourrait être à cause de permissions:

**Comment by NoireMann** [comment]
Yes, I am unable to do this, because this issue was closed by you, not me.
