### ISSUE TITLE
Koloboke startup issue

### ISSUE THREAD

**Issue by NDruce** [CyberdyneCC/Thermos#504]
NoClassDefFoundError: com/koloboke/collect/map/LongObjMap

Server log (see at end): http://pastebin.com/SU626VWi
Thermos build 58 (Forge 1614)

**Comment by spannerman79** [comment]
`25.08.2016 20:39:41 Caused by: java.lang.UnsupportedClassVersionError: com/koloboke/collect/map/LongObjMap : Unsupported major.minor version 52.0` Use Java 8

**Comment by Robotia** [comment]
@spannerman79 is correct, Java `1.7.0_51` is not supported. If you look [here](http://mcstats.org/plugin/Thermos), the majority of people are using Java 8.

**Comment by Bogdan-G** [comment]
as it does not sound strange but this library has 2 version build: J6-7 and J8-9

**Comment by Robotia** [comment]
You are expected to use Java 8.
