### ISSUE TITLE
Streams mod is corrupting world generation algorithms

### ISSUE THREAD

**Issue by NoireDvachevsky** [CyberdyneCC/Thermos#506]
**Explanation of issue:**

Streams mod is corrupting chunk generation while installed with RTG and Climate Control. Several chunks are bald and unpopulated. In addition, bukkit plugins based on a chunk-related things are not working properly. For ex: WorldEdit regeneration of chunks is broken: chunks are regenerating unpopulated (no matter, if this chunk has Streams river or not).

**How to recreate this issue:**
Try to generate a world with Streams mod and RTG installed. Pregenerate a piece of world with any pregen utils (Worldborder, Chunkgen. etc.) Or regenerate a single-chunk with bukkit plugin like WorldEdit.

The one thing that I could detect is the Spigot Watchdog report of server freeze - it has some Farseek related Exceptions: http://pastebin.com/FZbZccn2

**Mods Installed:**
RTG 1.1.1-1.7.10
BoP (Latest)
Climate Control (Latest)
Streams 0.2
Farseek

**Plugins Installed:**
Worldborder
WorldEdit
AsyncWE

**Thermos Version:**
58 Build

**Forge Version:**
1614

The reason why I create this issue on Thermos tracker in fact, that RTG devs are confirmed Streams mod as fully compatible with RTG. For some reason they are not working well together on Thermos. I guess thi is because of scala-nature of the Streams mod.

Thanks in advance,
Noire.

**Comment by iKaneki-Ken** [comment]
RTG is, from what I understand, is broken on both vanilla forge and Thermos.

**Comment by Sunconure11** [comment]
I can confirm this has happened on Vanilla too.

**Comment by NoireDvachevsky** [comment]
Yes, without Streams RTG is working fine. Except some mystical village bugs, but that is not very critical.

So, the point is - Streams this "bad boy".
