### ISSUE TITLE
Spigot /timings need updated

### ISSUE THREAD

**Issue by oaksvirals** [CyberdyneCC/Thermos#508]
Spigot has updated their timings feature so at the time being we're unable to use /timings.

Im using version: Thermos 1.7.10 Build 58 {Alpha) Forge 1614

**Comment by Robotia** [comment]
If you need timings right away, please build an unofficial Thermos. It was committed in https://github.com/CyberdyneCC/Thermos/pull/497 and will be available in the next public build release.
