### ISSUE TITLE
Server Starting Issue

### ISSUE THREAD

**Issue by RenInamori** [CyberdyneCC/Thermos#509]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/NRxyLwLY
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/Dp9zq4yC
**Explanation of issue:**
Started up the server after installing Thermos and after starting up it would say "A problem occured running the Server launcher.Exiting..."
**How to recreate this issue:**
Delete Libraries folder, drag Thermos-1.7.10-1614-server.jar into folder. Drag Libraries into folder as well. Change the startup code `http://pastebin.com/s746MCBG' to `http://pastebin.com/Qfi6XZJp`

Renamed the Thermos pack to Thermos-1.7.10-1614.jar
Started up the server and problem happened.
**Modpack Name:** *(Only if public)*
Skyfactory 2.5
**Mods Installed:**
http://pastebin.com/AbcJvtsd
**Plugins Installed:**
None
**Warmroast Report:** *(Optional)*

**Thermos Version:**
1614
**Forge Version:**
1614

**This is a brand new server, Never modified. All I did was install Thermos. Server was started up normally by its own serverstart.bat then thermos was added. I tried doing the opposite and having it launch thermos first, but the server still wouldn't startup"

**Comment by Robotia** [comment]
Remove MobiusCore from your mods folder. If you need it use [this](https://cdn.discordapp.com/attachments/172072987154055168/186577486593785857/MobiusCore-1.2.5-Thermos.jar) version.
