### ISSUE TITLE
spigot&bukkit dose not have org/bukkit/event/entity/EntitySpawnEvent

### ISSUE THREAD

**Issue by Himmelt** [CyberdyneCC/Thermos#510]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
`[ERROR]: [PlotSquared] Plugin PlotSquared v3.4.6-SNAPSHOT has failed to register events for class com.plotsquared.bukkit.listeners.EntitySpawnListener because org/bukkit/event/entity/EntitySpawnEvent does not exist.`
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:**

**How to recreate this issue:**

**Modpack Name:** *(Only if public)*

**Mods Installed:**

**Plugins Installed:**
[PlotSquared]
**Warmroast Report:** *(Optional)*

**Thermos Version:**
58
**Forge Version:**
1614

**Comment by djoveryde** [comment]
I think that version of plot squared is for 1.8.9+ only?

**Comment by linkinkov** [comment]
https://dev.bukkit.org/bukkit-plugins/plotsquared/files/25-3-1-8/ use this version

**Comment by Himmelt** [comment]
Oh,thank you.
