### ISSUE TITLE
Thermos-1.7.10-1558-server - Pixelmon NPC Crash (Possibly a Forge issue?)

### ISSUE THREAD

**Issue by pepsiisgross** [CyberdyneCC/Thermos#513]
You will receive NO SUPPORT if you do not follow the template below.

**Server Log:** http://pastebin.com/aDcLVQYq

**FML Log(s):** http://pastebin.com/xCsByhAa

**Explanation of issue:** When I battle with an NPC (gym leader) on Pixelmon, I'll beat the first pokemon and then it will keep doing the "Waiting..." screen, and then it'll eventually crash and the gym leader will win. 

**How to recreate this issue:** Make a gym leader in pixelmon, beat their first pixelmon in 1 move.

**Modpack Name:** *(Only if public)* Pixelmon-1.7.10-3.5.1-universal

**Mods Installed:** Pixelmon-1.7.10-3.5.1-universal

**Plugins Installed:** https://gyazo.com/3a01e7a290591482437ce1bb423740cf

**Warmroast Report:** *(Optional)*

**Thermos Version:** Thermos-1.7.10-1558-server

**Forge Version:** 1.7.10-Forge10.13.4.1558-1.7.10

**Comment by Time6628** [comment]
Bug with pixelmon.
