### ISSUE TITLE
InventoryClickEvent and uSkyBlock

### ISSUE THREAD

**Issue by ResponsibleBear** [CyberdyneCC/Thermos#514]
**Server Log:**
http://pastebin.com/haKCEuzV

**Explanation of issue:**
It seems that there is no necessary event in Thermos. Just change language in config uskyblock, example to fr or de never mind. And type /is in chat. Here we go.

**Plugins Installed:**
uSkyBlock v2.5.3

**Thermos Version:**
1.7.10-1614.58

**Comment by Time6628** [comment]
Try build 57.

**Comment by ResponsibleBear** [comment]
I try 54, 57, 58 build. Got the same error.

**Comment by SantaGitHub** [comment]
This bug was still to build 40,41,42,43.....

**Comment by KasperFranz** [comment]
Are you sure it is a bug in thermos? and not a problem in uSkyblock, have you tried the same setup on a vanilla 1.7.10 bukkit server?

**Comment by Time6628** [comment]
uSkyBlock doesn't support Thermos, try GPPSkyblock.

**Comment by SantaGitHub** [comment]
use ASkyBlock

**Comment by linkinkov** [comment]
Its language trouble just
