### ISSUE TITLE
Server Timeout/Crash

### ISSUE THREAD

**Issue by CobaltSparkz** [CyberdyneCC/Thermos#515]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

http://pastebin.com/4BmtmQ35

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

See above

**Explanation of issue:**

Server hung

**How to recreate this issue:**

N/A

**Modpack Name:** *(Only if public)*

CrundeeCraft

**Mods Installed:**

Pack Related

**Plugins Installed:**

http://prntscr.com/ceklvw

**Warmroast Report:** *(Optional)*

**Thermos Version:**

57

**Forge Version:**

1448

**Comment by Time6628** [comment]
PlayerAPI and galaticraft are the culprits, not thermos.
