### ISSUE TITLE
1.7.10 Pixelmon Thermos Conflicting

### ISSUE THREAD

**Issue by AnchorSam** [CyberdyneCC/Thermos#519]
**Server Log:**
http://pastebin.com/xkdXq1am

**FML Log(s):** 
http://pastebin.com/nuQTFpzX

**Explanation of issue:**
I think that Thermos is giving somehow conflicting with Pixelmon. When Thermos is being installed, throwing pokeballs at a pokemon will cause the pokeball and pokemon to disappear after not being caught.
**How to recreate this issue:**
By Installing Pixelmon -3.5.1, throwing a pokeball at a wild pokemon.

**Modpack Name:** *(Only if public)*

**Mods Installed:**
Pixelmon, Applied Energistics2, BiomesOPlenty, Carpenter's Blocks, MrCrayfish's Furniture, ChanceCubes, Extrautilities, Fastcraft, ItemFinder, Mantle, MapWriter, OpenBlocks, OpenModLib, PixelExtras, Pixelmon - 3.51, SpawnOfPsyduck, Tinker's Construct, VeinMiner, Waila, Wawla  
**Plugins Installed:**
None
**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-1.7.10-1614-server.jar
**Forge Version:**
forge-1.7.10-10.13.4.1614.jar (is not needed in main directory right?)

Thanks for the help

**Comment by Robotia** [comment]
Are you using Bungee?

**Comment by AnchorSam** [comment]
I'm using Bukkits I think.

**Comment by Time6628** [comment]
You're using Pixelmon with lots of other mods, which they do not recommend. Not a problem with thermos at all.

**Comment by AnchorSam** [comment]
But the things is that when I didn't used Thermos, the mods that I listed run fine. I will try to used pixelmon mod only and run and see if still has that problem.
