### ISSUE TITLE
Pixelmon 1.7.10 server is die.

### ISSUE THREAD

**Issue by YuriySimakov** [CyberdyneCC/Thermos#520]
[2016-09-13-7.txt](https://github.com/CyberdyneCC/Thermos/files/469449/2016-09-13-7.txt)

**Comment by KasperFranz** [comment]
follow the template - it is there for a reason and might de dupe of #519

**Comment by YuriySimakov** [comment]
But

**Comment by Robotia** [comment]
```follow the template```
