### ISSUE TITLE
Thermos 1.7.10

### ISSUE THREAD

**Issue by MacTirom** [CyberdyneCC/Thermos#521]
Please change it.

When i place a minecart or with the Traincraft Mod a train.
When I sit in there and then in the inventory of the Train Craft'm loco an item and then leave the server disappears, the locomotive and the item properly drop to the floor and when I get to the server again, it lies on the floor and is in the inventory of the Lok, and therefore then the item was doubled

Change it Minecart not disappear when leaving from the server but there remains so that you can no longer double the items in Traincraft.

I wrote with the programmers of Traincraft and they have told me that it would be up to Thermos and therefore should check with you.

**Comment by KasperFranz** [comment]
Follow The template you deleted while creating this issue :)?

**Comment by Time6628** [comment]
Please resubmit and follow the template.
