### ISSUE TITLE
Died all servers at the same time

### ISSUE THREAD

**Issue by Zoom4ikDan4ik** [CyberdyneCC/Thermos#524]
**Server Log: http://pastebin.com/H3V5M5BB**

**FML Log(s): http://pastebin.com/aquA1uFp**

**Explanation of issue: die server**

**Mods Installed: All the servers at once stopped, it is pointless to make a list of all servers**

**Plugins Installed: All the servers at once stopped, it is pointless to make a list of all servers**

**Watchdog spigot: http://pastebin.com/AaPntgQB**

**Thermos Version: Thermos-1.7.10-1614-server (latest build)**

**Comment by KasperFranz** [comment]
private pastes?

**Comment by Robotia** [comment]
It looks like your MySQL database is down.

**Comment by Zoom4ikDan4ik** [comment]
Now public pastes, sorry

**Comment by Zoom4ikDan4ik** [comment]
Perhaps, but before such was not, and if it was, the server worked without such disruptions.

**Comment by SantaGitHub** [comment]
Попробуй 58 версию.
Похоже что карта убитая в некоторых чанках.

**Comment by Time6628** [comment]
There is a problem with your databases.

**Comment by Shevchik** [comment]
What else did you expect when using network from main thread?

**Comment by spannerman79** [comment]
> Perhaps, but before such was not, and if it was, the server worked without such disruptions.

This is not a Thermos issue @Zoom4ikDan4ik 
This is an issue with your MySQL connections - nothing else is wrong here except something that you have to resolve yourself as its not code base related to Thermos.

This issue should be closed.
