### ISSUE TITLE
Thermos Build 57 + Opis/Mobius Fix

### ISSUE THREAD

**Issue by Solidflip** [CyberdyneCC/Thermos#530]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
======
On Server: Thermos Fixed MobiusCore + Regular OPIS
On Client: Regular MobiusCore+ Regular OPIS
 log : http://pastebin.com/7GJw18vt
======
On Server: Thermos Fixed MobiusCore + Regular OPIS
On Client: Regular MobiusCore + MAPLESS OPIS from https://github.com/CyberdyneCC/Thermos/issues/137#issuecomment-241874398
http://pastebin.com/vJSEw7kH (console log as no crash log was generated)
-----------
On Server: Thermos Fixed MobiusCore + Regular OPIS
On Client: No Mobius Core + Mapless OPIS mentioned above
On this one the client is able to join the server, but once they type /opis they crash after the console spits out this: http://puu.sh/rgovV/69136614fc.png

also there is no crash log, but there is a jumbed mess of a client log: http://pastebin.com/zxebQNRZ
I believe the important part that references OPIS is here: http://pastebin.com/gjyQW56x

**Explanation of issue:**
Tried following @Time6628 's advice about OPIS https://github.com/CyberdyneCC/Thermos/issues/409#issuecomment-226912906 but clients still cant connect with opis in
**How to recreate this issue:**
use opis and attempt to join server and use /opis

**Modpack Name:** *(Only if public)*
FTB Infinity Evolved 2.6.0

**Mods Installed:**
all in modpack
**Plugins Installed:**
this happens the same with all of our plugins and with none, tried both.

**Thermos Version:**
Build 57 

**Forge Version:**
1614

I tried to be as thorough as possible on this one, I have tried the solutions found on this github but have not found success. If anyone could help with anyway they got it to work for them i would appreciate it.

**Comment by Solidflip** [comment]
BTW i have no idea why this is all formatted weird.....my bad

**Comment by Time6628** [comment]
Replace the Opis on the server with the Thermos fixed Opis. You do **_NOT_** need to change anything on the client. If you are on a dedicated server, use WarmRoast instead.
https://github.com/Robotia/WarmRoastSetup

**Comment by Solidflip** [comment]
when i download the mobius from the front page of this github its only mobiuscore. Could you direct me to the opis link? or are they bundeled?

**Comment by Time6628** [comment]
I meant MobiousCore.

**Comment by Solidflip** [comment]
@Time6628  ive done that, i put the thermos Mobius on the server + regular OPIS and got the crashes above.

**Comment by Time6628** [comment]
Then use WarmRoast, or post an issue on the Thermos Opis repo.

**Comment by Solidflip** [comment]
Thermos opis repo? Could you link me where that is?

**Comment by Time6628** [comment]
https://github.com/CyberdyneCC/MobiusCoreTH

**Comment by Solidflip** [comment]
@Time6628  i have the Thermos Mobius core like you suggested, but the above crashes still happen. Is there some solution or is opis not supported by Thermos?

**Comment by Time6628** [comment]
I don't use Opis or MobisCore on any of my servers. I use WarmRoast as I suggested above.

**Comment by Solidflip** [comment]
@Time6628 I understand, In the meantime is there anyway we can re-open this issue as it is not resolved? Ive tried warmroast and it didnt meet our needs as well as opis did, and once thermos said it supported it we jumped at the chance

**Comment by Robotia** [comment]
Are you sure you have mapless? The crash has map writer in it

**Comment by FinePoints** [comment]
@Robotia Yeah we have the Mapless.  When we run the /opis command. We get forced disconnected saying A fatal error has occurred, this connection is terminated.

**Comment by JTLWebDesign** [comment]
FinePoints, were you able to get this to work? I'm running Thermos 1614 build 57 and I have the fixed MobiusCore and normal OPIS and my server starts, but when I try and run /opis with either the normal or mapless version on my client, I crash with a fatal error

**Comment by FinePoints** [comment]
I ended up with a dirty fix for it. I had the fixed Mobius and normal opis.   I ended up changing my texture pack to faithful and it worked like a charm. Venilla texture kept the crashing.
