### ISSUE TITLE
World.regenerateChunk

### ISSUE THREAD

**Issue by misterzym** [CyberdyneCC/Thermos#532]
** Explanation of issue: **
All plug-ins using World.regenerateChunk function behave very strangely! When I use it in the game okay. But when I'm out of the field of use, to return me in for a surprise - all actions World.regenerateChunk canceled!

**How to recreate this issue:**
1. Set the example WorldEdit.
2. Make any area set 0.
3. Make this area // regen.
4. Log out of the game (that would be the area was unloaded)
5. Go back to the game after a while.

**Mods Installed:**
backpack-2.0.1-1.7
Balkons-Veapon-1.7.10
CustomMobSpawner 3.3.0
dungeonpack_1.7.10_1.0
Mantle-1.7.10-0.3.2
roguelike-1.7.10
terraincontrol-forge-2.6.3
twilightforest-1.7.10-2.3.7

**Plugins Installed:**
KommandBook
MarriageMaster
Towny
WorldBorder
worldedit
worldguard
WGFix

**Thermos Version:**
Thermos-1.7.10-1614.34-server

**Forge Version:**
1.7.10 1614

**Comment by spannerman79** [comment]
You also need the Worldedit mod on the server - not just the bukkit plugin

Non Thermos issue

**Comment by misterzym** [comment]
If I use a version of the plug together with the mod, it leads to such a situation - the results of any commands are not displayed in the chat, one to all of them are displayed in the console. And all this without any errors on the console. In addition ax ceases to divide the field, it begins to destroy the blocks.

**Comment by Bysokar** [comment]
@spannerman79 @Time6628 I can second this also - have seen strange behavior in the last couple of builds.
The mod is not required for use at all in earlier builds of Thermos and plugins which depend on WorldEdit (there are many) don't work with the mod.

Solution for me has been to downgrade Thermos.

**Comment by iKaneki-Ken** [comment]
Funny, I'm using World Edit both plugin and mod and everything works perfectly fine, Try cycling through the mod and plugin until you find a working combination.

**Comment by Bysokar** [comment]
This is an issue with the Bukkit world.regeneratechunk method, not WorldEdit.

**Comment by Bysokar** [comment]
Also, I was simply saying plugins depending for WorldEdit require the plugin - not that the mod was bad haha

**Comment by misterzym** [comment]
i write mini plugin with worldEdit API
`WorldEditPlugin worldEditPlugin = null;
		worldEditPlugin = (WorldEditPlugin) Custom.serv.getPluginManager().getPlugin("WorldEdit");
		Selection sel = worldEditPlugin.getSelection(player);
		Selection selection = new CuboidSelection(sel.getWorld(),sel.getMinimumPoint(), sel.getMaximumPoint());
 Region region = selection.getRegionSelector().getRegion();
 region.getWorld().regenerate(region,sessionsWE);
`
and this work don't have any problem!

**Comment by Bysokar** [comment]
@misterzym Have you tried logging out, coming back a minute later (after regenerating) ?
For me the regeneration was not saved, and the chunk reverted back to what it was.

Doesn't happen on earlier Builds (46).

**Comment by misterzym** [comment]
@Bysokar yes, WE API saved all regeneration.
i logging out and login and restart server with/with out me
source in up - save all.

**Comment by Bysokar** [comment]
@misterzym 2 more questions then, 
1. Are you using a bukkit plugin like multiworld to generate worlds? 
2. Are  you using B58?

**Comment by misterzym** [comment]
@Bysokar 
1. no, i have mods generate multiworld (twilige forest and more)
2. yes

**Comment by Bysokar** [comment]
@misterzym can you test once more with a multiworld or multiverse (Bukkit) generated world?

**Comment by Bysokar** [comment]
Ok, so looking at your code it isn't actually related to te Bukkit regenerate chunk method it seems. Your using the world edit API regeneration functions, not the native Bukkit API (it works in chunks, your working with regions).
