### ISSUE TITLE
Can't start the server under UTF8

### ISSUE THREAD

**Issue by UzminTid** [CyberdyneCC/Thermos#533]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/UzminTid/a9ba52483c8887523ec774068c6222f6
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/UzminTid/935b8a57880c9bf6539d03db5fe5d323
**Explanation of issue:**
I have  a Ubuntu server and i turn it into Uft-8( var/lib/locales/supported.d/local  zh_CN.UTF-8 UTF-8)
When i start Thermos with the command _"java -Xmx6G -jar -Thermos.jar"_
it crash just like the log says

**How to recreate this issue:**
1.An utf8 ubuntu server 
2.Start the Thermos with either the minimum command or the command in the "Installing Thermos"wiki
3.Occur
**Modpack Name:** *(Only if public)*
No
**Mods Installed:**
No
**Plugins Installed:**
No
**Warmroast Report:** *(Optional)*
No yet
**Thermos Version:**
Thermos-1.7.10-1614-server.jar
**Forge Version:**
1614

**Comment by spannerman79** [comment]
https://gist.github.com/UzminTid/935b8a57880c9bf6539d03db5fe5d323#file-fml-server-1-log-L2
`Java is OpenJDK 64-Bit Server VM, version 1.7.0_111`
Use JDK8 http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Non thermos issue
