### ISSUE TITLE
GSON 

### ISSUE THREAD

**Issue by Slixe** [CyberdyneCC/Thermos#534]
**Server Log:** [20:21:29] [Server thread/ERROR]: [Factions v1.8.2] GSON lib not found. Your CraftBukkit build is too old (< 1.3.2) or otherwise not compatible.
[20:21:29] [Server thread/INFO]: [Factions v1.8.2] Now I suicide!
[20:21:29] [Server thread/INFO]: [Factions] Disabling Factions v1.8.2
[20:21:29] [Server thread/INFO]: [Factions v1.8.2] Disabled
**FML Log(s):** 

**Explanation of issue:**

**How to recreate this issue:**

**Modpack Name:** No modpack

**Mods Installed:** No mods

**Plugins Installed:** Factions, Essentials, WorldBorder

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-1.7.10-1614
**Forge Version:**
1.7.10-1614

**Comment by Time6628** [comment]
Use an older factions version.

**Comment by Slixe** [comment]
but this Factions is modified :/
