### ISSUE TITLE
Server crash on player join

### ISSUE THREAD

**Issue by rinart73** [CyberdyneCC/Thermos#535]
**Crash Report:** http://pastebin.com/BP79Bkc0

**Server Log:** http://pastebin.com/nWvauR7N

**FML Log(s):** http://pastebin.com/YxPdj6yq

**Explanation of issue:** When player tries to connect to the server, server crashes. I know that TerraFirmaCraft causes this, cause there is no other mods or plugins and without this mod everything works.
I also know that TerraFirmaCraft works fine on Forge server and [This Cauldron](https://sourceforge.net/projects/cauldron-unofficial/files/1.7.10/)
So I suppose we have some Thermos Forge incompatibility here?

**How to recreate this issue:** Install TerraFirmaCraft-0.79.29.922 (both client and server of course) and try to log in

**Modpack Name:** *(Only if public)* None

**Mods Installed:** TerraFirmaCraft-0.79.29.922

**Plugins Installed:** None

**Thermos Version:** 1.7.10-1614 build 57 and 1.7.10-1614 build 58

**Forge Version:** 1.7.10 - 10.13.4.1614

**Comment by SantaGitHub** [comment]
Delete world and gen new world

**Comment by rinart73** [comment]
It doesn't work. I tried several times.

**Comment by Time6628** [comment]
Incompatible ASM.

**Comment by rinart73** [comment]
So.. can this be solved? I suppose it can, because it works on older Cauldron forks.

**Comment by Time6628** [comment]
Not unless you fix the mod yourself.
