### ISSUE TITLE
Server Crash on Join

### ISSUE THREAD

**Issue by JamiePhonic** [CyberdyneCC/Thermos#537]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/JamiePhonic/8fac2acbac317a54e9c0bcf09ca7c270#file-latest-log

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/JamiePhonic/8fac2acbac317a54e9c0bcf09ca7c270#file-fml-server-latest-log

**Explanation of issue:**
Server Crashes when a player connects
Crash Log: https://gist.github.com/JamiePhonic/8fac2acbac317a54e9c0bcf09ca7c270#file-crash-2016-09-28_11-16-32-server-txt

**How to recreate this issue:**
Connect to the server

**Modpack Name:** *(Only if public)*
TechNodefirmacraft - 2.21.9 (Recommended modset, minus opis, mobius core and fastcraft)

**Mods Installed:**
https://gist.github.com/JamiePhonic/8fac2acbac317a54e9c0bcf09ca7c270#file-mod-list-txt

**Plugins Installed:**
NONE

**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-1.7.10-1614-57
Thermos-1.7.10-1614-58

**Forge Version:**
1-7-10 - Forge 1614

**Comment by Robotia** [comment]
Add the -noverify option

**Comment by JamiePhonic** [comment]
Added `-noverify` before the `-jar` argument amd started server. Issue seems resolved.
