### ISSUE TITLE
Server Unknow crash (JAVA)

### ISSUE THREAD

**Issue by JamiePhonic** [CyberdyneCC/Thermos#539]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

Explanation of issue:
Server will randomly crash with no evident cause.
Server and Forge logs are not included becuase the crash is happening in the JVM and not Thermos itself, so there are no Server or Forge logs. There is some strange spam in the console though
`RECURSION LIMIT 240 REACHED`

HS_ERR and REPLAY logs: https://gist.github.com/JamiePhonic/77e974f4ccbcbe8aa66c316041e325fb
A dump file is also available, however its 8GB in size (Same as the -Xmx size)

How to recreate this issue:
Connect to the server and wiat

Modpack Name: (Only if public)
TechNodefirmacraft - 2.21.9 (Recommended modset, minus prattle and fastcraft)

Mods Installed:
https://gist.github.com/JamiePhonic/8fac2acbac317a54e9c0bcf09ca7c270#file-mod-list-txt

Plugins Installed:
AsyncWorldEditInjector, WorldEdit, Questioner, GroupManager, BukkitCompat, OniCommands, Lockette, Votifier, WorldGuard, AsyncWorldEdit, StatRanks, BanItem, SignEditor, Vault, GriefPrevention, MassiveCore, ChestShop, Essentials, Towny, LongerDays, TownyChat, VanishNoPacket, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, RandomTeleport, EssentialsSpawn, EnjinMinecraftPlugin

(I will try removing plugins and seeing if the crash persists and update this post with the results)

Warmroast Report: (Optional)

Thermos Version:
Thermos-1.7.10-1614-57
Thermos-1.7.10-1614-58

Forge Version:
1-7-10 - Forge 1614

**Comment by Robotia** [comment]
It's related to net.minecraft.entity.player.EntityPlayerMP::func_71127_g as indicated by the report you shared. Have you tried running it on your personal computer or another system to see if the problem is unique to the verison of Java you have on your Windows Server?

**Comment by JamiePhonic** [comment]
Same issue occurs both on my windows 10 pro machine and my windows 2012 server
Removing plugins has no effect.

What appears to happen is when a player joins, the server is ok, then after so long the console spams `RECURSION LIMIT 240 REACHED` and eats up memory until the JVM crashes

**Comment by Bogdan-G** [comment]
@JamiePhonic 
>RECURSION LIMIT 240 REACHED

1) you up _stacksize_ in thread? look `-XssNk`(N - number, and oher)
2) you testing other GC(G1GC dont recommend Oracle if small heap(heap<16gb)? off 32bit reference(flag jvm: `-XX:-UseCompressedOops`)? del flags `-Xms2G -XX:hashCode=5`? update JVM to 101 build? up `pagefile.sys` size?
>Mods Installed:

3) in server-side you remove client-side mods and update mods(if there is)?
4) ASM inject cross-mod issue? ships mod gmm..

**Comment by JamiePhonic** [comment]
I'm using the reccommended launch options from step 5 of `http://cyberdynecc.github.io/Thermos/install` with the -noverify option added.
I will try adding `-Xss512k` and removing `-Xms2G -XX:hashCode=5`

Java is already 8.0-101
There are no client mods installed on the server, the mods are all the latest version i can find.
I will also try removing the ships mod.

**Comment by Bogdan-G** [comment]
>I'm using the reccommended launch options

reccommended != compulsory(required), you can spare time explore question about the choice of garbage collection and how to specifically fit your case. From myself(my imho) i will say: if you use more than 30 mods(not FML list, real mods, not include core/lib/addons) that will be worse g1gc clean up the garbage, CMS-gc even better in this regard, even in 16gb heap.

_offtop:_
>-XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat

meh, options default true in JVM(7/8), endble `G1GC` dont off options.
