### ISSUE TITLE
Thermos Crash...

### ISSUE THREAD

**Issue by GabrielGamer66** [CyberdyneCC/Thermos#542]
**Server Log: http://pastebin.com/fDgcKy6w 

**FML Log(s): http://pastebin.com/S5RFAZQr

**Explanation of issue: It just happened

**How to recreate this issue:**
**Mods Installed:
Immersive Enginering
IndustrialCraft 2
Forestry
BuildCraft
RailCraft
Mr Crayfish's Furniture mod
...

**Plugins Installed: None

**Thermos Version: 58

**Forge Version: 1614

**Comment by spannerman79** [comment]
`[18:56:09] [main/INFO] [FML/]: Loading tweaker shadersmodcore.loading.SMCTweaker from ShadersModCore-v2.3.31-mc1.7.10-f.jar`

Why are you running a client side only mod on a server? A server has no use for shaders............

**Comment by SantaGitHub** [comment]
@spannerman79 stupid Russian schoolboy

**Comment by spannerman79** [comment]
You are a moron @SantaGitHub  - I am not russian.

**Comment by Eufranio** [comment]
Send the crash-report and please use hastebin.com

**Comment by Robotia** [comment]
```[22:47:56] [Spigot Watchdog Thread/ERROR]:      logisticspipes.ticks.ServerPacketBufferHandlerThread.clear(ServerPacketBufferHandlerThread.java:339)
```
Logistics Pipes is at fault, the thread hung when it was created.
