### ISSUE TITLE
com/koloboke/collect/map/LongObjMap

### ISSUE THREAD

**Issue by colt05-usr** [CyberdyneCC/Thermos#543]
**Server Log:**
https://gist.github.com/colt05-usr/a1b012a6893cbe141689f238a5a058f1
**FML Log(s):**
`The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.`
**Explanation of issue:**
Thermos errors with "java.lang.ClassNotFoundException: com.koloboke.collect.map.LongObjMap" when starting the server. I cannot use the normal ThermosServer setup because when running without using -Xmx1024M the server runs out of memory.
**How to recreate this issue:**
Install Java 8  
Download Thermos  
Run `java -Xmx1024M -jar Thermos.jar`  
**Mods Installed:**
MCA
Orespawn
RadixCore
DecoCraft
Crayfish's Furniture Mod  
**Plugins Installed:**
None  
**Thermos Version:**
1.7.10-1558  
**Forge Version:**
7.99.4.1614

**Comment by spannerman79** [comment]
Dupe #504

**Comment by colt05-usr** [comment]
#504 said to install Java 8 which I have.

**Comment by Robotia** [comment]
Did you install the latest libraries?

**Comment by colt05-usr** [comment]
I downloaded the ThermosServer repo is that outdated?

**Comment by Robotia** [comment]
The libraries zip file included with the release jar on this repo has the latest libraries

**Comment by colt05-usr** [comment]
It worked! Thanks @Robotia!
