### ISSUE TITLE
Crash, don't know why...

### ISSUE THREAD

**Issue by shadow2921** [CyberdyneCC/Thermos#544]
**Server Log:** https://gist.github.com/shadow2921/732ed6a22be500136f05122ec78f7fb7

**FML Log(s):** https://gist.github.com/shadow2921/732ed6a22be500136f05122ec78f7fb7

**Explanation of issue:**When i start the server, it seems on, but when i want to join it, it's say "timed out" and after that server crash...

**How to recreate this issue:**

**Modpack Name:** *(Only if public)* Private :/

**Mods Installed:**  https://www.dropbox.com/s/rdsv3gid1qhl6wl/serveur%20fts.zip?dl=0 (mods) + http://pastebin.com/pc7y66Gi

**Plugins Installed:** no plugins

**Warmroast Report:** *(Optional)* /

**Thermos Version:** Thermos-1.7.10-1614-57

**Forge Version:** 1.7.10 (1614)

I'm french, sorry for my english: I try to create a server since 2 day, i saved off a lot of problem, but i never saw this one :/

Thanks all !

**Comment by Time6628** [comment]
Your server is probably stalling out, since you provided no crash logs. 
Use player's sampler mod to get a stall report http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820

**Comment by shadow2921** [comment]
I tried with fastcraft and here is the result: 

https://gist.github.com/shadow2921/d17e5d07713ff093efaabc1d3cf92ace

I stoped my server because my log file is so big (250 MO)

**Comment by Time6628** [comment]
You're server is not crashing at all.

**Comment by shadow2921** [comment]
It's just a part, if i let my server on, i have a really big log file = 500 600 Mo, and he start, start, again and again, never stop :/

**Comment by Time6628** [comment]
Your startup looks entirely normal, your server does not crash, and you've provided no logs to support or even suggest a crash. Probably just gonna lock this issue unless you provide the proper logs.

**Comment by Robotia** [comment]
Bonjour,

Quels problèmes avez-vous rencontré? Pouvez-vous nous donner le fichier pour le crash? Pas le latest.log mais le fichier dans crash-reports correspondant avec la date et l'heure.

Merci d'avoir utilisé Thermos et bienvenue à la communauté.

Robotia

**Comment by shadow2921** [comment]
Sorry, i work everyday i wasn"t here for explain my problem:

I restart my server, delete the map (cause of some bugs), and now i have no bug.
If i have something, i tell u .

Cordially,
Ps: Sorry for my English x)

**Comment by shadow2921** [comment]
Now i have an error when i try to connect on my serv.
A fatal error has occured, this connection is terminated...
I don"t know if thermos do that :/.
Do you want my log file ?

Cordially.

**Comment by Robotia** [comment]
@shadow2921 
S'il vous plaît nous donner le log fichier:

**Comment by shadow2921** [comment]
It was a just a mistake . I think all is good now ;) thank for your help.  Im sorry if i solved it myself, but i can"t wait x) If i have something new, I tell you ! :+1:

**Comment by Robotia** [comment]
(Woops)
