### ISSUE TITLE
How to set skip tile entities ticks to false?

### ISSUE THREAD

**Issue by YuriySimakov** [CyberdyneCC/Thermos#545]
Hello to Everybody!
How can I set skip tile entities ticks to FALSE in tileentities.yml (server folder)
I tried change it, but file changed to default after server restarting...

**Comment by KasperFranz** [comment]
You have to do it when the server is down,  as it writes the current values to the file. 

På 5. okt. 2016 7.10 PM, YuriySimakov <notifications@github.com> skrev:

Hello to Everybody!
How can I set skip tile entities ticks to FALSE in tileentities.yml (server folder)
I tried change it, but file changed to default after server restarting...
