### ISSUE TITLE
opis crash server

### ISSUE THREAD

**Issue by origamerpro** [CyberdyneCC/Thermos#546]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/hXbsw5VH
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:**
crash server
**How to recreate this issue:**
use in client command /opis wait 3-5 sec.
**Modpack Name:** *(Only if public)*

**Mods Installed:**mobius core - thermos fix opis Client and server

**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:**58

**Forge Version:**1644

**Comment by Time6628** [comment]
https://github.com/CyberdyneCC/MobiusCoreTH

**Comment by origamerpro** [comment]
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff2e6c08afc, pid=29203, tid=140680448018176
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x365afc]  GraphBuilder::arithmetic_op(ValueType*, Bytecodes::Code, ValueStack*)+0x9c
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/mineserver1/hs_err_pid29203.log
#
# Compiler replay data is saved as:
# /home/mineserver1/replay_pid29203.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by origamerpro** [comment]
no. that dont fix problem. crash all time. run opis with 3+ peoples online = crash.

**Comment by origamerpro** [comment]
1

**Comment by Time6628** [comment]
Try WarmRoast, I do not use Opis myself so I cannot help you.
