### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by colt05-usr** [CyberdyneCC/Thermos#547]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
https://gist.github.com/colt05-usr/1deaf82fb507af5634a5cbb74dc0b91f
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
FML didn't completely start yet

**Explanation of issue:**
I get this error after starting a server a few times then I must copy my mods folder, plugins folder, and config files into a new ThermosServer folder (this has happened once before).
**How to recreate this issue:**
Unknown
**Mods Installed:**
No mods loaded before the crash
**Plugins Installed:**
Essentials
MultiWorld
WorldEdit
WorldGuard

**Thermos Version:**
1.7.10-1614.58
**Forge Version:**
7.99.4.1614

**Comment by Time6628** [comment]
Delete cauldron.yml
