### ISSUE TITLE
Crash with DragonAPI 16d

### ISSUE THREAD

**Issue by aetherpirate** [CyberdyneCC/Thermos#549]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

http://pastebin.com/APvqHEJe

http://pastebin.com/E9htdbxp

**Explanation of issue:**

Thermos 57 crashes with latest DragonAPI (16d) 
* 58 produces same issue

Tested with only Reika's mods (DragonAPI, RotaryCraft, ReactorCraft, ElectriCraft) all 16d. 

**How to recreate this issue:**

Start server

**Modpack Name:** *(Only if public)*

used a test environment to isolate issue. 

**Mods Installed:**

Only the four I listed. 

**Plugins Installed:**

none

**Warmroast Report:** *(Optional)*

**Thermos Version:**

57 (58 same issue)

**Forge Version:**

1614

**Comment by Time6628** [comment]
https://github.com/CyberdyneCC/Thermos/issues/90#issuecomment-252454547
