### ISSUE TITLE
Server stall - Generation issues

### ISSUE THREAD

**Issue by Rubbertjuh** [CyberdyneCC/Thermos#550]
**Server Log:** _(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))_
Stall report 1: http://pastebin.com/HPn8ehUD
Stall report 2: http://pastebin.com/Q7NTBvr8
Stall report 3: http://pastebin.com/FU8HUy2J

**FML Log(s):** _(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))_
N/A

**Explanation of issue:**
Server seems to randomly stall, most of the times it's a few times after each other. I think this has to do with a chunk error, but I'm not sure. I come here seeking advice and guidance, hopefully somebody in this community can get a grasp on it and can be explain how these occur or how I can prevent them next time. 
I'm reporting this here because I am unsure if this is a thermos issue or not, it might very well be. 

**How to recreate this issue:**
Unsure how to recreate this issue, it just appears out of random.

**Modpack Name:** _(Only if public)_
Tekkit Legends [http://www.technicpack.net/modpack/tekkit-legends.735902](url)

**Mods Installed:**
http://hastebin.com/mojozutesa.coffeescript

**Plugins Installed:**
N/A

**Warmroast Report:** _(Optional)_
N/A

**Thermos Version:**
Thermos version 57

**Forge Version:**
Forge version 1710

Additional:
Once again, I'm not pointing fingers at anyone.

**Comment by Robotia** [comment]
I have seen this before, not sure what issue but I thought we had fixed it.
Will be looking into this.

**Comment by Rubbertjuh** [comment]
Thanks for the reply @robotia , hope looking into it will have a positive outcome! 
Tell me if you need more information or if I can help diagnose

**Comment by chezpaul** [comment]
Hey Robotia, I just wanted to pop in and say thanks for still working on this.
I'm always patiently waiting for updates to come out.
Thanks a ton for keeping up the good work.

**Comment by Robotia** [comment]
Thank you for your appreciation!
I am currently going through all the past commits from the beginning of KCauldron on https://github.com/CyberdyneCC/ThermosRebased
It will take some time to prepare the next release, but after my tests this week, I will be doing some more work on it.
36 out of 800 some commits so far, but it will be finished!
