### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by linkinkov** [CyberdyneCC/Thermos#551]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/8unanq2P

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:**

**How to recreate this issue:**

**Modpack Name:** *(Only if public)*

**Mods Installed:**

**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:**
57
**Forge Version:**
1614

**Comment by linkinkov** [comment]
Can anybody say that a function crash the server?

**Comment by SantaGitHub** [comment]
MODS?
PLUGINS??
WHERE?

**Comment by Robotia** [comment]
Привет @linkinkov ,
Did the server **crash** or **freeze**?

**Comment by linkinkov** [comment]
@Robotia freeze and then crash

**Comment by Robotia** [comment]
@linkinkov Where is the crash log?

**Comment by linkinkov** [comment]
@Robotia dont have crash, just stal report.
But now i fixed that problem. Its was custom generator of animal
