### ISSUE TITLE
Fault in Thermos launch command

### ISSUE THREAD

**Issue by Ionaru** [CyberdyneCC/Thermos#552]
When following the instruction on how to install Thermos on my server, I got the error "Failed to load main Class", after some debugging and trying different things I noticed that the launch command (you call it script) I copied from your website (http://cyberdynecc.github.io/Thermos/install) does not work.

Reason:
Between" -XX:MaxMetaspaceSize=2048m" and "-XX:+AggressiveOpts" there are 2 spaces where there should only be one. Java wasn't able to load the main Class because the command wasn't parsed correctly.

Please fix this as soon as possible because this could be affecting many people using your server software.

**Comment by Robotia** [comment]
We changed that a long time ago everywhere else. I think it was just an oversight on our part.
