### ISSUE TITLE
Server crash after update

### ISSUE THREAD

**Issue by FloppyDi** [CyberdyneCC/Thermos#555]
http://pastebin.com/88NGRYA9 crash log
http://pastebin.com/7JpMURqJ mod list

Server crash after the update 58

**Comment by Time6628** [comment]
You need to install the new libraries.

**Comment by spannerman79** [comment]
`Caused by: java.lang.UnsupportedClassVersionError: com/koloboke/collect/map/hash/HashLongObjMaps : Unsupported major.minor version 52.0`

Update to Java 8
