### ISSUE TITLE
Allow use of /restart on windows servers

### ISSUE THREAD

**Issue by martmists** [CyberdyneCC/Thermos#561]
The name of the restart script is defined as `start.sh` right [here](https://github.com/CyberdyneCC/Thermos/blob/71531cf7038e1d03f8f4f6a15a96cbca57f45153/src/main/java/org/spigotmc/SpigotConfig.java#L177). However, this only works on Mac and Linux. (And Linux subsystem on windows but not everyone uses windows 10 for their servers)
Please adjust this so it will use `start.bat` instead on windows platforms.

**Comment by Time6628** [comment]
Or, you could change it yourself in the config file(spigot.yml). Also, it's best not to use /restart as it can cause problems.

**Comment by Robotia** [comment]
https://github.com/CyberdyneCC/ThermosServer has the spigot.yml configuration and a launch.bat which should work fine.
