### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by LeftBoy** [CyberdyneCC/Thermos#566]
Crash-report:
http://pastebin.com/h4y3gua9
Server.log:
http://pastebin.com/G0NHeN9f
All plugins and mods in crash-report.
One week I haven't work with the server, today sharply server began to be crashed. Need a help.

**Comment by LeftBoy** [comment]
Okay, DailyBonus plugin do this crash.

**Comment by spannerman79** [comment]
`java.lang.NullPointerException: Nodes must be provided.`
Non thermos issue.  NPE= Plugin issue.

This issue should be closed.

**Comment by Rubbertjuh** [comment]
I'm having issues with the plugin DailyBonus plugin as well. 
What modpack are you running? 

DailyBonus does not want to support Modded servers and keeps saying that it's Thermos its fault.

**Comment by LeftBoy** [comment]
I removed dailybonus but the server all the same crashes

**Comment by LeftBoy** [comment]
All my mods are described in my crash-report.

**Comment by Robotia** [comment]
@LeftBoy The crash is because you have incorrect values in your `cauldron.yml`:
```    at net.minecraftforge.cauldron.configuration.ConfigBase.save(ConfigBase.java:70)```

**Comment by LeftBoy** [comment]
Later a long time I have found out the reason of a crash. It's was fires from mod of Thaumic Tinkerer + save value in bukkit.yml.          
Close theme.
