### ISSUE TITLE
[Bug] Hillary Clinton is losing the elections 

### ISSUE THREAD

**Issue by Eufranio** [CyberdyneCC/Thermos#571]
**Explanation of issue:**
Hillary Clinton is losing the elections ATM, this shouldn't happen. Trump will become the new president of USA.

**Comment by spannerman79** [comment]
WTF does this have to do with this issue tracker??

**Comment by Eufranio** [comment]
Robotia may have the fix, he fixes everything.

**Comment by ccxufo** [comment]
WTF does this have to do with this issue tracker??

**Comment by LorenzoDCC** [comment]
It's not a bug; it's a feature. Read the ingame manuals. Make Minecraftia Great Again.

**Comment by Eufranio** [comment]
Okay thanks Lorenzo, I'm going to report this to the mod autor.

**Comment by LorenzoDCC** [comment]
author*

**Comment by Robotia** [comment]
It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.

**Comment by evernife** [comment]
Trump > Clinton!

**Comment by bookerthegeek** [comment]
@BookerTheGeek 

Tagging myself so I can find this later.
