### ISSUE TITLE
java.lang.NoClassDefFoundError with Alpha58

### ISSUE THREAD

**Issue by Maxdg** [CyberdyneCC/Thermos#575]
**Server Log:** http://pastebin.com/00VhBg2f

**FML Log(s):** http://pastebin.com/wW0uBj2V http://pastebin.com/paHn9NVM

**Explanation of issue:**

    Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpe

        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.
    ava:25)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper
    java:12)
    Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
    Press any key to continue . . .

**How to recreate this issue:**
Use this launcher script:
http://pastebin.com/sfM9wbqj
With Build 58(Alpha) and the respective Libraries folder

**Modpack Name:** *(Only if public)*
The 1.7.10 Pack

**Mods Installed:**
Besides the regulars in The 1.7.10 pack we have also installed Railcraft and Immersive Engineering

**Plugins Installed:**
None

**Warmroast Report:** *(Optional)*
None

**Thermos Version:**
Thermos Build 58 (ALPHA)
1614-server

**Forge Version:**
forge-1.7.10-10.13.4.1614-1.7.10-universal

**Comment by KasperFranz** [comment]
You need to have the libraries installed (same as on #136)

**Comment by Maxdg** [comment]
@KasperFranz did download the libraries mentioned in #136 and replaced the libraries folder with that one. still same issue popping up

**Comment by KasperFranz** [comment]
you need to take the libraries from the same as you downloaded the jar

**Comment by Maxdg** [comment]
I've done that. Thats what this issue is created on: "With Build 58(Alpha) and the respective Libraries folder".

Anyhow i've downloaded libraries from 58 again, problem still persists

**Comment by KasperFranz** [comment]
Your launch script is also wrong, you got 2 jar files? (it is just using the last one)

Can you provide the full crash log?

**Comment by Maxdg** [comment]
Launch script could be faulty, but if i remove the Forge part the error changes completely:

    2016-11-16 13:13:17,159 ERROR Error processing element Queue: CLASS_NOT_FOUND
    2016-11-16 13:13:17,252 ERROR Unable to locate appender TerminalConsole for logg
    er com.mojang
    2016-11-16 13:13:17,252 ERROR Unable to locate appender TerminalConsole for logg
    er
    2016-11-16 13:13:17,252 ERROR Unable to locate appender TerminalConsole for logg
    er net.minecraft
    2016-11-16 13:13:17,643 ERROR Error processing element Queue: CLASS_NOT_FOUND
    2016-11-16 13:13:17,690 ERROR Unable to locate appender TerminalConsole for logg
    er com.mojang
    2016-11-16 13:13:17,690 ERROR Unable to locate appender TerminalConsole for logg
    er
    2016-11-16 13:13:17,690 ERROR Unable to locate appender TerminalConsole for logg
    er net.minecraft

Full crash log(latest.log)
http://pastebin.com/dJ7F8TkN

**Comment by KasperFranz** [comment]
That is not your crash-log that is just your log. there is a crashlog in the folder crash-reports

**Comment by Maxdg** [comment]
Forgive my sleepy head xD
http://pastebin.com/KEEmgc7E

**Comment by KasperFranz** [comment]
Your error is something else than you reported:
`java.lang.OutOfMemoryError: GC overhead limit exceeded`

this can be resolved by using the following launch script

```
java -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms4G -Xmx6G -XX:hashCode=5 -Dfile.encoding=UTF-8 -jar Thermos-1.7.10-<version>.jar --log-strip-color
```

(taken from the [documentation](https://cyberdynecc.github.io/Thermos/install#))

**Comment by Maxdg** [comment]
"There is no crashlog.. The log i pasted was from 2 days ago"

**Comment by KasperFranz** [comment]
Since you edited your post i am just gonna put this here for reference:

> Forgive my sleepy head xD
> http://pastebin.com/KEEmgc7E

There is nothing in common with the error you are saying you are getting and the logs you have provided?

**Comment by Maxdg** [comment]
(Facepalm) Kasper "The log i pasted was from 2 days ago" references to that log, the whole reason i've edited it...

**Comment by KasperFranz** [comment]
Lets sum up: 
the crash report you posted (and now removed) was from today (look at the date in it) and is because of a Out of Memory Exception.

Your logs (server log & FML logs) doesn't contain anything about `java.lang.NoClassDefFoundError: joptsimple/OptionSpe`

So my suggestion for you to solve this is to change your launch script as suggested earlier in this thread 

> ```
> java -XX:+UseG1GC -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:MetaspaceSize=1024m -XX:MaxMetaspaceSize=2048m -XX:+AggressiveOpts -XX:MaxGCPauseMillis=10 -XX:+UseStringDeduplication -Xms4G -Xmx6G -XX:hashCode=5 -Dfile.encoding=UTF-8 -jar Thermos-1.7.10-<version>.jar --log-strip-color
> ```
> 
> (taken from the [documentation](https://cyberdynecc.github.io/Thermos/install#))

**Comment by Maxdg** [comment]
Kasper you are "assuming" it's, it's because of another fix done last month due to halloween, we prevented it from changing textures to halloween by changing system date since the mod configs from enderIO etc didn't provide a way to disable this behaviour. The date hasn't been set back since then, so please accept the fact its actually an older day log instead of todays.

**Comment by Time6628** [comment]
Your libraries are incorrect, as far as I can tell because pastebin is block where I am currently.

**Comment by Maxdg** [comment]
Nope, both Library and .jar are from Alpa58

**Comment by Time6628** [comment]
You're running forge with that script, not thermos. You do not need forge to run thermos, just run the thermos jar.

**Comment by Maxdg** [comment]
I'll make another ticket then to fix the new error popping up

**Comment by Bogdan-G** [comment]
notice:
>java.lang.OutOfMemoryError: GC overhead limit exceeded

add: `-XX:-UseGCOverheadLimit`, and think or it crashlog client?
