### ISSUE TITLE
Can't build thermos from source

### ISSUE THREAD

**Issue by xorinzor** [CyberdyneCC/Thermos#577]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
N/A

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
N/A

**Explanation of issue:**
When I try to build Thermos from source using scripts/setup.sh the build eventually fails at:
```
A problem occurred evaluating root project 'Thermos'.
> Could not resolve all dependencies for configuration ':libraries'.
   > Could not resolve net.minecraft:server:1.7.10.
     Required by:
         cyberdynecc:Thermos:1.7.10-1614.UNOFFICIAL
      > Could not resolve net.minecraft:server:1.7.10.
         > Could not get resource 'https://repo.prok.pw/net/minecraft/server/1.7.10/server-1.7.10.pom'.
            > Could not GET 'https://repo.prok.pw/net/minecraft/server/1.7.10/server-1.7.10.pom'.
               > hostname in certificate didn't match: <repo.prok.pw> != <prok.pw> OR <prok.pw> OR <www.prok.pw>
      > Could not resolve net.minecraft:server:1.7.10.
         > Could not get resource 'https://libraries.minecraft.net/net/minecraft/server/1.7.10/server-1.7.10.pom'.
            > Could not GET 'https://libraries.minecraft.net/net/minecraft/server/1.7.10/server-1.7.10.pom'. Received status code 403 from server: Forbidden
   > Could not resolve pw.prok:KImagine:0.2.0.
     Required by:
         cyberdynecc:Thermos:1.7.10-1614.UNOFFICIAL
      > Could not resolve pw.prok:KImagine:0.2.0.
         > Could not get resource 'https://repo.prok.pw/pw/prok/KImagine/0.2.0/KImagine-0.2.0.pom'.
            > Could not GET 'https://repo.prok.pw/pw/prok/KImagine/0.2.0/KImagine-0.2.0.pom'.
               > hostname in certificate didn't match: <repo.prok.pw> != <prok.pw> OR <prok.pw> OR <www.prok.pw>
      > Could not resolve pw.prok:KImagine:0.2.0.
         > Could not get resource 'https://libraries.minecraft.net/pw/prok/KImagine/0.2.0/KImagine-0.2.0.pom'.
            > Could not GET 'https://libraries.minecraft.net/pw/prok/KImagine/0.2.0/KImagine-0.2.0.pom'. Received status code 403 from server: Forbidden
```
**How to recreate this issue:**
Just run scripts/build.sh

**Thermos Version:**
Master/Tag 57

**Comment by Robotia** [comment]
The prok.pw repository where a lot of our libraries came from has been down as of late. Right now, I am unable to build myself and haven't had the time to fix this. I plan on working on it this weekend.

**Comment by chezpaul** [comment]
Were you able to work on it? I wanted to build Thermos too but couldn't... Pleeeeease....  ;-)

**Comment by xorinzor** [comment]
I don't think I ever got this to work, turned out I could do something else to solve my original (not this) issue, although I have no clue what that was.

**Comment by linkinkov** [comment]
I can set up own repo @Robotia if you need

**Comment by chezpaul** [comment]
Any more news on this? I really would like to try and compile this.
Thanks

**Comment by Time6628** [comment]
no

**Comment by idnthvn** [comment]
Bummer, really could use this

**Comment by clienthax** [comment]
Going be the error it seems the ssl cert is missing locally.
Change https to http on your local build.gradle and it should start working

**Comment by UzminTid** [comment]
So..now Thermos can't be built due to the change of prok.pw and it seems in no way this can be solved?

**Comment by chezpaul** [comment]
What? So wait, is this the end of Thermos?

**Comment by Time6628** [comment]
Last commit to thermos was in august, pretty sure Rob started redoing it from the last good KCauldron commit. Now everyone is busy with school and what not.

**Comment by clienthax** [comment]
```
wget https://repo.prok.pw/net/minecraft/server/1.7.10/server-1.7.10.pom
wget https://repo.prok.pw/net/minecraft/server/1.7.10/server-1.7.10.jar
mvn -Dpackaging=jar install:install-file -Dfile=server-1.7.10.jar -DpomFile=server-1.7.10.pom

wget https://repo.prok.pw/pw/prok/KImagine/0.2.0/KImagine-0.2.0.pom
wget https://repo.prok.pw/pw/prok/KImagine/0.2.0/KImagine-0.2.0.jar
mvn -Dpackaging=jar install:install-file -Dfile=KImagine-0.2.0.jar -DpomFile=KImagine-0.2.0.pom
```

Change
```
        maven {
            name 'prok'
            url 'https://repo.prok.pw/'
        }
```
to
```
     	mavenLocal()
//        maven {
//            name 'prok'
//            url 'https://repo.prok.pw/'
//        }
```

**Comment by chezpaul** [comment]
Where do I change this maven line? I'm sorry not to be a github pro.  ;-(

**Comment by ApplePieXpto** [comment]
@chezpaul build.gradle
also, you need maven installed with the environment variable path defined on your system
