### ISSUE TITLE
Why are there no updates for so long?

### ISSUE THREAD

**Issue by SourcePowered** [CyberdyneCC/Thermos#578]
There are too many issues need to be repaired, why not always update it?
Sponge can't use it at all ........ Whether optimization or efficiency, or security.

- - -

Allow me to whine:

When we just upgraded to Sponge 1.10.2, not yet stable, mojang has been upgraded to 1.11. F**K IT!!!

I think we need a version that is dedicated to the Mod Server, instead of constantly updating. After all, the Mod server is very complex. Mojang was joking(f**king) with us and I'm waiting for **Minecraft 1.99.99**. :)

Microsoft said: F**K ALL OF YOU!!! We are creating Minecraft CSharp Version!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ccxufo** [comment]
...Everyone is busy,I also hope that it could update to new version.

**Comment by Time6628** [comment]
Thermos is made by a bunch of people who make it in their spare time, Robotia is currently working on rebasing all the commits from KCauldron to Thermos and I am busy porting everything to sponge.
