### ISSUE TITLE
Not start and not close

### ISSUE THREAD

**Issue by Electrodevice** [CyberdyneCC/Thermos#580]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log: https://gist.github.com/Electrodevice/1d65eacf2ddc074093d229defd0f6aef

**Explanation of issue:**
No any gui. Java(tm) stay in tasks and eat 224MB.

Thermos-1.7.10-1614-server.jar

**Modpack Name: no mods

**Plugins Installed:**
no plugins

**Forge Version:**
MinecraftForge v10.13.4.1614

**Comment by spannerman79** [comment]
Read your own log - https://gist.github.com/Electrodevice/1d65eacf2ddc074093d229defd0f6aef#file-latest-log-L19

**Comment by Electrodevice** [comment]
Good, and what can I do? Thermos-1.7.10-1614-server.jar was started my own right hand.

**Comment by Electrodevice** [comment]
So I change start.cmd and string 19 no exist now.
And what?
No work with it to.
new log:
https://gist.github.com/Electrodevice/66325106bb4ceeadaba7224a8e203186

**Comment by Bogdan-G** [comment]
and what's the problem?
PS x32 OS is not recommended, it is desirable to x64

**Comment by Electrodevice** [comment]
No any problem. No thermos - no problem. Started using forge.

**Comment by Bogdan-G** [comment]
@Electrodevice you also run through java.exe?

**Comment by Electrodevice** [comment]
Haven't any idea about. I use forge + forge essentials.

**Comment by Bogdan-G** [comment]
Okay. All Cauldron fork's does not have an interface, only console mode, if the visibility is enabled by the user.
