### ISSUE TITLE
[Crash] The server has stopped responding!

### ISSUE THREAD

**Issue by Rsslone** [CyberdyneCC/Thermos#581]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/45iDtdLK
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/S9xGh9ch
**Explanation of issue:**
Random crash. Not sure if its due to Dynmap or not.
**How to recreate this issue:**
Not sure of cause.
**Modpack Name:** *(Only if public)*
TommyTek
**Mods Installed:**
Advanced Machines
AOBD
Applied Energistics
Aroma1997's Dimensional World
Backpack
Baubles
BiblioCraft
Big Reactors
Biomes o' Plenty
Blood Magic
Bookshelf
Botania
BuildCraft
Carpenter's Blocks
Chicken Chunks
Chisel
DenseOres
DogeMod
MoCreatures
Enchanting Plus
EnderIO
Extra Utilities
Flans Mod
Forestry
Forge MultiPart
Galacticraft
GrowthCraft
Hardcore Ender Expansion
Industrial Craft
Iron Chest
Jabba
Logistics Pipes
Mekanism
MineFactoryReloaded
Modular Powersuits
MrCrayfish's Furniture Mod
Natura
NEI
NetherOres
OpenBlocks
PneumaticCraft
Project Red
RailCraft
Recurrent Complex
Redstone Arsenal
SirenMod
Statues
Sync
Tinkerers Construct
Thermal Expansion
Waila
WarpBook
Witchery
**Plugins Installed:**
bPermissions
Essentials
SimpleBackup
WorldBorder
WorldEdit
WorldGuard
**Warmroast Report:** *(Optional)*

**Thermos Version:**
Thermos-1.7.10-1614-58
**Forge Version:**
v10.13.4.1614

**Comment by Time6628** [comment]
It looks like Dynmap.

**Comment by Bogdan-G** [comment]
and where the crash log?

**Comment by Rsslone** [comment]
I included both FML and Server log.

**Comment by spannerman79** [comment]
No you didn't @Rsslone - you only provided partials.

As @Time6628 stated - Dynmap - non thermos issue.
