### ISSUE TITLE
Server crash!

### ISSUE THREAD

**Issue by StarchierOrb** [CyberdyneCC/Thermos#582]
**Server Log:**http://pastebin.com/Rb1gAUwu

**FML Log(s):**http://pastebin.com/Rb1gAUwu

**Explanation of issue:**
  This randomly happened on my server while few players was online and i was away, i don't know  what exactly happened.   (I can get a full log because it was running on multicraft and the log was deleted)

**How to recreate this issue:** 
  i don't know

**Modpack Name**:(Only if public)
   none

**Mods Installed:**
 BiomesOPlenty , Lots of food , Minecraft comes alive

**Plugins Installed:**
  EssentialsX,  Vault,  ProtocolLib-v1_7_R4-3.6.4,  GlobalMarket,  Worldedit,  Worldguard
  Residence4.1.0.1 , MyPet
 
**Thermos Version:**
1.7.10-1614.58

**Forge Version:**
Latest

**Comment by spannerman79** [comment]
no log = unable to help

**Comment by Time6628** [comment]
Go into the logs folder and copy and paste the log file that has the problem in it.
