### ISSUE TITLE
server freezing

### ISSUE THREAD

**Issue by Cronosus** [CyberdyneCC/Thermos#583]
hello, i have on server problem with freezing.
help please.

**Server Log:** 
http://cronos.wz.cz/mc/281116latest.log
**FML Log(s):**
http://cronos.wz.cz/mc/281116fml-server-1.log
**Explanation of issue:**
server freezing, and can't restart (no crashing)
**How to recreate this issue:**
after some time of server running
**Modpack Name:** 
traincraft.cz (on technic platform)
**Mods Installed:**
http://cronos.wz.cz/mc/mods.PNG
**Plugins Installed:**
http://cronos.wz.cz/mc/plugins.PNG
**Thermos Version:**
Build 58 (i think, or 57.. now i'm not sure.. where to find?)
**Forge Version:**
10.13.4.1617.1710

**Comment by Time6628** [comment]
CoFHCore, not thermos.

**Comment by Cronosus** [comment]
yes, but thex not helps, because Thermos... :/
