### ISSUE TITLE
Server Crash/Lockup

### ISSUE THREAD

**Issue by CobaltSparkz** [CyberdyneCC/Thermos#584]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

http://pastebin.com/dPPJyHPX

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

http://pastebin.com/dPPJyHPX

**Explanation of issue:**

Server hang

**How to recreate this issue:**

N/A

**Modpack Name:** *(Only if public)*

CrundeeCraft

**Mods Installed:**

CrundeeCraft pack defaults

**Plugins Installed:**

http://prntscr.com/dcwq06

**Warmroast Report:** *(Optional)*

**Thermos Version:**

1448

**Forge Version:**

57

Seems to be the decobench again? Had this same error on 3-4 of our servers with different forge versions over the last few months

**Comment by Time6628** [comment]
Decocraft, not thermos.
