### ISSUE TITLE
Galacticraft gravity won't work in Thermos servers

### ISSUE THREAD

**Issue by Eufranio** [CyberdyneCC/Thermos#587]
**Explanation of issue:**
Galacticraft gravity won't work in Thermos servers. If you travel to the moon, you will walk like if you were in the overworld or any other place.

**How to recreate this issue:**
Travel to any planet and walk.

**Modpack Name:** *(Only if public)*
http://www.technicpack.net/modpack/magitech-server-1710.820227

**Mods Installed:**
www.magitechserver.com/mods

**Plugins Installed:**
```
PlaceholderAPI, MythicLib, PlugMan, VipZeroFIX, ConsoleSpamFix, MagiUtils, ChatReaction, MultiWorld, SkinsRestorer, MagiKits, BetterAlias, ItemRestrict, aUCVault, Itemizer, dynmap, LuckPerms, WorldEdit, EmptyWorldGenerator, Skript, OpenInv, Offline_Teleporter, ClearLag, AutoMessage, WorldBorder, ProtocolLib, DeathMessagesPrime, AutoSaveWorld, eZProtector, AsyncWorldEdit, Magi-GUI, Vault, FastLogin, LogBlock, Trading, HolographicDisplays, VipZero, WorldGuard, Legendchat, ChestCommands, MythicMobs, Prism, MyCommand, BungeeTabListPlus, Essentials, ScoreboardStats, RandomTP, Citizens, TagsGUI-2.0, DiscordSRV, FramePicture, CutePortals, skRayFall, EssentialsSpawn, AuthMe, AuthMeBridge, SharpSK, EffectLib
```
**Thermos Version:**
Build 58

**Forge Version:**
1.7.10-1614

**Comment by YuRaNnNzZZ** [comment]
Not a Thermos issue.
https://wiki.micdoodle8.com/wiki/Compatibility#Dynamic_Surroundings

**Comment by Eufranio** [comment]
Oh
