### ISSUE TITLE
1.10

### ISSUE THREAD

**Issue by Omuck3** [CyberdyneCC/Thermos#588]
Hello.  Are there any plans for a 1.10 version of Thermos?  I used it for 1.7.10, and it was great.  However, there's really nothing for 1.10 that allows forge+spigot plugins.

**Comment by spannerman79** [comment]
> Hello. Are there any plans for a 1.10 version of Thermos?

No


> However, there's really nothing for 1.10 that allows forge+spigot plugins.

https://www.spongepowered.org/
