### ISSUE TITLE
doTickpengding causes tps to be less than 4

### ISSUE THREAD

**Issue by azbh111** [CyberdyneCC/Thermos#589]
Timings report : 
http://hastebin.com/raw/enitazebag
server: Thermos-1.7.10-1614-58-server
plugins:
http://hastebin.com/cebexefibi

![image](https://cloud.githubusercontent.com/assets/18545310/20909212/3f38482a-bb95-11e6-885c-fcc3a7974a41.png)

It often happens,,and I have to restart the server

**Comment by spannerman79** [comment]
Non thermos issue.

Either plot plugin or too much redstone devices in plot world

**Comment by azbh111** [comment]
it is resource world,not plot.and there is no redstone devices in resource world

**Comment by azbh111** [comment]
the plot plugin is only used to show plugins

**Comment by azbh111** [comment]
What does doTickPengding means?

**Comment by spannerman79** [comment]
Use Google

As I already stated - non thermos issue
