### ISSUE TITLE
SkillAPI support

### ISSUE THREAD

**Issue by evernife** [CyberdyneCC/Thermos#590]
**Explanation of issue:**
SkillAPI do not work on Thermos

Can find more information here, in this issue!

https://github.com/Eniripsa96/SkillAPI/issues/97

**How to recreate this issue:**
Put SkillAPI on plugins folder

**Modpack Name:** *(any)*

**Mods Installed:** *(any)*

**Plugins Installed:** *(SkillApi)*

**Thermos Version:** 58;57;56

**Forge Version:** 1614

**Comment by spannerman79** [comment]
The dev has already stated the following;
>With it also being an abandoned project and minecraft now being 4 major versions ahead of it, I don't think support will be added to it

Seems clear to me.  This issue creation is pointless

**Comment by evernife** [comment]
But, just before that, he said:

> Cauldron is unfortunately not supported since it breaks any sort of reflection I need to use to accomplish certain features. 

So, that's the why i am here to ask for thermos to fix what cauldron had "breaked", of course, if it is possible :/ and viable

**Comment by spannerman79** [comment]
God help me.....
Really read what I previously commented. As in **even if it was resolved support wouldn't be added!!**

**Comment by evernife** [comment]
![image](https://cloud.githubusercontent.com/assets/11357801/20994495/e0475f24-bcd7-11e6-8643-aead1d3bf243.png)

**Comment by evernife** [comment]
No support so?
