### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by cpaxe97** [CyberdyneCC/Thermos#591]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** http://pastebin.com/PPJsy5NT

**FML Log(s):** http://pastebin.com/jiTEMFBB - http://pastebin.com/5svXpWt6 - http://pastebin.com/1WjgAak1

**Explanation of issue:** Trying to get FTB Infinity working on this so I can get plugins it starts loading and give me the errors above.

**How to recreate this issue:** All I did was start the .jar on my mc panel

**Modpack Name:** *(Only if public)* FTB Infinity Evolved 1.7.10

**Mods Installed:** https://www.feed-the-beast.com/projects/ftb-infinity-evolved/relations/dependencies

**Plugins Installed:** None at the moment since I can't get it to work.

**Warmroast Report:** *(Optional)* N/A

**Thermos Version:** Thermos-1.7.10-1558-57

**Forge Version:** I think it''s 1558

**Comment by spannerman79** [comment]
Use 1614 not 1558

**Comment by cpaxe97** [comment]
http://pastebin.com/G2m49gWy

Think I'm having the same error.  I changed thermos to 1614 to

**Comment by spannerman79** [comment]
Read your logs!!
`[14:52:48] [Server thread/WARN]: **** FAILED TO BIND TO PORT!`

Non thermos issue

**Comment by cpaxe97** [comment]
Yeah I was just reading through it and saw that seeing if it starts up now

**Comment by spannerman79** [comment]
This is an issue tracer for actual issues, not for "I'm too lazy and just want to complain about issues when I'm a shrub and just toss out log files"

**Comment by cpaxe97** [comment]
Also, the first error I did post was a actual error.

**Comment by Chew** [comment]
Make sure to close this issue if it has been resolved.
