### ISSUE TITLE
The server Thermos #58 freezes stream.

### ISSUE THREAD

**Issue by TheJayse** [CyberdyneCC/Thermos#593]
Hello. I use a thermos core, and I ran into a problem. My server stops responding when loading the stream is not responding. When I started to look for the cause of the fall, I used jstack -l command. After the completion of the verification process - the magazine: http://pastebin.com/uKrcBLe0

I think that the main problem in the core. How to fix it? I am willing to pay for a solution to this problem.

**Comment by spannerman79** [comment]
No full log = unable to help.

Use the issue template - thats the reason it exists.

Non-thermos issue and incomplete issue creation.
