### ISSUE TITLE
FTB Infinity Server Crash

### ISSUE THREAD

**Issue by maginator** [CyberdyneCC/Thermos#596]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** :

**FML Log(s):** https://gist.github.com/maginator/4f5ee02435c00062b8e7cf702679572c (latest Log)

**Explanation of issue:** I create a FTB Infinity Server and i try to start it with Thermos but its crahs

**How to recreate this issue:** Installing a FTB Infinty

**Modpack Name:** *(Only if public)* FTB Infinity Evolved

**Mods Installed:** FTB Infinity Evolved

**Plugins Installed:** No

**Warmroast Report:** *(Optional)*

**Thermos Version:** 1.7.10-1611

**Forge Version:**1.7.10-1611

**Comment by Eufranio** [comment]
Could you port the `crash-report-...` file generated in the `crash-reports` folder?

**Comment by maginator** [comment]
Crash: https://gist.github.com/maginator/df9cde04918de385f03ea98b3281eade

**Comment by Eufranio** [comment]
A falling gravel is erroring, probably because of bad generated chunks. Is your world new? You can delete the file **r-0.-1.mca** from the **/world/region/** folder (it will delete all the chunks in this region)

**Comment by maginator** [comment]
yes world is new generaded but i try to delet it. i wish i can read the crash report that would make something easy and i must not wirte for help

**Comment by maginator** [comment]
its crash ;( : https://gist.github.com/maginator/fe249df2fab39fcfb6748bf596798e4c

**Comment by Eufranio** [comment]
You're using **client** mods in the server (the one from the crash is ResourceLoader)

**Comment by maginator** [comment]
oh right im copy my clinet mods to the serve sry for the comment

**Comment by Eufranio** [comment]
If you fixed your issue you can close this topic xD
