### ISSUE TITLE
Crash with Hardcore Ender Expansion 

### ISSUE THREAD

**Issue by Eufranio** [CyberdyneCC/Thermos#597]
Explanation and versions right here: https://github.com/chylex/Hardcore-Ender-Expansion/issues/200

The dev said it's an cauldron error. I'm running Thermos 1614 B58.

**Comment by Time6628** [comment]
Please follow the format.

**Comment by Eufranio** [comment]
Just opened a new issue: https://github.com/CyberdyneCC/Thermos/issues/598
