### ISSUE TITLE
Crash with Hardcore Ender Expansion mod

### ISSUE THREAD

**Issue by Eufranio** [CyberdyneCC/Thermos#598]
**Explanation of issue:**
After using the Dragon egg in the Temple to restore the End and the Dragon the entire server crashes. Afterwards if anyone tries to enter the End again, the server crashes again. This crash was already reported to the HEE dev, and he said [it's specifically a Cauldron error... ](https://github.com/chylex/Hardcore-Ender-Expansion/issues/200#issuecomment-249163583)

**How to recreate this issue:**
Just use the Dragon Egg in a Temple from Hardcore Ender Expansion.

**Modpack Name:** *(Only if public)*
Happens in [New Horizons](https://github.com/GTNewHorizons/NewHorizons) and [MagiTech (my pack](http://www.technicpack.net/modpack/magitech-server-1710.820227)

**Plugins Installed:**
http://pastebin.com/21xhgiVR

**Thermos Version:**
Build 58
**Forge Version:**
1.7.10-1614

Hardcore Ender Expansion v1.7.10 - 1.8.6.

**Comment by HeyZeer0** [comment]
Hello @Robotia and @Time6628 
I know what is causing this error, but i dont know how can i fix it.

That is the crash:
http://pastebin.com/p9CyDBhy

Hardcore Ender Expansion is trying to respawn the player using **[THIS](https://github.com/chylex/Hardcore-Ender-Expansion/blob/HEE1-1.7.10/src/main/java/chylex/hee/system/util/DragonUtil.java#L196)** method.
What method can i replace to fix that error?

Thanks =)
