### ISSUE TITLE
MineTweaker?/Modtweaker? crash

### ISSUE THREAD

**Issue by Eizock** [CyberdyneCC/Thermos#600]
**Server Log:** http://pastebin.com/6hqDMtGR
**FML Log(s):** http://pastebin.com/gMqpEvVm
**Crash-Report:** http://pastebin.com/U39BGYtK

**Explanation of issue:**
Custom Modpack just won't start with cauldron/kcauldron/thermos.

**How to recreate this issue:**
Download my zip (contains mods and config folder):  https://www.dropbox.com/sh/ygg8adf8fzhlurs/AAAHjW8dgZEr5lIFA-wE4qNCa?dl=1

**Modpack Name:** *(Only if public)*
N/A

**Mods Installed:**
mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
FML{7.10.99.99} [Forge Mod Loader] (Thermos-1.7.10.jar)
Forge{10.13.4.1614} [Minecraft Forge] (Thermos-1.7.10.jar)
kimagine{0.2} [KImagine] (minecraft.jar)
appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar)
CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
itemphysic{1.1.5} [ItemPhysic] (minecraft.jar)
Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar)
NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar)
OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar)
<CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar)
debug{1.0} [debug] (denseores-1.6.2.jar)
IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar)
AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar)
appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar)
bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar)
ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar)
bagginses{2.1.1} [Bagginses] (Bagginses-2.1.1.jar)
betterbuilderswands{0.8.0} [Better Builder's Wands] (BetterBuildersWands-0.8.0-1.7.10r89+339bc1f.jar)
CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar)
ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar)
ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar)
BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar)
Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar)
Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar)
BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar)
BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar)
BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar)
BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar)
BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar)
BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar)
BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar)
BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar)
BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar)
Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar)
BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar)
ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar)
CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar)
ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar)
ComputerCraft{1.74} [ComputerCraft] (ComputerCraftPlusComputerCraftEdu1.74.jar)
ComputerCraftEdu{1.74} [ComputerCraftEdu] (ComputerCraftPlusComputerCraftEdu1.74.jar)
creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.24 mc1.7.10.jar)
ElecCore{1.4.294} [ElecCore] (ElecCore-1.7.10-1.4.294.jar)
deepresonance{1.1.4} [DeepResonance] (deepresonance-1.1.4.jar)
DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2h.jar)
funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-7.jar)
MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.464.jar)
Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar)
EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar)
numina{0.4.1.103} [Numina] (Numina-0.4.1.103.jar)
MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar)
ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar)
powersuits{@VERSION@} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.1.107.jar)
ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar)
ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar)
TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar)
DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V16d.jar)
Dynmap{2.3-163} [Dynmap] (Dynmap-2.3-forge-1.7.10.jar)
endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar)
EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar)
EnderTech{1.7.10-0.3.2.405} [EnderTech] (EnderTech-1.7.10-0.3.2.405.jar)
enderutilities{0.5.3} [Ender Utilities] (enderutilities-1.7.10-0.5.3.jar)
extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar)
harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar)
ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar)
fc-dummy{0} [fc-dummy] (fastcraft-1.23.jar)
fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar)
MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar)
FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar)
FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar)
GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.464.jar)
GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar)
iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar)
Hats{4.0.1} [Hats] (Hats-4.0.1.jar)
HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar)
headcrumbs{1.7.4} [Headcrumbs] (Headcrumbs-1.7.4.jar)
HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar)
IC2NuclearControl{2.4.2a} [Nuclear Control 2] (IC2NuclearControl-2.4.2a.jar)
immersiveintegration{0.6.8} [Immersive Integration] (immersiveintegration-0.6.8.jar)
ImmibisCore{59.0.1} [Immibis Core] (Immibis-Core-1.7.10.jar)
inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar)
inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar)
IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar)
JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar)
journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar)
LogisticsPipes{0.9.3.128} [Logistics Pipes] (logisticspipes-0.9.3.128.jar)
magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar)
magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury] (magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar)
MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar)
MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar)
MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar)
MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar)
modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar)
ModularForcefieldSystem{3.0-ALPHA-7} [Modular Forcefield System] (ModularForcefieldSystem-1.7.10-3.0-ALPHA-7.jar)
MorePlanet{1.3.5} [More Planets] (More-Planets-1.7.10-1.3.5.jar)
Morpheus{1.7.10-1.6.20} [Morpheus] (Morpheus-1.7.10-1.6.20.jar)
NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar)
OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar)
OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar)
openmodularturrets{2.2.4-225} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.2.4-225.jar)
OpenPeripheralCore{1.3} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-7.jar)
OpenPeripheral{0.5.1} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-7.jar)
OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-7.jar)
PneumaticCraft{1.12.7-150} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.7-150-universal.jar)
PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar)
PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar)
SonarCore{1.1.3} [SonarCore] (SonarCore-1.7.10-1.1.3.jar)
PracticalLogistics{0.2.4} [Practical Logistics] (Practical-Logistics-1.7.10-0.2.4.jar)
ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar)
ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar)
ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar)
ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar)
ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar)
ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar)
ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar)
QuarryPlus{2.1.0} [QuarryPlus] (QuarryPlus-1.7.10-2.1.0.jar)
RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar)
rftools{4.23} [RFTools] (rftools-4.23.jar)
RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V16d.jar)
simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar)
SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar)
StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar)
StevesAddons{0.10.16} [Steve's Addons] (StevesAddons-1.7.10-0.10.16.jar)
StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar)
StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar)
StorageDrawers{1.7.10-1.10.8} [Storage Drawers] (StorageDrawers-1.7.10-1.10.8.jar)
ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171.jar)
TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar)
TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar)
Translocator{1.1.2.16} [Translocator] (Translocator-1.7.10-1.1.2.16-universal.jar)
VeinMiner{0.35.1_1.7.10-a8c76e8} [Vein Miner] (VeinMiner-0.35.1-1.7.10r481.jar)
VeinMinerModSupport{0.35.1_1.7.10-a8c76e8} [Mod Support] (VeinMiner-0.35.1-1.7.10r481.jar)
WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar)
McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar)
MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar)
RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar)
aobd{2.9.2} [Another One Bites The Dust] (AOBD-2.9.2.jar)
denseores{1.0} [Dense Ores] (denseores-1.6.2.jar)
ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)
MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar)

**Plugins Installed:**
None

**Thermos Version:**
Thermos Build 58

**Forge Version:**
1.7.10-1614

**Comment by Eufranio** [comment]
Can you please send your crash-report file located in the crash-reports folder?

**Comment by Eizock** [comment]
@Eufranio Updated issue with a crashreport :D

**Comment by Eufranio** [comment]
Well, minetweaker doesn't seem to be the fault, but some other mod that broke your stuff... Good luck, can't identify what exactly it is.

**Comment by Eizock** [comment]
@Eufranio Hmm ok but Thanks anyway

**Comment by Time6628** [comment]
DragonAPI.
