### ISSUE TITLE
Console Log Spam. 

### ISSUE THREAD

**Issue by Ragestrike** [CyberdyneCC/Thermos#601]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** http://pastebin.com/7MBw7g4n
**FML log** https://paste.ee/p/K1IZ3

**Explanation of issue:**  Installed Thermos on a hosting website. It runs perfectly fine. but it spams my console log with that error. Can you please make it not want to write in restricted folders on host servers.

i contacted the host and they said 

"It tries to write in /etc/ folder.

- system : /etc/.java/.systemPrefs/
- user : ~/.java/.userPrefs/

Sorry but we can't permit to Thermos to write in this Java directory, it can be security issue. So we don't have a fix for this."

**Modpack Name:** *(Only if public)* space astronomy

**Thermos Version:** 1.7.10-1614-58-server

**Forge Version:** Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10

**Comment by Time6628** [comment]
This is because java cannot right there because it has no perms. Not thermos.
