### ISSUE TITLE
Deconstruction table issues

### ISSUE THREAD

**Issue by checkium** [CyberdyneCC/Thermos#605]
You will receive NO SUPPORT if you do not follow the template below. (Vous ne receverez pas aucune aide si vous effacer ce modèle)

**Server Log:** http://pastebin.com/ZQf8xxmZ (I had to cut some parts because of pastebin's limit)

**FML Log(s):** Since the logs are a bit old (but the error is the same), I couldn't find the fml log, since it doesn't seems to save.

**Explanation of issue:** The mod "Deconstruction table" throws the error java.util.ConcurrentModificationException

**How to recreate this issue:** Start thermos with the Deconstruction Table mod

**Modpack Name:** The Unleashed Survival (Technic)

**Mods Installed:** www.technicpack.net/modpack/the-unleashed-survival.928280/mods

**Plugins Installed:** BanItem, Griefprevention, Betterbeds, PremissionsEx, UChat and a custom plugin.

**Thermos Version:** 1.7.10-1614

**Forge Version:** 7.99.4.1614

Also, other errors with this mod exist since cauldron, as you can see [here](https://github.com/MinecraftPortCentral/Cauldron-Issues/issues/111)

**Comment by Eufranio** [comment]
Known issue with LegacyJavaFixer.

**Comment by checkium** [comment]
@Eufranio The error happens the same way.

**Comment by linkinkov** [comment]
Maybe update java and remove  LegacyJavaFixer?

**Comment by checkium** [comment]
@linkinkov Like I said, the error happens with or without LegacyJavaFixer, I already removed it. I'm running java 8 u111

**Comment by Eufranio** [comment]
Learn how to update your mods, we can't do it for you.

**Comment by checkium** [comment]
@Eufranio Deconstruction Table is on the latest version.

**Comment by Eufranio** [comment]
It isn't.

**Comment by checkium** [comment]
Oh.. Looks like theres a new version on curse that isn't on minecraft forums.. Let me test it.

**Comment by Eufranio** [comment]
because curse is where modders release their mods?????
