### ISSUE TITLE
tubestuff crash

### ISSUE THREAD

**Issue by Andrey-007** [CyberdyneCC/Thermos#606]
**Server Log:** http://pastebin.com/NYgPD7Xs*

**FML Log(s):** *http://pastebin.com/PG0SFstf*

**Explanation of issue:**
just before the collapse
photo https://yadi.sk/i/qiOmihd236oa9B
crash, cyclical server restart
**How to recreate this issue:**

**Modpack Name:** *none*

**Mods Installed:**
immibis-core-59.1.4
tubestuff-59.0.4
**Plugins Installed:**
none
**Thermos Version:**
58 (ALPHA)
**Forge Version:**
v1614

**Comment by Time6628** [comment]
Not thermos.

**Comment by Andrey-007** [comment]
It occurs only on the thermos
