### ISSUE TITLE
Microblocks Losing Block Data(?) in Player Inventories on Rejoin

### ISSUE THREAD

**Issue by SilverKytten** [CyberdyneCC/Thermos#609]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
Server logs are a bit too long to upload to either Github Gist or Pastebin, but here is a section where I grab some microblocks and relog? 
[Latest.log](http://pastebin.com/1bTBrs1N)

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
[FML-Server-Latest.log](http://pastebin.com/8VCPxZzu)

**Explanation of issue:**
Microblocks go invisible, in the inventory, but can still be placed - When placed, they're the same size/shape of block, but are now Ender-Thermic pumps, from ExtraUtilities.
![2017-01-14_18 03 34](https://cloud.githubusercontent.com/assets/2188185/21959618/0adf5304-da92-11e6-8d89-370ee3faec4f.png)

**How to recreate this issue:**
Log off of, and rejoin, server with microblocks in inventory.

**Modpack Name:** *(Only if public)*
Run With Nature

**Mods Installed:**
[1.7.10]bspkrsCore-universal-6.15.jar
CodeChickenLib-1.7.10-1.1.3.138-universal.jar
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
ForgeRelocation-1.7.10-0.0.1.4-universal.jar
ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar
MrTJPCore-1.7.10-1.1.0.33-universal.jar
PotionExtension-1.7.10-1.1.0.jar
AgriCraft-1.7.10-1.5.0.jar
animalsPlus-1.2.jar
AppleMilkTea2-1.7.10_2.9b.jar
Aquaculture-1.7.10-1.2.6.21.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
Baubles-1.7.10-1.0.1.10.jar
BetterChests-1.7.10-1.1.1.9.jar
BetterStorage-1.7.10-0.13.1.126.jar
BiblioCraft[v1.11.2][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiomesOPlenty-1.7.10-2.1.0.2027-universal.jar
Botania r1.8-249.jar
Carpenter's Blocks v3.3.8_dev_r2 - MC 1.7.10.jar
cfm-3.4.8-mc1.7.10.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel-2.9.5.11.jar
ChocoCraft-4.1.5.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
cookingbook-mc1.7.10-1.0.134.jar
CraftHeraldry 1.1.3.jar
CustomNPCs_1.7.10d(21feb16).jar
Decocraft-2.1.1_1.7.10.jar
DogeMod_0.5.2_[1.7.10].jar
DoggyStyle-1.1.3.99.jar
DrZharks MoCreatures Mod v6.3.1.zip
EnderStorage-1.7.10-1.4.7.37-universal.jar
Exotic Birds 1.7.10 - 1.0.3b.jar
ExtendedPotions-MC1.7.10-1.2.jar
ExtraButtons-1.7.10.1.jar
extrautilities-1.2.10.jar
fairylights-0.6.0-1.7.10.jar
FamiliarsAPI-1.7.10.jar
FamiliarsDefaultMobPack-1.7.10.jar
FamiliarsExtendedFamPack-1.7.10.jar
FamiliarsHerobrineFamPack-1.7.10.jar
fantastic-1.4.jar
fastcraft-1.21.jar
forestry_1.7.10-4.2.16.64.jar
GlowstoneWire-1.7.x-1.0.2.113.jar
GollumCoreLib-2.0.0-1.7.10.jar
growthcraft-apples-1.7.10-2.1.0.jar
growthcraft-bamboo-1.7.10-2.1.0.jar
growthcraft-bees-1.7.10-2.1.0.jar
growthcraft-cellar-1.7.10-2.1.0a.jar
growthcraft-core-1.7.10-2.1.0a.jar
growthcraft-fishtrap-1.7.10-2.1.0a.jar
growthcraft-grapes-1.7.10-2.1.0.jar
growthcraft-hops-1.7.10-2.1.0.jar
growthcraft-rice-1.7.10-2.1.0a.jar
Hamsterrific-0.2.0.zip
Hand-HeldPower-0.3.jar
Hats-4.0.0.jar
HatStand-4.0.0.jar
iChunUtil-4.1.3.jar
IguanaTinkerTweaks-1.7.10-2.1.6.jar
IGW-Mod-1.7.10-1.1.12-34-universal.jar
InventoryTweaks-1.59-dev-152.jar
ironchest-1.7.10-6.0.60.741-universal.jar
Jabba-1.2.1a_1.7.10.jar
JammyFurniture-5.0.0-1.7.10.jar
JustAnotherSpawner-0.17.6.jar
JustAnotherSpawnerCompatibilityAddon-1.2.0.jar
lom-1.7.10-3.2.2.jar
malisiscore-1.7.10-0.12.9.jar
malisisdoors-1.7.10-1.9.5.jar
Mantle-1.7.10-0.3.2.jar
MegaPlantPack-1.7.10.jar
MobAmputation-4.0.0.jar
MorePistons-2.0.0-1.7.10.jar
MorePlayerModels_1.7.10b.jar
MultiMine-1.7.10.jar
MultiPageChest-1.3.4-MC1.7.10.jar
natura-1.7.10-2.2.0.1.jar
neiaddons-1.12.14.40-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.1.jar
NoMoreRecipeConflict-0.3(1.7.10).jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
OceanCraft-1.7.10.jar
OpenBlocks-1.7.10-1.5.1.jar
OpenModsLib-1.7.10-0.9.1.jar
Pam's BoneCraft 1.7.2b.zip
Pam's Clay Spawn 1.7.10b.jar
Pam's DesertCraft 1.7.10a.zip
Pam's Get all the Seeds 1.7.10a.jar
Pam's HarvestCraft 1.7.10Lb.jar
Pam's Harvest the Nether 1.7.10a.jar
Pam's Mob Drop Crops 1.7.10a.zip
Pam's Need Moar Sticks 1.7.10a.jar
Pam's Random Pants 1.7.2a.zip
Pam's Simple Recipes 1.7.10a.jar
Pam's Temperate Plants 1.7.2b.zip
Pam's WeeeFlowers 1.7.2b.zip
PetBat-1.7.10.jar
PneumaticCraft-1.7.10-1.12.3-146-universal.jar
primitivemobs-1.0c-1.7.10.jar
ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar
ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar
ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar
ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar
ProjectRed-1.7.10-4.7.0pre12.95-World.jar
RandomThings-2.2.4.jar
RikMuldsCore_1.0c.jar
RopePlus-1.7.10.jar
Squicken-1.7-1.0.0.jar
Subsistence-1.7.10-0.0.9.7.jar
TConstruct-1.7.10-1.8.8.jar
TheCampingMod_2.1g.jar
Treecapitator-universal-2.0.4.jar
ttCore-MC1.7.10-0.1.1-78.jar
twilightforest-1.7.10-2.3.7.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
Wawla-1.0.5.120.jar
worldedit-forge-mc1.7.10-6.1.1-dist.jar
zz-backpacks 1.7.10 - 3.0.4.jar

**Plugins Installed:**
AutoGamemode, WorldEdit, EmptyWorldGenerator, Spawnz, TimTheEnchanter, Essentials, AutoShutdown, NoWither, WorldBorder, LWC, WorldGuard, ProtocolLib, Multiverse-Core, HeavySpleef, Multiverse-Inventories, EssentialsGeoIP, EssentialsChat, PermissionsEx, DiscordBridge, Signs, CraftIRC, SimplyVanish, ZavAutoMessager, EssentialsSpawn, TrollTools, MassiveCore, EnjinMinecraftPlugin, MCBans, MobArena, CreativeGates, LWC_Tools, SilkSpawners

**Thermos Version:**
https://github.com/TCPR/Thermos | 1.7.10-R0.1-SNAPSHOT

**Forge Version:**
1.7.10-10.13.4.1614

**Comment by Time6628** [comment]
Thermos is not maintained anymore, closing issue.
