### ISSUE TITLE
[Proposal] Fly-Hacks Detection

### ISSUE THREAD

**Issue by Robotia** [CyberdyneCC/Thermos#61]
Most servers have to enable in-game flight to allow players to fly with mod equipment.
However, this allows players to use fly-hack packs. I propose a feature that allows the detection of "non-flying" tools being equipped (item IDs would have to be configured by the server owner), allowing owners to detect and ban the use of fly-hacks.

**Comment by Bogdan-G** [comment]
option `allow-flight=true` does not give full freedom I modes movements

**Comment by spannerman79** [comment]
No, this is an issue with the actual mod and the dev themselves.

For example, in one of @ReikaKalseki mods there is a config file option that fixes this - allows the use of the jetpack within his mod/s and while on a vanilla forge server within server.properties you have `allow-flight=false`

I've seen some of the other modders make similar changes for their 1.8 mods but its hard to try to convince some of those modders to backport their fixes.

I'd say keep towards keeping compatibility with plugins like NoCheatPlus etc to pickup on this sort of thing then try to make it integrated into the server.  Look at how buggy spigots anti-xray engine eventually became........

**Comment by Robotia** [comment]
Spanner has a good point. I feel like it's possible to create a heuristic algorithm that would flag potential hackers based upon strange packet behavior. For instance, detect kill aura.

**Comment by spannerman79** [comment]
For anti Aura it would be best to ensure compatibility for plugins like https://www.spigotmc.org/resources/noaura-v2.10154/ (example only)

**Comment by ReikaKalseki** [comment]
> For example, in one of @ReikaKalseki mods there is a config file option that fixes this - allows the use of the jetpack within his mod/s and while on a vanilla forge server within server.properties you have allow-flight=false

This is done by directly resetting the flyingTickCount used to check to see if a player is flying.

**Comment by Robotia** [comment]
Unlikely.
