### ISSUE TITLE
Developing mods, changing recipes

### ISSUE THREAD

**Issue by SergOmarov** [CyberdyneCC/Thermos#613]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/WWJLgysr

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/euBMxATb

**Explanation of issue:**
I am working on a mod for minecraft, and I needed to change the recipes of vanilla and other mods. Test on forge - everything works, there is no on thermos.

**How to recreate this issue:**
Source code of part of my mod: http://pastebin.com/cYPL5UwN

**Modpack Name:** *(Only if public)*

**Mods Installed:**
BUILDCRAFT FORESTRY INDUSTRIALCRAFT EXPEREMENTAL IRONCHEST NUCLEARCONTROL GRAVISUITE EXTRA UTILITES COMPACTSOLARS APPLIED ENERGISTICS 2 PROJECT:RED BINNIE MODS CARPENTER'S BLOCKS WILD CAVES-3 CHISEL 2 RAILCRAFT ENDER IO THERMALEXPANSION THERMALFOUNDATION

**Plugins Installed:**World Edit, World Guard

**Warmroast Report:** *(Optional)*

**Thermos Version:**
build 57

**Forge Version:**
1.7.10-1614

**Comment by Time6628** [comment]
Use minetweaker.

**Comment by SergOmarov** [comment]
Prompt users to install it along with my mod?

**Comment by Time6628** [comment]
Minetweaker allows you to change recipes using scripts, it has to be installed on both client and server. If you are making a mod, you should change the recipes in your mod.
