### ISSUE TITLE
Custom Steve Server 1.7.10 crashes server on boot (not sure if it's thermos causing crash)

### ISSUE THREAD

**Issue by InuYasha86000** [CyberdyneCC/Thermos#615]
**Explanation of issue:**

I am not sure if this is caused directly by the Custom Steve Server 1.7.10 mod but I wanted to post the crash report here just in case: [http://pastebin.com/DiwAmmL7](url)

**How to recreate this issue:** add the Custom Steve Server 1.7.10.jar to the server

**Modpack Name:** *(Only if public)* The Valley

**Mods Installed:** info is in my modpacks client and server versions readme

**Plugins Installed:** Info is in my modpacks server version readme

**Warmroast Report:** *(Optional)*

**Thermos Version:** build 58 (I believe)

**Forge Version:** 1.7.10 1614

The custom steve server version is made to allow anyone running custom steve on there client to allow others to view there custom 3d model they are using (Custom steve allows MMD models to be used in place of normal steve)
here is a link to the forum topic for Custom Steve: [http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293772-1-7-10-customsteve-1-3-0beta-change-the-model-of](url)
I have also notified the creator of Custom Steve as well.

**Comment by Time6628** [comment]
that is a mod issue, not thermos.
