### ISSUE TITLE
DEAD!!!??

### ISSUE THREAD

**Issue by chezpaul** [CyberdyneCC/Thermos#616]
Can we call this project dead?
Are we there yet?
Or are you guys going to come in here and call me names for speaking out the truth?
I'm not complaining, I know it's hard work and we all have other shit to do. 
I just want to know if I should move on or not.
That's all.
Thanks for all the hard work.
Peace

**Comment by 008** [comment]
donate more and it will rise

**Comment by KasperFranz** [comment]
Read the top of the project page:

> (NO LONGER DEVELOPED)

**Comment by chezpaul** [comment]
I remember when I read this and got exited:

"Thermos is a fork of KCauldron, a craftbukkit forge server for Minecraft 1.7.10. After periods of inactivity on KCauldron's GitLab concerning major issues, Thermos was created to allow active members of the Minecraft coding community to optimize it and provide fixes in a timely manner.

We hope to eliminate all issues with craftbukkit forge servers. In the end, we envision a seamless, low lag Thermos experience."


Too bad
