### ISSUE TITLE
[Proposal] Teleport Crashing Players to Spawn

### ISSUE THREAD

**Issue by Robotia** [CyberdyneCC/Thermos#94]
In issue #55, the fact that player's can be stuck in "crashing chunks" and must manually have their data reset was mentioned.
I said the following in response: `I can create a mini algo that will reset player locations to the spawn if they log in/out in under a second two times in a row.`

I will look into implementation Friday evening / this weekend in EST.

**Comment by djoveryde** [comment]
Most of the time they tend to log in/log out within 5 seconds at times. What about setting it so if they log in/out within 10 seconds 3 times it will automatically send them to spawn. In theory there should be no reason to log in/out that many times within 10 seconds

**Comment by Robotia** [comment]
My my worry with this is possible abuse, it might be better to make it into a command.

**Comment by bookerthegeek** [comment]
I feel this would be better as a command. If servers want it to be automatic they can use command helper. Also, What if it is spawn that is corrupt? ideas....

- Command based;
 - Console
 - In Game
- Config;
 - Automatic / Command / Both
 - Permission level for command?
 - Location your teleported to
  - Example: Galactic science does not have spawn in the overworld

**Comment by Rubbertjuh** [comment]
Really hyped about this feature! ^_^ would love to see this being added

**Comment by djoveryde** [comment]
Ok instead of tp to spawn what about a random teleport instead, the same as players could use a /stuck command that will move them 20 blocks perhaps away from the area (insase of corrupt chunk or being stuck in the floor), and onto the surface.

**Comment by bookerthegeek** [comment]
@djoveryde No, Spawn is a good place to go. If spawn is corrupt, Server owners "should" know how to fix it.

A teleport of 20 blocks would not really fix anything with a corrupt chunk as it will crash you while you are in render distance of the corrupt chunk, not just in it. you would need to have a range of 656+ for servers with a render distance of 10 chunks.

And forgeessentials (I think) adds the /stuck. When I mentioned command, I was thinking staff.

**Comment by HandGrenade** [comment]
There is actually a plugin which is basically what you are suggesting: https://github.com/Vastrix/Offline-Teleporter

This adds the following commands:
/otp [player] - Teleports the sender to specified player.
/otphere [player] - Teleports the specified player to the sender.
/otpback - Teleports the sender to their location before having '/otphere' by another player.
/otpspawn [player] - Teleports specified player to spawn. (CONSOLE ONLY)

The only feature it doesn't include is the automatic teleportation based upon login times. :)

**Comment by Robotia** [comment]
Just use either that or NBTEdit/NBTExplorer.
