### ISSUE TITLE
[Proposal] ANSI Encoding for Console in lieu of UTF8

### ISSUE THREAD

**Issue by Esctogrillo** [CyberdyneCC/Thermos#99]
When someone type a word with accent ( ~ ´ ` ^ ª º ) the message on console looks like this:

[L] Mod | TKS TheTitanic10: Você - Está - Lá - Não
[L] Mod | TKS TheTitanic10: Voc├¬ - Est├í - L├í - N├úo
![console error](https://cloud.githubusercontent.com/assets/14919996/13028579/5abd55e2-d25a-11e5-9365-aa504a241836.png)

**Comment by Robotia** [comment]
Yes this is a common issue with UTF8 and foreign languages :cry: . I will see what I can do to fix this, I am sorry you are having this problem. Please share your launch script?

**Comment by Esctogrillo** [comment]
:start
java -d64 -server -XX:+UseG1GC -XX:hashCode=5 -Xms7G -Xmx7G -Dfml.ignorePatchDiscrepancies=true -noverify -Dfile.encoding=UTF-8 -jar Thermos23.jar nogui --log-strip-color
goto start

**Comment by Robotia** [comment]
Confirmed, bug for Windows but not Unix-based servers. This is a silly error that probably occurs with ALL forge servers.

**Comment by Robotia** [comment]
Broken by Forge 1614, please post the issue is there.
